dailydotdev/daily-api

- migrations/20200324164902_add_read_setting.js
- src/graphql/helpers/post.js
- src/graphql/schema/post.js
- src/models/event.js
- src/models/post.js
- src/models/settings.js
- test/fixtures/posts.js
- test/fixtures/settings.js
- test/integration/graphql/post.js
- test/integration/models/post.js
> feat(posts): Remove read articles from feed

- package-lock.json
- package.json
- src/index.ts
- src/trace.ts
A new fastify plugin was created that adds hooks to trace incoming requests automatically.
> feat: add stackdriver trace agent

- __tests__/SourceResolver.ts
- __tests__/__snapshots__/SourceResolver.ts.snap
- __tests__/helpers.ts
- package-lock.json
- package.json
- src/Context.ts
- src/apollo.ts
- src/compatibility/index.ts
- src/compatibility/publications.ts
- src/compatibility/utils.ts
- src/entity/Source.ts
- src/entity/SourceDisplay.ts
- src/entity/SourceFeed.ts
- src/entity/index.ts
- src/migration/1587658873043-Source.ts
- src/resolver/SourceResolver.ts
- src/resolver/index.ts
sources is a new query to fetch all available sources of the user.
This includes both public and private sources, if a source is both
public and private the private representation will be returned.
> feat: sources query

- __tests__/SettingsResolver.ts
- __tests__/__snapshots__/SettingsResolver.ts.snap
- package-lock.json
- package.json
- src/compatibility/index.ts
- src/compatibility/settings.ts
- src/entity/Settings.ts
- src/entity/index.ts
- src/migration/1588054676723-Settings.ts
- src/resolver/SettingsResolver.ts
- src/resolver/SourceRequestResolver.ts
- src/resolver/index.ts
`userSettings` and `updateUserSettings` are new query and mutation to get and update user settings, respectively.
> feat: get and update user settings

- __tests__/BookmarkResolver.ts
- __tests__/__snapshots__/BookmarkResolver.ts.snap
- src/apollo.ts
- src/compatibility/index.ts
- src/compatibility/posts.ts
- src/entity/Bookmark.ts
- src/entity/EmptyResponse.ts
- src/entity/Post.ts
- src/entity/Settings.ts
- src/entity/Source.ts
- src/entity/SourceRequest.ts
- src/entity/index.ts
- src/migration/1588088109887-Bookmark.ts
- src/migration/1588172477587-NullablePublishedAt.ts
- src/resolver/BookmarkResolver.ts
- src/resolver/SourceRequestResolver.ts
- src/resolver/index.ts
`addBookmarks` is a new mutation to save an array of posts as bookmarks. `removeBookmark` is a mutation to remove bookmark by post id.
> feat: add mutations to add and remove bookmarks

- __tests__/BookmarkResolver.ts
- __tests__/__snapshots__/BookmarkResolver.ts.snap
- __tests__/fixture/post.ts
- __tests__/fixture/source.ts
- src/compatibility/posts.ts
- src/entity/Bookmark.ts
- src/entity/Post.ts
- src/resolver/BookmarkResolver.ts
`bookmarks` query fetches the bookmarks feed of the user.
`/v1/posts/bookmarks` is the compatibility route of this query.
> feat: bookmarks query

- src/routes/settings.js
Adds showOnlyNotReadPosts to settings route so that it is not stripped out when updating. Check https://github.com/dailydotdev/daily-apps/pull/102#issuecomment-621059646 for more info
> Added showOnlyNotReadPosts setting

- __tests__/__snapshots__/feed.ts.snap
- __tests__/feed.ts
- src/compatibility/posts.ts
- src/schema/feed.ts
`sourceFeed` query generates a dedicated feed for a single source
> feat: source feed query

- __tests__/__snapshots__/posts.ts.snap
- __tests__/helpers.ts
- __tests__/posts.ts
- package-lock.json
- package.json
- src/common/index.ts
- src/common/slack.ts
- src/compatibility/posts.ts
- src/compatibility/utils.ts
- src/entity/HiddenPost.ts
- src/entity/index.ts
- src/errors.ts
- src/migration/1588662906958-HiddenPost.ts
- src/schema/posts.ts
`hidePost` and `reportPost` mutations hide and report a post.
Compatibility routes `POST /v1/posts/:id/hide` and `POST /v1/posts/:id/report` added accordingly
> feat: hide and report post mutations

- __tests__/__snapshots__/feed.ts.snap
- __tests__/feed.ts
- __tests__/helpers.ts
- src/common/feedGenerator.ts
- src/entity/Feed.ts
- src/entity/FeedSource.ts
- src/entity/FeedTag.ts
- src/entity/index.ts
- src/migration/1588863598567-Feed.ts
- src/schema/feed.ts
`FeedSettings` is a new type to manage the feed settings of a user. For example include only these tags and exclude these sources.
> feat: feed settings type and query

- __tests__/posts.ts
- src/common/feedGenerator.ts
Remove hidden posts from the feeds the user receives
> feat: hide hidden posts from feed

- __tests__/__snapshots__/feeds.ts.snap
- __tests__/feeds.ts
- package-lock.json
- package.json
- src/common/algolia.ts
- src/common/feedGenerator.ts
- src/common/index.ts
- src/entity/Post.ts
- src/schema/common.ts
- src/schema/feeds.ts
- src/schema/posts.ts
`searchPosts` is a new query to create a feed based on a search query. `searchPostSuggestions` is a query that returns query suggestions.
> feat: search posts and suggestions queries

- __tests__/__snapshots__/bookmarks.ts.snap
- __tests__/__snapshots__/compatibility.ts.snap
- __tests__/bookmarks.ts
- __tests__/compatibility.ts
- __tests__/feeds.ts
- src/apollo.ts
- src/common/feedGenerator.ts
- src/compatibility/posts.ts
- src/schema/bookmarks.ts
- src/schema/compatibility.ts
- src/schema/feeds.ts
Add deprecated fields and queries to support existing GraphQL API.
> feat: add backwards compatibility with graphql api v1.0

- __tests__/__snapshots__/sourceRequests.ts.snap
- __tests__/bookmarks.ts
- __tests__/feeds.ts
- __tests__/posts.ts
- __tests__/settings.ts
- __tests__/sourceRequests.ts
- package-lock.json
- package.json
- src/apollo.ts
- src/compatibility/utils.ts
- src/directive/AuthDirective.ts
- src/directive/UrlDirective.ts
- src/directive/index.ts
- src/errors.ts
- src/index.ts
- src/schema/posts.ts
- src/schema/sourceRequests.ts
Format errors to remove any sensitive details before sending it over to the client.
> feat: hide error details from client

- bin/background.ts
- src/index.ts
- src/workers/index.ts
- src/workers/newView.ts
Create a background worker to listen to Pub/Sub events.
View is the first supported event.
> feat: background worker to process view events

- __tests__/__snapshots__/newPost.ts.snap
- __tests__/newPost.ts
- src/workers/index.ts
- src/workers/newPost.ts
Add post to database upon Pub/Sub message and index it in Algolia.
> feat: background worker to process add post message

- __tests__/__snapshots__/sources.ts.snap
- __tests__/settings.ts
- src/compatibility/publications.ts
- src/compatibility/settings.ts
- src/compatibility/utils.ts
- src/index.ts
- src/schema/compatibility.ts
- src/schema/feeds.ts
After manual testing, I found out several major compatibility issues. This PR fixes them all and is compatible with v2.15.0
> fix: compatibility routes fixes

- __tests__/__snapshots__/notifications.ts.snap
- __tests__/notifications.ts
- src/entity/Banner.ts
- src/entity/index.ts
- src/migration/1589812598274-Banner.ts
- src/schema/notifications.ts
`banner` query returns the relevant banner information based on provided timestamp
> feat: banner query to receive promotions

- __tests__/__snapshots__/bookmarks.ts.snap
- __tests__/bookmarks.ts
- __tests__/setup.ts
- src/common/feedGenerator.ts
- src/schema/bookmarks.ts
- src/schema/compatibility.ts
Add flag to bookmarks query to get only unread bookmarks
> feat: unread bookmarks

- __tests__/__snapshots__/bookmarks.ts.snap
- __tests__/bookmarks.ts
- __tests__/helpers.ts
- src/Context.ts
- src/auth.ts
- src/common/feedGenerator.ts
- src/directive/AuthDirective.ts
- src/entity/Bookmark.ts
- src/entity/BookmarkList.ts
- src/entity/index.ts
- src/migration/1590596508994-BookmarkList.ts
- src/schema/bookmarks.ts
- src/schema/common.ts
- src/schema/compatibility.ts
Bookmarks now can be organized in lists. Each bookmark can belong to one list only.
Each list has a name and the user can create, remove, and rename a bookmark list.
When a list is deleted the bookmarks are ejected and go back to the default list.
The bookmark list is a premium feature and not available to everyone.
> feat: bookmark list

- __tests__/helpers.ts
- __tests__/sources.ts
- src/schema/sources.ts
`addPrivateSource` is a new mutation for premium users to add new private sources.
`sourceByFeeds` is a new query to check if the given feeds exist already and to prevent submitting them again.
> feat: add private source mutation

- __tests__/sources.ts
- src/schema/sources.ts
If user B adds the same private source user A already has, instead of creating a new source the existing one will be used.
This optimizes superfeedr usage and reduce potential cost.
BREAKING CHANGE:
Private sources may include only a one RSS feed from now on.
This breaks both sourceByFeeds and addPrivateSource.
Closes #106
> fix: merge existing private sources

- __tests__/segmentUser.ts
- __tests__/segmentUsers.ts
- helm/daily-api/templates/cronjobs.yaml
- package-lock.json
- package.json
- src/cron/index.ts
- src/cron/segmentUsers.ts
- src/entity/TagSegment.ts
- src/entity/index.ts
- src/migration/1593949036242-TagSegment.ts
- src/workers/index.ts
- src/workers/segmentUser.ts
The new job runs every week and segments the users to a set of predefined segments according to the users' views
> feat: new cron job to segment all users

- __tests__/newPost.ts
- src/workers/newPost.ts
> fix: check for existing url before saving new posts

- __tests__/posts.ts
- src/cron/tweetTrending.ts
- src/routes/rss.ts
- src/schema/posts.ts
The permalink field returns a URL to the post
> feat(post): add permalink field

- __tests__/__snapshots__/newUser.ts.snap
- __tests__/__snapshots__/updateUser.ts.snap
- __tests__/newUser.ts
- __tests__/updateUser.ts
- src/entity/User.ts
- src/entity/index.ts
- src/migration/1595345916300-User.ts
- src/workers/index.ts
- src/workers/newUser.ts
- src/workers/updateUser.ts
Add listeners to user events to replicate some of the information.
This information will be needed in the future for comments and upvotes
> feat: replicate partial user information

- __tests__/__snapshots__/newPost.ts.snap
- __tests__/__snapshots__/posts.ts.snap
- __tests__/posts.ts
- __tests__/sourceRequests.ts
- __tests__/updateViews.ts
- src/common/pubsub.ts
- src/cron/updateViews.ts
- src/entity/Bookmark.ts
- src/entity/Post.ts
- src/entity/Upvote.ts
- src/entity/index.ts
- src/migration/1595424192556-Upvote.ts
- src/schema/posts.ts
- src/schema/sourceRequests.ts
Add the ability to upvote and cancel an upvote from a post
> feat: add post upvotes

- __tests__/__snapshots__/comments.ts.snap
- __tests__/comments.ts
- __tests__/posts.ts
- src/common/pubsub.ts
- src/schema/comments.ts
A user can now upvote a comment or cancel an existing upvote
> feat: comment upvotes

- __tests__/posts.ts
- src/common/feedGenerator.ts
- src/schema/posts.ts
Add to Post type two new fields:
* upvoted - Whether the user upvoted this post
* commented - Whether the user commented this post
> feat(post): upvoted and commented fields

- __tests__/__snapshots__/posts.ts.snap
- __tests__/__snapshots__/updateFeaturedComments.ts.snap
- __tests__/posts.ts
- __tests__/updateFeaturedComments.ts
- helm/daily-api/templates/cronjobs.yaml
- src/apollo.ts
- src/common/feedGenerator.ts
- src/cron/index.ts
- src/cron/updateFeaturedComments.ts
- src/entity/Comment.ts
- src/migration/1596003287300-FeaturedComment.ts
- src/schema/comments.ts
- src/schema/posts.ts
- src/schema/users.ts
Add `featuredComments` field to the `Post` type.
Add `author` field to the `Comment` type.
Add cronjob to set featured comments.
> feat: featured comments

- __tests__/__snapshots__/comments.ts.snap
- __tests__/comments.ts
- src/common/commentsFeedGenerator.ts
- src/schema/comments.ts
- src/schema/common.ts
- src/schema/feeds.ts
New query to get post comments with sub comments
> feat: postComments query

- __tests__/__snapshots__/commentCommented.ts.snap
- __tests__/__snapshots__/commentUpvoted.ts.snap
- __tests__/__snapshots__/updateFeaturedComments.ts.snap
- __tests__/commentCommented.ts
- __tests__/commentUpvoted.ts
- helm/daily-api/templates/_helpers.tpl
- helm/daily-api/templates/secret.yaml
- package-lock.json
- package.json
- src/common/mailing.ts
- src/common/pubsub.ts
- src/common/users.ts
- src/cron/updateFeaturedComments.ts
- src/workers/commentCommented.ts
- src/workers/commentUpvoted.ts
- src/workers/index.ts
When a user gets an upvote or a reply to his/her comment, an email is sent to notify.
> feat: notification emails

- __tests__/__snapshots__/cronRss.ts.snap
- __tests__/__snapshots__/sourceRequests.ts.snap
- __tests__/cronRss.ts
- __tests__/fixture/rss.xml
- __tests__/helpers.ts
- __tests__/sources.ts
- bin/cron.ts
- helm/daily-api/templates/cronjobs.yaml
- package-lock.json
- package.json
- src/cron/cron.ts
- src/cron/index.ts
- src/cron/rss.ts
- src/entity/SourceFeed.ts
- src/migration/1598351006459-SourceFeedLastFetched.ts
Due to issue with Superfeedr, we are moving towards building an RSS parser system.
This is the first step and it will be tested on dev.to feed
> feat: new cron job to crawl rss feeds

- __tests__/compatibility.ts
- __tests__/posts.ts
- package-lock.json
- package.json
- src/common/feedGenerator.ts
- src/graphorm/graphorm.ts
- src/graphorm/index.ts
- src/schema/bookmarks.ts
- src/schema/compatibility.ts
- src/schema/feeds.ts
- src/schema/posts.ts
The first commit in a proof of concept for improving performance by fetching only the requested fields.
I created a standalone library as part of the codebase, called GraphORM. It turns a GraphQL resolve info to an SQL query.
> feat: fetch only necessary fields for graphql

- __tests__/posts.ts
- src/common/slack.ts
- src/schema/posts.ts
Add mutation to delete a post for moderators only
> feat: delete post mutation

- __tests__/commentCommented.ts
- __tests__/commentUpvoted.ts
- __tests__/newPost.ts
- __tests__/newUser.ts
- __tests__/newView.ts
- __tests__/segmentUser.ts
- __tests__/updateUser.ts
- bin/background.ts
- package-lock.json
- package.json
- src/workers/segmentUser.ts
- src/workers/worker.ts
Segment users background worker failed due to creating a pubsub instance on every message problem.
Update pubsub client version
> fix: reuse pubsub instance

- __tests__/commentFeaturedRep.ts
- __tests__/commentUpvotedRep.ts
- src/common/index.ts
- src/common/pubsub.ts
- src/common/reputation.ts
- src/migration/1600350754278-RetroReputation.ts
- src/workers/commentFeaturedRep.ts
- src/workers/commentUpvotedRep.ts
- src/workers/index.ts
Add migration to calculate reputation in retrospective.
Increase reputation when the user gets upvotes or featured comment
> feat: increase user reputation on upvote and featured comment

- __tests__/__snapshots__/comments.ts.snap
- __tests__/comments.ts
- src/schema/comments.ts
Add new query userComments to fetch comments by user id.
This new query is used in the profile page
> feat(comments): get comments by user

- __tests__/__snapshots__/commentCommented.ts.snap
- __tests__/__snapshots__/commentCommentedThread.ts.snap
- __tests__/commentCommented.ts
- __tests__/commentCommentedThread.ts
- src/common/mailing.ts
- src/common/users.ts
- src/workers/commentCommentedThread.ts
- src/workers/commentUpvoted.ts
Some of the notification emails got an update and require more variables.
Furthermore, repliers get also a notification email now when someone comments
> feat: update to new notification emails

- __tests__/tweetTrending.ts
- helm/daily-api/templates/cronjobs.yaml
- src/cron/tweetTrending.ts
Add frequency of tweet bot to 5 per day
Tweet dicussion links to increase awareness to daily
> feat: tweet discussions instead of direct links

- __tests__/__snapshots__/feeds.ts.snap
- __tests__/feeds.ts
- src/schema/feeds.ts
Get a feed of posts of a single author
> feat: author feed query

- __tests__/posts.ts
- src/graphorm/graphorm.ts
- src/graphorm/index.ts
- src/schema/compatibility.ts
- src/schema/posts.ts
If the logged-in user is the author of the post, they can get access to the number of views the post received
> feat: post views field

- __tests__/__snapshots__/users.ts.snap
- __tests__/users.ts
- src/schema/users.ts
Get the user statistics for the profile page
> feat: user stats query

- __tests__/__snapshots__/newPost.ts.snap
- __tests__/newPost.ts
- src/workers/newPost.ts
Add another method to match between posts and authors. Match the twitter:creator to the username
> feat: match authors based on username

- src/cron/updateTrending.ts
Limit trending articles to be able to reduce the trending threshold
> refactor: limit trending articles

- __tests__/__snapshots__/users.ts.snap
- __tests__/users.ts
- src/schema/users.ts
Implemented a new system to movtivate users to read more content by giving them medals based on their reading.
Practically, it is a new query `userReadingRank` that returns the relevant information
> feat: reading-based ranking system

- __tests__/__snapshots__/feeds.ts.snap
- __tests__/__snapshots__/keywords.ts.snap
- __tests__/feeds.ts
- __tests__/keywords.ts
- __tests__/workers/__snapshots__/newPost.ts.snap
- src/apollo.ts
- src/common/feedGenerator.ts
- src/entity/Keyword.ts
- src/migration/1609237342955-KeywordOccurrencesDefaultUpdate.ts
- src/schema/feeds.ts
- src/schema/keywords.ts
Add queries and mutations for the keywords backoffice system
> feat: keywords moderation api

- __tests__/__snapshots__/compatibility.ts.snap
- __tests__/__snapshots__/feeds.ts.snap
- __tests__/compatibility.ts
- __tests__/feeds.ts
- src/common/feedGenerator.ts
- src/schema/bookmarks.ts
- src/schema/compatibility.ts
- src/schema/feeds.ts
Optimize configured feed query to allow enabling the new blocked tags filters
> refactor: optimize configured feed query

- .gitignore
- create-topic.ts
- docker-compose.yml
- infra/index.ts
- infra/package-lock.json
- infra/package.json
> ci: upgrade debezium version to 1.6

- __tests__/__snapshots__/posts.ts.snap
- __tests__/posts.ts
- __tests__/workers/cdc.ts
- src/common/slack.ts
- src/entity/PostReport.ts
- src/migration/1635777599202-ReportReasonComment.ts
- src/schema/posts.ts
- src/workers/cdc.ts
- src/workers/postBannedEmail.ts
When a user reports a post, they can now provide a comment with their chosen reason.
DD-40
> feat: added comment to report reasons

- __tests__/workers/cdc.ts
- src/workers/cdc.ts
> refactor: send pubsub event for alerts on data creation 

- __tests__/__snapshots__/users.ts.snap
- __tests__/users.ts
- src/common/devcard.ts
- src/schema/users.ts
DD-36
Inline with the newest addition in our Profile Tooltip. This has the API for getting most-read tags by the user.
> feat: user most read tags query

- src/common/users.ts
The function used by the changes provided:
```
const authorizedHeaders = (userId: string): { [key: string]: string } => ({
authorization: `Service ${process.env.GATEWAY_SECRET}`,
'user-id': userId,
'logged-in': 'true',
});
```
> fix: missing headers for fetching features

- __tests__/personalizedFeed.ts
- src/personalizedFeed.ts
Instead of using multiple `zadd` commands when pushing the feed, we use a regular `set` command and do the pagination on the server side.
> refactor: reduce redis calls

- src/common/feedGenerator.ts
- src/personalizedFeed.ts
- src/schema/feeds.ts
- src/trace.ts
With our upcoming plans to improve the complexity of the feed algorithm, it's important that we will measure the performance of generating the feed
> refactor: add detailed tracing for feed v2

- __tests__/comments.ts
- src/schema/comments.ts
> fix: validation for comments with empty content

- __tests__/alerts.ts
- src/routes/alerts.ts
- src/routes/index.ts
DD-493
A dedicated fastify route for alerts related requests.
> feat: dedicated route for alerts-related requests for integration

- __tests__/users.ts
- src/common/users.ts
- src/schema/users.ts
DD-522 #done
Supports backward compatibility for calculating the ranks.
> fix: rank steps versioning

- __tests__/__snapshots__/users.ts.snap
- __tests__/users.ts
- src/entity/View.ts
- src/migration/1644408031624-addViewHiddenIndex.ts
- src/schema/users.ts
Added the search reading history API calls and test cases.
Related to:
https://github.com/dailydotdev/apps/pull/893
> feat: :sparkles: Added the search reading history API calls

- __tests__/setup.ts
- package.json
- src/common/devcard.ts
- src/entity/ActiveView.ts
- src/graphorm/index.ts
- src/migration/1645627361402-ActiveView.ts
- src/schema/users.ts
- src/workers/checkDevCardEligibility.ts
I've added a `ActiveView` viewEntity 
using this entity will automatically not load deleted views, so we don't have to exclude them by hand.
DD-551 #done
> feat: exclude deleted views

- __tests__/__snapshots__/comments.ts.snap
- __tests__/__snapshots__/users.ts.snap
- src/common/markdown.ts
- src/common/post.ts
- src/common/users.ts
- src/workers/commentMentionEmail.ts
This also includes a fix for recommending users without a username as part of the post commented users.
> fix: missing character and avoid email spamming in user mention

- __tests__/__snapshots__/comments.ts.snap
- __tests__/__snapshots__/users.ts.snap
- __tests__/comments.ts
- __tests__/users.ts
- src/schema/comments.ts
DD-468 #done
When generating the preview, we will be just utilizing our existing function to provide the same result than re-creating the overrides in the frontend.
I have also removed the flaky test which was deemed unnecessary. Reference: https://dailydotdev.slack.com/archives/C02E2C3C13R/p1646829007663149?thread_ts=1646818642.801639&cid=C02E2C3C13R
> feat: query for comments preview

- __tests__/__snapshots__/comments.ts.snap
- __tests__/comments.ts
- src/schema/comments.ts
DD-469 #done
Since we recently introduced the comment preview, we also need to apply some changes in order to display the mentions as well.
> refactor: comment preview to include mentions

- infra/index.ts
- src/index.ts
Added a new websocket server based on env variable.
> feat: add new web socket server

- src/common/links.ts
Added exclude rule for apple developer blog.
> feat: allow developer apple website.

- ormconfig.js
- increased max connection number
- increased time until idle connection is closed
Signed-off-by: Viktor Poluksht <viktor@daily.dev>
> chore: modify pg connection parameters

- src/common/links.ts
Added excludes for google play and hackernews.
WT-240 #done
> chore: add exclude domains

- src/compatibility/utils.ts
- src/schema/users.ts
Catch empty whoami users and throw forbidden error
WT-299
> fix: throw forbidden error if user not found

- src/entity/User.ts
A fix for making certain fields un-required and allowing optional fields from the gateway users.
WT-370
> fix: for adding users from the Gateway call

- .infra/workers.ts
- __tests__/workers/__snapshots__/updateMailingList.ts.snap
- __tests__/workers/deleteUserFromMailingList.ts
- __tests__/workers/updateMailingList.ts
- src/common/mailing.ts
- src/common/users.ts
- src/workers/deleteUserFromMailingList.ts
- src/workers/updateMailingList.ts
Migrated the workers from the gateway.
> feat: user mailing list

- __tests__/whoami.ts
- garden.yml
- src/compatibility/utils.ts
- src/index.ts
- src/routes/whoami.ts
- src/schema/users.ts
* Image field can be empty in some cases
* Add logging in case of an unexpected error in the `injectGraphQL` function
* Add `reputation` field to the `whoami` call
> fix: minor issues for the new auth

- __tests__/whoami.ts
- src/graphorm/index.ts
- src/routes/whoami.ts
- src/schema/users.ts
> fix: add missing whoami fields

- .infra/workers.ts
- __tests__/whoami.ts
- __tests__/workers/cdc.ts
- src/common/pubsub.ts
- src/graphorm/index.ts
- src/routes/whoami.ts
- src/schema/users.ts
- src/workers/cdc.ts
- src/workers/index.ts
Migration of the workers from Gateway to API
> Feat migrate workers

- src/workers/cdc.ts
Move from userChange state to user for deletion topic.
> fix: move user deleted to right listener

- src/config.ts
- src/entity/User.ts
Provide fallback image from when the image is not set from a social provider
WT-462 #done
> fix: add fallback image for when social image not available

- __tests__/private.ts
- src/entity/User.ts
The info confirmed is a criterion and when the user registered with complete info, it should automatically be true.
> refactor: adding new user can have true infoConfirmed

- __tests__/__snapshots__/users.ts.snap
- __tests__/users.ts
Added test cases to test for user deletion unsets
WT-409 #done
> feat: add user deletion test cases

- src/common/links.ts
- src/common/slack.ts
- src/workers/commentCommentedSlackMessage.ts
- src/workers/postCommentedSlackMessage.ts
Added the exact comment links to the slack messages.
WT-488 #done
> fix: add slack comment link

- __tests__/__snapshots__/feeds.ts.snap
- __tests__/feeds.ts
- src/schema/feeds.ts
I changed the algorithm of the best discussion feed to surface more fresh content and to have more predictable behavior
> feat: make the best discussion feed more fresh

- src/entity/User.ts
Added timezone field to the new user endpoint
WT-590 #done
> fix: add timezone to new user command

- src/config.ts
Added new profile image
WT-608 #done
> fix: new profile image

- src/schema/users.ts
Fix the option to provide whether the image was already uploaded.
Relevant PR: https://github.com/dailydotdev/daily-gateway/pull/533
> fix: update user profile include image string

- __tests__/rss.ts
- src/routes/rss.ts
Currently when an invalid uuid is provided the server returns 500. This is fixed now.
> fix: handle invalid uuid for rss

- __tests__/__snapshots__/feeds.ts.snap
- __tests__/feeds.ts
- __tests__/fixture/source.ts
- src/common/feedGenerator.ts
Only removed banned posts from community source feed.
WT-769 #done
> fix: only hide banned post for community source

- __tests__/__snapshots__/notifications.ts.snap
- __tests__/fixture/notifications.ts
- __tests__/notifications.ts
- src/entity/NotificationAvatar.ts
- src/graphorm/index.ts
- src/migration/1669735640941-AvatarName.ts
- src/schema/notifications.ts
New `notifications` query returns the user's notifications sorted by time.
WT-775 #done
> feat: notifications query

- __tests__/notifications.ts
- src/schema/notifications.ts
New mutation to set all unread notifications of the user as read.
WT-776 #done
> feat: readNotifications mutation

- __tests__/users.ts
- src/schema/users.ts
We didn't actually check if the username and name are null, this introduces that check for both fields.
WT-807 #done 
Related:
https://github.com/dailydotdev/apps/pull/1416
> fix: ensure name and username are required

- .infra/Pulumi.prod.yaml
- .infra/workers.ts
- package-lock.json
- package.json
- src/common/mailing.ts
- src/onesignal.ts
- src/workers/index.ts
- src/workers/newNotificationMail.ts
- src/workers/newNotificationPush.ts
Send push notifications via OneSignal on a new notification. 
No tests to check that as it's more integration and manual testing we will have to apply here.
WT-782 #done
> feat: send push notifications

- .infra/workers.ts
- __tests__/helpers.ts
- __tests__/workers/newNotificationMail.ts
- __tests__/workers/usernameChangedUpdateNotifications.ts
- src/workers/index.ts
- src/workers/usernameChangedUpdateNotifications.ts
New worker that updates the `targetUrl` of `NotificationAvatar` when a username changes.
WT-790 #done
> feat: update notification avatars on username change

- __tests__/__snapshots__/sourceRequests.ts.snap
- __tests__/cron/tweetTrending.ts
- __tests__/feeds.ts
- __tests__/fixture/source.ts
- src/cron/tweetTrending.ts
- src/entity/Source.ts
- src/entity/SourceMember.ts
- src/entity/index.ts
- src/migration/1671547534880-Squad.ts
- src/schema/sourceRequests.ts
* Modify the existing Source table to accommodate the squad requirements.
* Add a new table to manage source members, also required for squad.
WT-819 #done
WT-822 #done
> feat: db schema for squads

- __tests__/__snapshots__/sources.ts.snap
- __tests__/sources.ts
- src/entity/SourceMember.ts
- src/graphorm/index.ts
- src/schema/sources.ts
Adjust Source type and introduce a new type SourceMember
WT-824 #done
> feat: graphql schema for squads

- __tests__/__snapshots__/sources.ts.snap
- __tests__/helpers.ts
- __tests__/sources.ts
- src/graphorm/index.ts
- src/schema/sources.ts
Introduce two new queries:
* `sourceMembers` - To get the members of a source by source id.
* `mySourceMemberships` - To get the logged-in user's source memberships.
WT-823 #done
WT-825 #done
WT-826 #done
> feat: squad queries

- __tests__/__snapshots__/compatibility.ts.snap
- __tests__/__snapshots__/feeds.ts.snap
- __tests__/compatibility.ts
- __tests__/feeds.ts
- src/schema/compatibility.ts
- src/schema/feeds.ts
> refactor: add authorization to source feed query

- __tests__/sources.ts
- src/common/cloudinary.ts
- src/entity/Source.ts
- src/entity/posts/utils.ts
- src/errors.ts
- src/migration/1671719516235-NullableSourceImage.ts
- src/schema/sources.ts
- src/schema/users.ts
New mutation to create new squad
WT-828 #done
> feat: createSquad mutation

- __tests__/__snapshots__/private.ts.snap
- __tests__/__snapshots__/sourceRequests.ts.snap
- __tests__/posts.ts
- __tests__/sources.ts
- src/entity/Source.ts
- src/entity/SourceMember.ts
- src/entity/posts/Post.ts
- src/entity/posts/utils.ts
- src/migration/1671725294007-TokenToString.ts
- src/schema/feeds.ts
- src/schema/posts.ts
- src/schema/sources.ts
Add two new mutations for squad:
* `sharePost` - Shares a post to source
* `joinSource` - Join the logged-in to the requested source given enough permissions
WT-829 #done
WT-830 #done
> feat: squad mutations

- __tests__/workers/newNotificationMail.ts
- src/notifications/generate.ts
- src/workers/newNotificationMail.ts
- src/workers/notifications/articleUpvoteMilestone.ts
- src/workers/notifications/commentUpvoteMilestone.ts
- src/workers/notifications/utils.ts
Change the upvote milestone notifications copy to a new format
> fix: update upvote milestones copy

- src/workers/notifications/utils.ts
- updates to the upvotes milestones for email notifications
- minor copy changes
> Update: upvote milestones

- __tests__/boot.ts
- src/Context.ts
- src/entity/Settings.ts
- src/routes/boot.ts
- src/routes/index.ts
- src/schema/alerts.ts
- src/schema/settings.ts
- src/schema/trace.ts
Instead of having multiple endpoints for the gateway to use.
This new endpoint is one stop shop for all the gateway needs.
This will save us the effort of adding new functionality to the gateway.
> refactor: new boot endpoint

- __tests__/boot.ts
- src/routes/boot.ts
> feat: add squads to boot

- __tests__/workers/newNotificationMail.ts
- __tests__/workers/notifications.ts
- src/entity/posts/utils.ts
- src/schema/users.ts
- src/workers/newNotificationMail.ts
- src/workers/notifications/commentReply.ts
* Don't add notification to the comment author when they reply to their own thread
* Properly format numbers in emails with commas
* Add missing parameter "total comments" to the analytics report
* Add verbose logging to spot the issue with one of our emails
> fix: notification hotfix

- src/workers/notifications/utils.ts
- minor copy update for consistency
> Update: Minor copy changes to upvotes notifications

- .infra/index.ts
- .infra/package-lock.json
- .infra/package.json
- Dockerfile
- Dockerfile.dev
- __tests__/health.ts
- src/index.ts
I found some references that recommend to use slim for better dns resolve and other issues.
Also used this PR to do graceful termination
> ci: secure docker + graceful termination

- src/schema/feeds.ts
Temporary set to 0 upvotes because of inventory issue
> fix: temporary upvote fix for inventory issue

- __tests__/sources.ts
- src/schema/sources.ts
Added delete squad option
WT-842
> feat: delete squad mutation

- __tests__/sources.ts
- src/schema/sources.ts
Added function to edit a squad,
also modified some function to be more generic so we can re-use them.
WT-946
> feat: edit squad function

- src/routes/boot.ts
Added case-insensitive order of squads.
WT-967 #done
> fix: case-insensitive ordering of squads

- __tests__/private.ts
- src/entity/User.ts
- src/migration/1674979079360-UserReferral.ts
- src/routes/private.ts
Migrated referral column to be a relationship to a user.
Also modified the `newUser` route to handle legacy input + new input.
And added 2 test cases for these scenario's
WT-988
> fix: refactor referral to relationship field

- __tests__/sourceRequests.ts
- src/entity/Source.ts
- src/migration/1675687066898-SourceCreatedAt.ts
Add createdAt column to source table.
WT-1029 #done
> feat: add createdAt to source table

- src/cron/exportToTinybird.ts
Signed-off-by: Viktor Poluksht <viktor@daily.dev>
> feat: include post type and source private fields in tinybird export

- __tests__/__snapshots__/feeds.ts.snap
- __tests__/feeds.ts
- __tests__/personalizedFeed.ts
- src/common/feedGenerator.ts
- src/personalizedFeed.ts
Fetch source memberships of the user and forward it to the feed service
> feat: provide squad ids query param to feed

- __tests__/__snapshots__/sources.ts.snap
- src/schema/sources.ts
> fix: order of the squad members

- __tests__/sources.ts
- src/schema/sources.ts
Removal of Squad member privilege. The access should be as follow:
Owner > Moderator > Member.
> feat: removing member from a squad privilege

- 1677643070022-UnknownSource.ts
- src/common/feedGenerator.ts
- src/cron/exportToTinybird.ts
- src/entity/Source.ts
- src/entity/posts/Post.ts
Introducing new source for the private links.
Note: merging is blocked until the correct image source link is provided by the design/product team.
> feat: unknown source

- .vscode/extensions.json
- .vscode/settings.json
Same as https://github.com/dailydotdev/apps/pull/1654
- Gives option to run specific tests selectively from VSCode
- After merging Jest runner extension will be recommended on the next VSCode launch
- I also added codelens config to make it work on __tests__ and `.spec` files as we use both
- After extension installation it gives you a nice overlay above test cases and describe sections to run tests selectively
> feat: add jest runner extension and config

- __tests__/workers/newNotificationMail.ts
- src/workers/newNotificationMail.ts
Fix the squad_reply template to work with threads
Added test case to validate.
WT-1138 #done
> fix: modify squad_reply template and added test case

- .infra/workers.ts
- __tests__/workers/cdc.ts
- src/common/pubsub.ts
- src/workers/cdc.ts
- src/workers/notifications/postAdded.ts
- src/workers/postChangelogAdded.ts
- src/workers/postScoutMatchedSlack.ts
* Publish messages to post-visible
* Stop sending messages to post-added
* Update subscribers to use post-visible, it also required to update the subscription name
WT-1143 #done
> refactor: use post-visible instead of post-added

- __tests__/workers/newNotificationMail.ts
- __tests__/workers/notifications.ts
- src/entity/Notification.ts
- src/notifications/generate.ts
- src/workers/newNotificationMail.ts
- src/workers/notifications/postAdded.ts
New notification for external links support to notify the user when the post is live
> feat: squad post live notification

- .infra/workers.ts
- __tests__/workers/postUpdated.ts
- src/entity/posts/utils.ts
- src/workers/cdc.ts
- src/workers/index.ts
- src/workers/postUpdated.ts
@idoshamun We just need to verify my JSON expected input matches what Denis is sending.
Introduces a new post-updated subscription, can update any part of the post
Can determine if post becomes visible
Updates shared post to become visible.
WT-1127 #done
Review suggestion:
Ensure test cases are solid.
> feat: introducing post updated worker

- __tests__/posts.ts
- src/entity/posts/Post.ts
- src/entity/posts/utils.ts
- src/workers/postUpdated.ts
> hotfix: small fixes for private links

- __tests__/__snapshots__/comments.ts.snap
- __tests__/comments.ts
- src/common/markdown.ts
Allow usage of hyphens when mentioning a user.
> refactor: mention criteria to include hyphens

- __tests__/__snapshots__/sources.ts.snap
- __tests__/boot.ts
- __tests__/sources.ts
- src/graphorm/index.ts
- src/roles.ts
- src/routes/boot.ts
- src/schema/sources.ts
Added new role for blocked users.
Decided to go negative to ensure lower prio then users.
Also updated test cases to validate they no longer return blocked users.
Tested locally on FE side as well.
WT-1215 #done
> feat: introduce blocked role and exclusion from squad members

- __tests__/__snapshots__/feeds.ts.snap
- __tests__/feeds.ts
- __tests__/personalizedFeed.ts
- src/common/feedGenerator.ts
- src/personalizedFeed.ts
- src/schema/common.ts
- src/schema/feeds.ts
- src/schema/posts.ts
Propagate to the client the metadata provided from the feed service for analytics purposes.
> feat: support feed service metadata

- .infra/workers.ts
- __tests__/notifications/index.ts
- __tests__/workers/cdc.ts
- __tests__/workers/notifications.ts
- src/common/pubsub.ts
- src/entity/Notification.ts
- src/notifications/builder.ts
- src/notifications/generate.ts
- src/notifications/icons.ts
- src/notifications/types.ts
- src/workers/cdc.ts
- src/workers/newNotificationMail.ts
- src/workers/notifications/index.ts
- src/workers/notifications/sourceMemberRoleChanged.ts
Added new notifications inline with the roles changes for Squad v4.
They only get send as notifications and not as emails.
WT-1190 #done 
WT-1195 #done
> feat: introduce new notifications for v4

- src/notifications/generate.ts
Missed including the source attachment per design.
> fix: add source attachment

- __tests__/posts.ts
- src/entity/posts/FreeformPost.ts
- src/entity/posts/Post.ts
- src/entity/posts/index.ts
- src/migration/1682497694917-FreeformPost.ts
- src/schema/posts.ts
Added support for freeform post type.
- Re-uses image field
- New fields content and contentHtml as described in PR
Mutation is a separate ticket.
WT-1285 #done
> fix: add freeform post type

- __tests__/__snapshots__/private.ts.snap
- __tests__/private.ts
- __tests__/workers/postUpdated.ts
- src/entity/posts/Post.ts
- src/entity/posts/utils.ts
- src/migration/1682690930599-ContentCuration.ts
- src/workers/postUpdated.ts
Added content curation metadata field and setters to both endpoints.
WT-1305 #done
> feat: add content curation metadata

- .infra/index.ts
- Dockerfile
- Dockerfile.dev
I'm trying to switch back to alpine image to see if it solves the gitpod issue
> build(docker): switch back to alpine

- __tests__/__snapshots__/feeds.ts.snap
- __tests__/feeds.ts
- __tests__/sources.ts
- __tests__/workers/postBannedRep.ts
- src/common/date.ts
- src/common/post.ts
- src/schema/feeds.ts
- src/schema/sources.ts
- src/workers/postBannedRep.ts
Add a welcome post when a user has created a Squad.
As we have been trying to move away from snapshots, I have also updated the tests to use an accurate expectation based on the description.
> feat: add welcome post when creating 

- bin/addWelcomePosts.ts
Retro command to add welcome post to all squads that don't have one yet.
Should be run once and can be deleted after.
WT-1320 #done
> fix: add welcome posts to existing squads

- src/cron/exportToTinybird.ts
Exclude welcome posts on tinybird query
> refactor: tinybird query to exlcude welcome post type

- src/common/post.ts
As per discussion, we wanted to update the markdown content for future welcome posts.
https://dailydotdev.slack.com/archives/C0506KU4RH9/p1684238420525799
> refactor: markdown content for welcome post

- __tests__/workers/completedUserActions.ts
- bin/completedUserActions.ts
I noticed our test runners are executing the `completedUserActions` file.
> chore: stop running unnecessary commands

- __tests__/posts.ts
- src/schema/posts.ts
As mentioned by Sab, content should be nullable.
Relevant discussion: https://dailydotdev.slack.com/archives/C050BHWG2MA/p1685371730738579?thread_ts=1685371697.452579&cid=C050BHWG2MA
> refactor: content property should be optional

- __tests__/posts.ts
- src/schema/posts.ts
Deleting of posts for Welcome and Freeform post should be allowed.
> fix: delete welcome and freeform post

- __tests__/workers/__snapshots__/postUpdated.ts.snap
- src/entity/posts/Post.ts
- src/migration/1685957377259-PostTitleHtml.ts
Note: The mutation for making the title commentary as HTML will be worked in a different PR.
> refactor: post title html property

- __tests__/notifications/index.ts
- __tests__/workers/newNotificationMail.ts
- src/common/links.ts
- src/notifications/generate.ts
Usage of query parameter to show the promotion modal.
> refactor: promotion notification query params

- __tests__/posts.ts
- src/entity/posts/utils.ts
- src/schema/comments.ts
- src/schema/posts.ts
Making the commentary optional on the sharePost as well as trimming the whitespace leading and trailing on the commentary before creating
> feat: Making commentary optional for sharePost

- src/entity/CommentReport.ts
- src/migration/1687956058691-CommentReport.ts
Add comment_report table and migration.
> feat: added comment report table and migration

- src/cron/exportToTinybird.ts
Include the source type on the data to export to tinybird.
WT-1485 #done
> refactor: export to tinybird the source type

- src/cron/exportToTinybird.ts
This reverts commit 137a77726ba69110ed68c1312ec4017685fb948f.
> Revert "refactor: export to tinybird the source type (#1324)"

- src/common/mailing.ts
- src/common/twitter.ts
- src/entity/posts/utils.ts
- src/notifications/builder.ts
- src/workers/postUpdated.ts
Had a quick look at our google cloud errors.
Mostly some edge cases of functions that call on null values.
(Main introductions where due to freeform post not having a sharedPost or commentary at first)
See separate commits per instance.
> fix: cloud errors

- __tests__/posts.ts
- src/common/post.ts
Sets the private attribute on freeform posts to match the private attribute of the squad source
WT-1628 #done
> fix: set private flag to match squad source on free form posts

- __tests__/search.ts
- src/integrations/magni.ts
- src/schema/search.ts
Fetch a single search session by session id from the session history list.
WT-1650 #done
> feat: single search session query

- src/schema/feeds.ts
Added a extra order by on API driven feeds to ensure more stability.
WT-1665 #done
> fix: add extra order by for API feeds

- src/auth.ts
> fix: remove legacy support

- .infra/Pulumi.prod.yaml
The value is based from [this message](https://dailydotdev.slack.com/archives/C05EM7ZFQMQ/p1692624401881979)
> fix: magni origin

- __tests__/feeds.ts
- src/integrations/feed/generators.ts
Set popular feed to use different configs then my feed
> refactor: update popular feed config

- __tests__/search.ts
- src/integrations/magni.ts
- src/schema/search.ts
Fix types for sources and awaiting the result.
> fix: source type fixes

- src/routes/index.ts
I added a route that returns the user's id. I need it for support cases mainly
> feat: utility route to get user's id

- src/entity/Source.ts
- src/migration/1672583245776-SourceImageDefault.ts
- src/migration/1693820674317-SourceImageDefault.ts
Frontend PR https://github.com/dailydotdev/apps/pull/2151
> feat: update squad image placeholder

- src/schema/posts.ts
Bringing back the query as it's now cached.
WT-1821 #done
> fix: bring back search rec logic

- src/entity/View.ts
- src/migration/1694443626041-ViewIndex.ts
Added indexes for view as recommended
> fix: indexes needed from research

- .github/CODEOWNERS
Added codeowners rules for generic and specific file for Viktor.
> fix: added codeowner rules

- .env
- .infra/Pulumi.prod.yaml
- __tests__/feeds.ts
- __tests__/integrations/feed.ts
- src/integrations/feed/clients.ts
- src/integrations/feed/configs.ts
- src/integrations/feed/generators.ts
- src/integrations/snotra/clients.ts
- src/integrations/snotra/index.ts
- src/integrations/snotra/types.ts
- src/integrations/utils.ts
Introduce new feed that sets the feed config based on the user's state
> feat: feed v15

- __tests__/redirector.ts
- src/cron/exportToTinybird.ts
- src/routes/redirector.ts
Product requested to add `ref=dailydev` to all our links
> feat: add ref query param to redirector

- __tests__/posts.ts
- src/common/post.ts
Up the title limit to 250 as requested by product.
> fix: up the title limit

- __tests__/workers/postUpdated.ts
- src/entity/posts/utils.ts
- src/workers/postUpdated.ts
- always create questions for new posts (if present)
- only update questions for existing posts if there aren't any already present
ref [WT-1866](https://dailydotdev.atlassian.net/browse/WT-1866)
[WT-1866]: https://dailydotdev.atlassian.net/browse/WT-1866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: process & store post questions on post worker processing

- __tests__/posts.ts
- src/schema/posts.ts
Earlier today we checked how many users see the search recommendations and it was relatively low. We guess that it's because upvote is less frequent than views.
We'll try to change that and see if it increases adoption.
> refactor: use views for search recs

- __tests__/__snapshots__/settings.ts.snap
- __tests__/boot.ts
- src/schema/settings.ts
Return default settings *(as logged in user) instead of adding query on boot.
> fix: add settings default

- __tests__/__snapshots__/feeds.ts.snap
- __tests__/feeds.ts
- src/integrations/feed/generators.ts
- src/integrations/feed/types.ts
> feat: feed v16

- .infra/index.ts
- .infra/workers.ts
- src/workers/deadLetterLog.ts
- src/workers/digestDeadLetterLog.ts
- src/workers/index.ts
- src/workers/personalizedDigestEmail.ts
- added dead letter topic in pulmi
- added configuration for digest subscription (by default subscriptions do not opt into dead letter topic)
- removed try catch from digest worker
> feat: add dead letter topic for digest subscription

- .infra/crons.ts
based on discussion: https://dailydotdev.slack.com/archives/C05NRH3U31C/p1697796480350509
> chore: disable invite gen cron until release day

- __tests__/settings.ts
- src/schema/settings.ts
self explanatory
ref https://dailydotdev.atlassian.net/browse/WT-1889
> fix: invalid validation on settings update mutation

- __tests__/private.ts
- src/entity/User.ts
- src/migration/1698144204806-UserCreatedAt.ts
Changed `createdAt` to be non nullable and default to now.
> fix: add default created at date for users

- __tests__/cron/generateSearchInvites.ts
- src/cron/generateSearchInvites.ts
as per slack thread: https://dailydotdev.slack.com/archives/C05NRH3U31C/p1698224770211269
> chore: update invite generation threshold from 7 to 1 day

- src/integrations/analytics.ts
- src/routes/webhooks.ts
Dave raised some issues and I'm trying to fix them. Hopefully it will indeed fix the issue
> refactor: some analytics adjustments for Dave

- src/routes/boot.ts
- src/tracking.ts
Hotfix for that: https://github.com/dailydotdev/daily-api/pull/1517
> fix: forgot to update boot analytics to uuid

- __tests__/alerts.ts
- src/entity/Alerts.ts
- src/schema/alerts.ts
Added the new referral mutation flow to support generic update that doesn't follow the regular flow.
(This is to ensure we don't accidentally wrongly set anything)
WT-1924 #done
> fix: add update referral mutation

- .infra/crons.ts
when merged and run, this will generate invite records for ~5k users: https://metabase.daily.dev/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo1LCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE2MiwiYWdncmVnYXRpb24iOltbImNvdW50Il1dLCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLDUzMzQsbnVsbF0sMV0sWyI9IixbImZpZWxkIiw0OTAyLG51bGxdLCJzZWFyY2giXV19LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InNjYWxhciIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==
> chore: enable search invite generator cron

- __tests__/cron/personalizedDigest.ts
- __tests__/workers/__snapshots__/personalizedDigestEmail.ts.snap
- __tests__/workers/personalizedDigestEmail.ts
- src/common/mailing.ts
- src/common/pubsub.ts
- src/cron/personalizedDigest.ts
- src/entity/UserPersonalizedDigest.ts
- src/migration/1699372102745-UserPersonalizedDigestLastSendDate.ts
- src/workers/personalizedDigestEmail.ts
Implementing batch id and deduplication logic from [DR](https://dailydotdev.atlassian.net/l/cp/afS2U1Lo)
Part with testing the load issue will be done in separate PRs.
> feat: digest de-duplication

- bin/insertMissingAlerts.ts
Refactor the insertion through streams to have better management in terms of load.
> refactor: insert alerts through stream

- __tests__/workers/cdc.ts
- src/common/pubsub.ts
- src/workers/cdc.ts
To support a new feed feature, the feed needs to map post id to yggdrasil id.
> feat: publish message when yggdrasil id is set

- __tests__/__snapshots__/feeds.ts.snap
- __tests__/feeds.ts
- src/schema/feeds.ts
Add the `group` property on `advancedSettings` type which is also part of the `FeedAdvancedSettings`.
WT-1985
> feat: group property on advanced settings

- src/integrations/feed/generators.ts
- src/integrations/feed/types.ts
Introduce feed v18 which treats squads like any other post
> feat: feed v18

- __tests__/fixture/notifications.ts
- __tests__/notifications.ts
- src/notifications/builder.ts
- src/schema/notifications.ts
Prerequisite for: https://github.com/dailydotdev/daily-api/pull/1572
Set `readAt` for notifications v2 in `readNotifications` mutation
> feat: read notifications v2

- src/schema/posts.ts
Add videoID so we can query it from the frontend
> fix: add video ID to graphQL load

- src/notifications/index.ts
The previous implementation was sensitive to sql injections and escaping issues. I use parameterized query now to fix it
> fix: support sql escaping

- __tests__/workers/postUpdated.ts
- src/entity/posts/YouTubePost.ts
The model was missing `publishedAt` field, so I added it.
Plus added a real life content test to see if there were any other fields missing.
> fix: add missing publishedAt to YouTubePost model

- .github/workflows/codeql-analysis.yml
Lots of warnings that these are deprecated, so updated them. Not sure if we look at any of their outputs.
> chore: update codeql workflow

- __tests__/feeds.ts
- src/integrations/feed/clients.ts
- src/schema/feeds.ts
Still WIP trying to figure out why there was a memory leak
> fix: use similar posts from feed service only for debugging purposes

- .circleci/config.yml
- __tests__/workers/postUpdated.ts
As a preparation for the upgrade to psql 15 in production, we update the circleci version to 15 too.
> chore: upgrade postgres to v15 in CircleCI pipelines

- __tests__/workers/newNotificationV2Mail.ts
- src/workers/newNotificationV2Mail.ts
Opss I did it again and broke our emails without noticing 🥵
> fix: personalization parameter for emails

- __tests__/feeds.ts
- src/common/feedGenerator.ts
- src/schema/feeds.ts
- src/schema/posts.ts
New query to get the user upvoted posts
> feat: user upvoted posts feed

- __tests__/__snapshots__/users.ts.snap
- __tests__/users.ts
- src/common/cloudinary.ts
- src/entity/User.ts
- src/migration/1703668189004-ProfileV2.ts
- src/routes/boot.ts
- src/schema/users.ts
* User's readme support including rendering the readme to markdown
* Cover image support including uploading to cloudinary
* Expose stats to everyone
> feat: support for profile v2

- __tests__/redirector.ts
- src/routes/redirects.ts
Added a public redirector endpoint where based on `userId` you can get redirected to user's profile image.
Usage as:
```
api.local.com/{userId}/profile-image
```
it will fallback to the placeholder image if user doesn't exist or has no image set in DB.
> feat: added a profile picture redirector

- src/integrations/feed/generators.ts
- src/integrations/feed/types.ts
Set default feed version to 18 and introduce feed v21. The non personalized config stays the same, it's not a bug :P
> feat: feed v21

- __tests__/__snapshots__/search.ts.snap
- __tests__/feeds.ts
- __tests__/search.ts
- src/schema/feeds.ts
- src/schema/search.ts
> refactor: move search queries from `feed` schema to `search` schema

- src/common/utils.ts
- src/migration/1704973835929-RenameInactiveUser.ts
<table>
<tr>
<td>Before
<td><img src="https://github.com/dailydotdev/daily-api/assets/1681525/b3be5fb6-f901-4f4e-8942-4387b32edf2d">
<tr>
<td>After
<td><img src="https://github.com/dailydotdev/daily-api/assets/1681525/45cb6e05-ce60-44ac-b19f-26a9b8b464b6">
</table>
> fix: give the ghost user a ghostly username 👻

- __tests__/feeds.ts
- __tests__/integrations/feed.ts
- src/entity/posts/Post.ts
- src/integrations/feed/configs.ts
- src/integrations/feed/generators.ts
- src/integrations/feed/types.ts
- src/schema/feeds.ts
Ole-Martin and I noticed that we don't send the user settings to feed service and this PR fixes it
> fix: send to feed the allowed post types

- __tests__/feeds.ts
- src/integrations/feed/generators.ts
- src/integrations/feed/types.ts
Bump the vector config to v22. Personalise stays the same for now
> feat: feed v22

- .infra/index.ts
- .infra/package-lock.json
- .infra/package.json
- src/routes/automations.ts
Let's make sure we don't get bankrupted
> fix: add rate limiting to automations

- src/entity/DevCard.ts
- src/migration/1707227186596-DevCard20Settings.ts
Adds new fields in the `dev_card` table:
- `theme`
- `isProfileCover`
- `showBorder`
MI-159 #done
> feat: store devcard 2.0 fields in DB

- __tests__/devcard.ts
- src/common/devcard.ts
- src/schema/devcards.ts
We need more user fields to properly render the new devcard
> feat: add user info into get devcard graphql query

- __tests__/devcard.ts
- src/schema/devcards.ts
Slack discussion here: https://dailydotdev.slack.com/archives/C06FDFQC6QZ/p1707397842394759
> fix: switch to fetching devcards by userId instead

- __tests__/devcard.ts
- src/schema/devcards.ts
Introduces the generateDevCardV2 mutation instead. 
Also revived the tests.
> fix: revert changes to generateDevCard mutation

- __tests__/devcard.ts
- src/schema/devcards.ts
Forgot to change this from OG URL 🤦
> fix: mutation generateDevCardV2 giving wrong URL

- src/routes/devcards.ts
To generate the right types we need to utilize the parameter sent.
> fix: missing usage of type parameter

- __tests__/sitemaps.ts
- src/entity/user/BotUser.ts
- src/migration/1707921624847-BotUser.ts
- src/routes/devcards.ts
- src/routes/sitemaps.ts
* Introduce bots table (will be filled with data using a retool app for now)
* Dynamically generate a robots.txt file based on the bots table and fresh users
> feat: dynamic robots.txt

- src/routes/devcards.ts
Embed the existing png image in svg
> feat: support svg devcards with an embedded png hack

- src/entity/Source.ts
- src/entity/SourceMember.ts
- src/entity/posts/Post.ts
- src/entity/user/User.ts
- src/migration/1707983477045-NewIndexes.ts
- src/routes/devcards.ts
With some of the latest additions we are actually not leveraging all indexes needed.
Thus added the missing ones.
> chore: add optimization indexes

- __tests__/sitemaps.ts
- package-lock.json
- src/routes/sitemaps.ts
Related to: https://github.com/dailydotdev/apps/pull/2640
> refactor: disable robots.txt

- src/common/feedGenerator.ts
- src/entity/posts/Post.ts
- src/migration/1708364779258-PostGin.ts
- src/schema/bookmarks.ts
- src/schema/common.ts
- src/schema/search.ts
- src/schema/users.ts
* Add index (can't believe we didn't have it before 😅)
* Change ordering to be based on the search rank and then created at to make it more predictable
* Change how we build the query to make only the last word partial search
Hopefully it will be better now
> refactor: search low hanging improvements

- __tests__/users.ts
- src/schema/users.ts
Update user information about acquisition channel.
MI-177 #done
> feat: acquisition mutation

- __tests__/users.ts
- __tests__/workers/cdc/primary.ts
- src/entity/user/User.ts
- src/migration/1709002546321-UserAcquisitionChannel.ts
- src/schema/users.ts
Additional column to track the acquisition channel.
MI-176 #done
> refactor: user entity to add acquisition channel column

- __tests__/urlShortener.ts
- src/schema/urlShortener.ts
Adds authentication requirement to the url shortener query. Also adds validation that the shortened URL is pointing to daily.dev
> feat: add @auth and better URL validation to url shortener

- src/integrations/feed/generators.ts
- src/integrations/feed/types.ts
> feat: feed v27

- src/common/feedGenerator.ts
- src/errors.ts
- src/schema/feeds.ts
We push a `refresh` key from frontend, needs to propagate to feed itself.
> fix: add force refresh arg

- __tests__/workers/postBannedRep.ts
- src/workers/postBannedRep.ts
[Thread](https://dailydotdev.slack.com/archives/C06E5FBGX41/p1710151932440609)
> feat: decrease reputation for community picks ban and all post types

- __tests__/boot.ts
- src/entity/MarketingCta.ts
- src/entity/user/UserMarketingCta.ts
- src/migration/1710235892939-MarketingCta.ts
- src/routes/boot.ts
> feat: add entities for marketing CTAs

- .infra/Pulumi.prod.yaml
- src/growthbook.ts
- src/integrations/meilisearch.ts
- src/schema/search.ts
Running meilisearch as a option beyond feature flags. (Would say just for internal testing for now)
Not fully optimized, but leveraging all things we already have in place 🙏
> fix: introducing feature flagged meilisearch

- src/entity/user/UserMarketingCta.ts
- src/migration/1710235892939-MarketingCta.ts
Didn't realise that typeorm had added a extra column for foreign key
> fix: the relation column name in UserMarketingCta

- __tests__/cron/__snapshots__/exportToTinybird.ts.snap
- __tests__/cron/exportToTinybird.ts
- src/cron/exportToTinybird.ts
https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/815398934/RFC-021+-+Language+Filter
> AS-150 add language field to tinybird export cron

- __tests__/sitemaps.ts
- src/routes/sitemaps.ts
New sitemap that lists all our tag pages
> feat: tags sitemap

- __tests__/cron/dailyDigest.ts
- src/cron/index.ts
> feat: register daily digest cron

- __tests__/users.ts
- src/common/users.ts
- src/notifications/builder.ts
- src/redis.ts
- src/routes/boot.ts
- src/schema/users.ts
> feat: mutation to mark user marketing CTA as read

- bin/seedUserStreaks.ts
- will let us interrupt the seed task and resume it without having to go through all users again
```bash
daily-api % ts-node bin/seedUserStreaks.ts                        
Queuing batch of users to process [ 'testuser', '404', 'VziREZeRywFMA6M7tSUyx' ]
inserting user streaks for:  [ 'testuser', '404', 'VziREZeRywFMA6M7tSUyx' ]
userPointer { id: 'VziREZeRywFMA6M7tSUyx', createdAt: '2024-03-13 09:28:01.31' }
no users to process
userPointer null
user streaks created for:  [ 'testuser', '404', 'VziREZeRywFMA6M7tSUyx' ]
insertion finished with a total of:  3
daily-api % ts-node bin/seedUserStreaks.ts
insertion finished with a total of:  0
```
ref MI-238
> feat: add redis caching on last user pointer

- __tests__/__snapshots__/comments.ts.snap
- __tests__/boot.ts
- __tests__/comments.ts
- __tests__/feeds.ts
- __tests__/posts.ts
- __tests__/workers/cdc/primary.ts
- __tests__/workers/notifications.ts
- src/common/index.ts
- src/common/vote.ts
- src/entity/Comment.ts
- src/entity/user/UserComment.ts
- src/entity/user/UserPost.ts
- src/graphorm/index.ts
- src/migration/1711384423929-CommentDownvotes.ts
- src/migration/1711384643544-UserComment.ts
- src/schema/comments.ts
- src/schema/feeds.ts
- src/schema/posts.ts
- src/workers/cdc/primary.ts
- src/workers/notifications/articleUpvoteMilestone.ts
AS-210
- adding new user_comment entity
- adding downvotes to comments
- refactor UserPostVote to UserVote
- migrations & test updates
Mutations and data move will be in separate PRs.
> feat: comment downvote entities

- __tests__/sitemaps.ts
- src/routes/sitemaps.ts
Changed sitemaps to use slug instead of URL
> fix: sitemaps to use slugs

- .circleci/config.yml
For now they look to be creating some issues. We will bring back later.
> revert: parallel tests

- .infra/workers.ts
- __tests__/workers/cdc/primary.ts
- __tests__/workers/commentDownvoteCanceledRep.ts
- __tests__/workers/commentDownvotedRep.ts
- src/common/pubsub.ts
- src/common/typedPubsub.ts
- src/entity/ReputationEvent.ts
- src/workers/cdc/primary.ts
- src/workers/commentDownvoteCanceledRep.ts
- src/workers/commentDownvotedRep.ts
- src/workers/index.ts
- reputation workers for comment downvote
> feat: add comment downvote reputation events

- .infra/package-lock.json
- .infra/package.json
This adds new labels to the cron jobs, to make it easier to query their metrics
> chore: update pulumi-common

- src/common/personalizedDigest.ts
Want to debug if some daily emails are not sent due to no posts being returned from service. See [here](https://dailydotdev.slack.com/archives/C06L6UB03U0/p1713181958648059?thread_ts=1713175325.594489&cid=C06L6UB03U0)
> feat: logging when no posts are returned from feed service

- __tests__/sources.ts
- src/schema/sources.ts
Optimized the recently added queries by leveraging the MV.
Also added the new query for similar sources.
> fix: optimized new queries by using MV and added similar source query

- src/workers/postBannedRep.ts
Apparently our flags object is not correctly deep parsed in the messageToJSON.
Decided to manually re-parse it for the worker.
(See example)
> fix: flags were not parsed as object

- .infra/Pulumi.prod.yaml
- .infra/workers.ts
- __tests__/helpers.ts
- __tests__/workers/cdc/primary.ts
- __tests__/workers/deleteUserFromMailingList.ts
- __tests__/workers/updateMailingList.ts
- __tests__/workers/userCreatedCio.ts
- __tests__/workers/userUpdatedCio.ts
- package-lock.json
- package.json
- src/cio.ts
- src/common/pubsub.ts
- src/common/typedPubsub.ts
- src/common/utils.ts
- src/workers/addToMailingList.ts
- src/workers/cdc/primary.ts
- src/workers/deleteUserFromMailingList.ts
- src/workers/index.ts
- src/workers/updateMailingList.ts
- src/workers/userCreatedCio.ts
- src/workers/userDeletedCio.ts
- src/workers/userUpdatedCio.ts
Update user profiles in customerio and delete them when needed.
Sidenote:  I refactored relevant workers to typed pubsub 💪
> feat: export data to customerio

- __tests__/feeds.ts
- src/schema/feeds.ts
Cleanup args assignment and added test case.
Could only come up with one good one that wasn't covered by the generic ones already.
> fix: cleanup similar feed

- src/entity/notifications/NotificationPreference.ts
- src/migration/1715072633296-NotificationPreferenceFk.ts
Deleted users who subscribed to source would break sending for other users due to FK constraint failing. See [here](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1715022146004289)
> feat: add notification preference fk

- __tests__/comments.ts
- __tests__/posts.ts
- src/Context.ts
- src/config.ts
- src/directive/rateLimit.ts
- src/graphql.ts
- src/redis.ts
- src/schema/comments.ts
- src/schema/posts.ts
Rate limit posts and comments.
> Comments - 20 comments per hour
> Posts - 10 per hour. 1 per 10 minutes in watercooler
AS-288
> feat: rate limit comments and posts

- __tests__/__snapshots__/sourceRequests.ts.snap
- bin/updateSource.ts
- src/entity/Source.ts
- src/schema/sources.ts
Add script to update source meta, also move `description` property to `Source` entity since it is now used by both Machine and Squad types (column existed already). See [here](https://dailydotdev.slack.com/archives/C06JCC41KSS/p1715257073668299?thread_ts=1715174261.029459&cid=C06JCC41KSS)
> feat: update source meta

- src/migration/1715679235259-AdvancedSettingsUpgrade.ts
Removed the old group all together
Introduces new groups
> feat: update all advanced settings to new types

- __tests__/__snapshots__/sourceRequests.ts.snap
- __tests__/feeds.ts
- src/common/feedGenerator.ts
- src/entity/Source.ts
- src/migration/1715682646033-SourceAdvancedSettingsRemoval.ts
Legacy system, cleanup basically.
AS-318 #done
> fix: remove source advanced settings

- __tests__/feeds.ts
- src/common/feed.ts
- src/common/index.ts
- src/errors.ts
- src/schema/feeds.ts
- src/types.ts
AS-301, add feed crud methods, merges in base branch for feed fields.
> feat: feed crud

- __tests__/feeds.ts
- src/integrations/feed/configs.ts
- src/schema/feeds.ts
- add option to pass filters to feed preview directly and pass it to popular feed used for custom feed
- added additional `FeedLocalConfigGenerator` that creates a config based on inline filters
> feat: add filters support for feed preview

- bin/syncSquadFlags.ts
Script to update all of Squads' stats.
After this, engineering should be able to do some internal testing.
> chore: script to update flags for squads

- __tests__/workers/userCreatedCio.ts
- __tests__/workers/userUpdatedCio.ts
- src/cio.ts
(Un)subscribe users from the relevant topic based on the `acceptedMarketing` property
> feat: sync accepted marketing to cio

- __tests__/feeds.ts
- src/common/feed.ts
- src/errors.ts
- src/schema/feeds.ts
For now validate alphanumeric characters and length so that we avoid people just filling it with garbage.
> feat: validate custom feed name

- src/routes/users.ts
Example value added `"referralLink": "https://dly.to/29lC7EzhPOa",`
> feat: add `referralLink` to me endpoint

- src/schema/feeds.ts
> fix: add missing version arg to gql definition

- __tests__/tags.ts
- src/schema/tags.ts
Needed the endpoints, we need to adjust the actual query based on MV we adding.
Added test as well to ensure they keep working.
> fix: add new tag endpoints for tag directory

- __tests__/tags.ts
- src/schema/tags.ts
https://app.circleci.com/pipelines/github/dailydotdev/daily-api/8134/workflows/4ee4f601-3243-4ad3-923a-de6d04833e56/jobs/32491/tests
> fix: flaky tags query by adding order

- bin/import.ts
I forgot to add refresh to seeds so that views actually have data after import.
> feat: refresh new mv in seeds

- .infra/crons.ts
[Thread](https://dailydotdev.slack.com/archives/C06S6HEUZB9/p1717410310384379)
> feat: refresh highlighted cron daily

- __tests__/workers/cdc/primary.ts
- src/workers/cdc/common.ts
Change object does not parse jsonb fields like ORM so they come in as JSON strings
> fix: handle json string value from change object

- __tests__/workers/notifications.ts
- src/workers/notifications/squadMemberJoined.ts
[Thread](https://dailydotdev.slack.com/archives/C014VT1J59V/p1717652642933269)
> fix: check if member exists before running joined logic

- src/onesignal.ts
> fix: remove `@TODO`

- src/routes/index.ts
- src/routes/redirects.ts
Temp send FF users to webapp as extension doesn't work
And add message on old auth system to inform people.
> chore: temp fixes for FF issues

- __tests__/keywords.ts
- src/entity/Keyword.ts
- src/graphorm/index.ts
- src/schema/keywords.ts
Ability to public expose roadmap flags
> fix: add roadmap flag to keywords

- __tests__/private.ts
- __tests__/users.ts
- src/entity/user/User.ts
- src/errors.ts
- src/schema/users.ts
Found several edge cases which may lead to duplicate emails
> fix: handle properly duplicate emails

- .infra/Pulumi.prod.yaml
- src/routes/webhooks/customerio.ts
This stub will be used to understand exactly the payload of these events. Locally I got rate limited by ngrok 🙈
> refactor: cio webhook stub to log properly the payload

- __tests__/workers/userUpdatedCio.ts
- src/cio.ts
- src/common/mailing.ts
- src/routes/webhooks/customerio.ts
- src/schema/users.ts
- src/workers/userUpdatedCio.ts
As part of our effort to solve to unsubscribe issues we need to sync updates to and from cio.
Note:  I wanted to introduce new hook to deal with the subscription thing to not have one big hook for everything but I didn't manage to get it work properly
> feat: sync subscriptions with cio and back

- seeds/MarketingCta.json
- src/entity/MarketingCta.ts
I forgot, but I think this is all that's needed on API side to add new CTA variant 😅 
AS-396
> feat: new CTA variant

- src/migration/1719227161827-AdvancedSettingsCopy.ts
Updated some copy for advanced_settings descriptions.
https://dailydotdev.slack.com/archives/C01473UNK9C/p1719215646375229?thread_ts=1718910959.633029&cid=C01473UNK9C
> chore: update copy for descriptions

- __tests__/webhooks.ts
- src/common/pubsub.ts
- src/common/typedPubsub.ts
- src/routes/webhooks/customerio.ts
[AS-399](https://dailydotdev.atlassian.net/browse/AS-399)
[AS-399]: https://dailydotdev.atlassian.net/browse/AS-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AS-399 promote user post webhook

- __tests__/publicSquadRequests.ts
- src/schema/sourceRequests.ts
request to increase the cooldown from this thread: https://dailydotdev.slack.com/archives/C069XNYMDGV/p1719496169767519
related PR https://github.com/dailydotdev/apps/pull/3276
> feat: change cooldown period to 30 days

- src/migration/1720104393427-AdvancedSettingsCopy.ts
New copy requested by product:
https://dailydotdev.slack.com/archives/C07A93GC63H/p1720081953149869?thread_ts=1719925744.424499&cid=C07A93GC63H
> chore: new copy

- src/auth.ts
- src/common/cloudinary.ts
- src/common/links.ts
- src/common/mailing.ts
- src/common/object.ts
- src/cookies.ts
- src/kratos.ts
- src/routes/rss.ts
- src/subscription.ts
- src/tracking.ts
daily.dev strict mode PR template
This one focuses on:
- common
- top level utils
> feat(strict-ts): apply to common utils

- __tests__/workers/__snapshots__/personalizedDigestEmail.ts.snap
@idoshamun @capJavert just wanted to make sure it was intended to update the id of the email. If so, I've updated the snapshots to reflect the new value.
> test: update snapshots

- README.md
> docs: update node version in readme

- src/schema/search.ts
Basically v2 was a title based only search
v3 is an experiment to try out full body search again
Keep in mind default now is v2.
AS-448
> feat: add support for v3 search

- src/common/personalizedDigest.ts
This reverts commit b93480a8f79916d8d0e1355a178430d72d5d3918.
> revert: log when posts are lower then max

- src/workers/cdc/primary.ts
> fix: add a temporary log on source CDC

- src/workers/cdc/primary.ts
Reverts dailydotdev/daily-api#2072
> Revert "fix: add a temporary log on source CDC"

- src/common/slack.ts
```
TypeError: Cannot read properties of undefined (reading 'toString')
```
:triggered:
AS-463
> fix: notify vordr slack

- .eslintrc.js
- __tests__/boot.ts
- __tests__/common/date.ts
- __tests__/cron/dailyDigest.ts
- __tests__/cron/hourlyNotifications.ts
- __tests__/private.ts
- __tests__/users.ts
- __tests__/whoami.ts
- __tests__/workers/personalizedDigestEmail.ts
- __tests__/workers/userCreatedPersonalizedDigestSendType.ts
- src/common/date.ts
- src/common/index.ts
- src/common/personalizedDigest.ts
- src/common/users.ts
- src/cron/dailyDigest.ts
- src/cron/hourlyNotifications.ts
- src/cron/personalizedDigest.ts
- src/cron/updateCurrentStreak.ts
- src/entity/user/User.ts
- src/entity/user/UserPersonalizedDigest.ts
- src/migration/1721746827472-User.ts
- src/migration/1722585215836-UserWeekStart.ts
- src/routes/boot.ts
- src/schema/users.ts
- src/types.ts
Related apps PR https://github.com/dailydotdev/apps/pull/3386
AS-437
> feat: add streak config

- src/entity/user/User.ts
- src/migration/1722942338711-UserEmailIndex.ts
https://dailydotdev.slack.com/archives/C03C3JZPRU4/p1722941471628759
> fix: replace email index

- __tests__/integrations.ts
- __tests__/users.ts
- src/common/userIntegration.ts
- src/schema/integrations.ts
- src/schema/users.ts
> feat: slack integration adjustments

- .infra/Pulumi.prod.yaml
https://dailydotdev.slack.com/archives/C07EDA5C5C2/p1723095133948389
> chore: update vordr word list

- __tests__/workers/postAddedSlackChannelSend.ts
- src/workers/postAddedSlackChannelSend.ts
everything works just forgot to update a string so top link did not contain params when post has author  :hidethepain
> fix(slack): missed updating other template string

- __tests__/search.ts
- src/schema/search.ts
Option to search for user suggestions (based on name and username)
> feat: add option to search user suggestions

- src/entity/user/User.ts
- src/migration/1723215750644-UserGinIndexes.ts
Checked with Viktor/EverSQL gin seems to be the way to go.
(These two alone move from 2s to 0.5ms so let's start with this.
> chore: optimize user search indexes

- __tests__/common/mailing.ts
- __tests__/users.ts
- __tests__/workers/userCreatedCio.ts
- __tests__/workers/userUpdatedCio.ts
- src/common/markdown.ts
- src/directive/user.ts
- src/entity/user/UserStats.ts
- src/schema/leaderboard.ts
- src/schema/search.ts
Accidentally merged previous branch to quickly.
So refactored all use-cases now in one go :)
> chore: update 404 hardcode to ghostuser

- __tests__/integrations.ts
- __tests__/workers/postAddedSlackChannelSend.ts
- src/common/mailing.ts
- src/schema/integrations.ts
- src/workers/postAddedSlackChannelSend.ts
Final copies, [see](https://dailydotdev.slack.com/archives/C07A9JNPENB/p1723472140884259)
> feat: adjust slack messages

- __tests__/__snapshots__/feeds.ts.snap
- __tests__/feeds.ts
This test keeps being flaky locally, so this should fix it hopefully.
Only did this specific one as it was the most flaky and annoyed me
> test: attempt fix a flaky test

- src/workers/postUpdated.ts
Realised I forgot to add the other flags on scout picks
> fix: set correct vordr flags on worker too

- __tests__/search.ts
- src/schema/search.ts
Added here for adoption purposes to not break FE implementation on old systems.
Also modified the test cases to reflect this limit.
> fix: add search users 3 char limit

- src/schema/search.ts
Temporary log for debugging search user queries
> chore: temporary search logging added

- src/workers/cdc/primary.ts
- cdc
- not the proudest part of the series, mostly used `!` to force unwrap of null values on TS side
This is mainly due to base type `ChangeMessage` being generic for all operations `c | r | u | d`, and we asses the `payload.op` manually
Eg. on `payload.op === u` `before` and `after` will always be not null but on `payload.op === d` `after` will be `null`
In the future implementation strict TS …
> feat(strict-ts): apply to cdc

- src/cio.ts
- src/common/datePageGenerator.ts
- src/common/handles.ts
- src/common/object.ts
- src/common/pagination.ts
- src/common/personalizedDigest.ts
- src/common/post.ts
- src/common/pubsub.ts
- src/common/search.ts
- src/common/slack.ts
- src/common/vordr.ts
- src/common/vote.ts
- src/cron/updateCurrentStreak.ts
- src/dataLoaderService.ts
- src/directive/rateLimit.ts
- src/entity/Alerts.ts
- src/types.ts
- common
- some other files connected to common imports
> feat(strict-ts): apply to common

- __tests__/workers/newNotificationV2Mail.ts
- src/common/twitter.ts
- src/workers/newNotificationV2Mail.ts
Enabling post_mention and squad_post_added notifications emails for freeform as well 🤯
> fix: enable new post emails for freeform posts

- src/cio.ts
Add temporary log to identify data from pubsub parsed
> chore: log for cio data

- src/entity/user/User.ts
- src/entity/user/UserStreak.ts
- src/migration/1724076968672-LeaderboardIndexes.ts
[Issue thread](https://dailydotdev.slack.com/archives/C03C3JZPRU4/p1724066167892659)
> feat: add leaderboard indexes

- src/workers/postAddedSlackChannelSend.ts
- no need to run anything if no integrations for post's source
- also locally in adhoc it just spools a bunch of messages when you seed
> feat: skip worker logic if no integrations found

- __tests__/__snapshots__/users.ts.snap
- __tests__/boot.ts
- __tests__/private.ts
- __tests__/users.ts
- __tests__/workers/cdc/primary.ts
- src/Context.ts
- src/common/users.ts
- src/entity/user/User.ts
- src/migration/1724168427191-UserLanguage.ts
- src/routes/boot.ts
- src/schema/users.ts
- src/types.ts
https://github.com/dailydotdev/heimdall/pull/98
> feat: add user language

- __tests__/users.ts
- src/common/users.ts
- src/data-source.ts
- src/entity/Company.ts
- src/entity/UserCompany.ts
- src/entity/user/User.ts
- src/graphorm/index.ts
- src/ids.ts
- src/migration/1724144430626-Company.ts
- src/schema/users.ts
Adds the new structure for company and user_company tables.
Also added all necessary mutations and query changes.
You should be able to review this part already :)
> feat: introduce company and usercompany structure

- __tests__/submissions.ts
- __tests__/workers/cdc/primary.ts
- src/config.ts
- src/errors.ts
- src/schema/submissions.ts
- src/workers/cdc/primary.ts
We do also support setting it in env, but noticed currently we don't and this seemed more verbose anyway. (not sure why we even added in env to begin with)
> chore: up the default

- __tests__/workers/cdc/primary.ts
- src/common/feedGenerator.ts
- src/common/slack.ts
- src/common/timezone.ts
- src/common/userIntegration.ts
- src/common/users.ts
- src/cron/updateCurrentStreak.ts
- src/entity/posts/ArticlePost.ts
- src/entity/posts/Post.ts
- src/entity/posts/utils.ts
- src/entity/user/User.ts
- src/errors.ts
- src/index.ts
- src/logger.ts
- src/onesignal.ts
- src/redis.ts
- src/routes/privateRpc.ts
- src/schema/comments.ts
- src/schema/sources.ts
- commons
- some adjustments to existing code that got broken over during process
> feat(strict-ts): apply to common 2

- .infra/crons.ts
- __tests__/cron/cleanZombieUserCompany.ts
- src/cron/cleanZombieUserCompany.ts
- src/cron/index.ts
- src/entity/UserCompany.ts
Auto-cleanups un-verified work emails that are older than one hour.
AS-538
> feat: create cron to cleanup unverified work emails

- src/common/personalizedDigest.ts
- src/integrations/feed/clients.ts
- sometimes we don't want to refetch 5 times by default like in digest
> feat: add option to specify retries for feed fetch

- __tests__/leaderboard.ts
- src/schema/leaderboard.ts
Add query for company leaderboard.
> feat: company leaderboard query

- __tests__/cron/personalizedDigest.ts
Simulation of "timezone" in the test was not right, I was just manually calculating offset and since weekly digest takes day into account it would no longer match.
Now I set the value in proper timezone globally inside cron during test so everything executes in the said timezone.
> fix: flaky digest test

- src/common/slack.ts
- src/workers/vordrPostPrevented.ts
Adds shared post title and source name to slack vordr post messages
> fix: minor tweaks to vordr slack messages

- .infra/Pulumi.prod.yaml
I see there's lots of span errors, need to investigate why it happens before I re-enable tracing
> fix: temporarily disable trace

- __tests__/submissions.ts
- src/config.ts
- src/schema/submissions.ts
Revert submission limit back to 3, but allow infinite submissions for team members.
> fix: submission limit

- .infra/Pulumi.adhoc.yaml
- src/data-source.ts
Accidentally changed the data source env value 🤦
> hotfix: this shouldn't have changed

- __tests__/workers/userCompanyApprovedCio.ts
- src/cio.ts
Sync domains to CIO as well.
Will run a manual fix for existing companies via CSV upload
> fix: sync domains to CIO as well

- __tests__/__snapshots__/sources.ts.snap
- __tests__/sources.ts
- __tests__/triggers/sourceMember.ts
- bin/syncMembersCount.ts
- src/common/utils.ts
- src/entity/Source.ts
- src/graphorm/index.ts
- src/migration/1725981526888-SourceFlagMembersIncrement.ts
- src/migration/1725981967186-SourceMembersCountDecrement.ts
- src/migration/1725988464760-SourceMembersIndex.ts
- src/schema/sources.ts
Order the sources by members count depending if the parameter sent says true.
> feat: sort sources by members count

- src/entity/common.ts
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1726462490868179
> fix: post report messages messed up

- .infra/Pulumi.prod.yaml
- src/telemetry/opentelemetry.ts
Looks like #2255 solved the issue
> chore: re-enable tracing

- __tests__/common/contentPreference.ts
- __tests__/contentPreference.ts
- __tests__/users.ts
- src/common/contentPreference.ts
- src/entity/contentPreference/ContentPreference.ts
- src/entity/contentPreference/ContentPreferenceUser.ts
- src/entity/contentPreference/types.ts
- src/entity/notifications/NotificationPreferenceUser.ts
- src/graphorm/index.ts
- src/graphql.ts
- src/migration/1726149087071-ContentPreference.ts
- src/notifications/common.ts
- src/notifications/generate.ts
- src/schema/contentPreference.ts
- src/schema/users.ts
- src/workers/newNotificationV2Mail.ts
> feat: content preference

- src/entity/contentPreference/ContentPreferenceUser.ts
- src/graphorm/index.ts
- src/schema/contentPreference.ts
- src/schema/users.ts
Some minor things we missed initially are added here now.
> fix: small fixes around graphORM

- __tests__/sources.ts
- src/schema/sources.ts
Reverts dailydotdev/daily-api#2182
> Revert "refactor: create/edit squad mutations"

- src/entity/notifications/index.ts
- src/notifications/common.ts
Needed to add the user entity to being able to mute it.
(Follows common practices)
AS-574
> fix: allow muting user posts

- .infra/application.properties
- .infra/index.ts
Update debezium so we can support proper exclude filter.
https://dailydotdev.slack.com/archives/C02E2C3C13R/p1725993356167719?thread_ts=1725973772.751369&cid=C02E2C3C13R
> chore: debezium update

- src/graphorm/graphorm.ts
- src/schema/users.ts
Testing graphorm implementation
> chore: test our read replica on graphORM

- __tests__/workers/vordrPostCommentPrevented.ts
- src/workers/vordrPostCommentPrevented.ts
- src/workers/vordrPostPrevented.ts
It became spammy lately, so this should help a little
> refactor: don't send slack notification for vordr users

- src/common/queryReadReplica.ts
- src/common/readReplica.ts
- src/routes/boot.ts
Add new read replica wrapper and apply to boot queries (where safe)
> chore: add read replica wrapper and use for boot

- .infra/crons.ts
- __tests__/cron/updateSourcePublicThreshold.ts
- __tests__/sources.ts
- src/cron/index.ts
- src/cron/updateSourcePublicThreshold.ts
- src/entity/Source.ts
- src/graphorm/index.ts
- src/migration/1727345240782-SourceFlagsIndexes.ts
- src/schema/sources.ts
- src/workers/cdc/primary.ts
- New property in the source.flags column.
- Updated query to accept a parameter to filter threshold.
- Cron job to update the flag every 10 minutes.
> feat: public threshold for source

- __tests__/workers/notifications.ts
- src/workers/notifications/postAddedUserNotification.ts
We also need to respect muted in NotificationPreference
> feat: respect muted for user post

- __tests__/notifications/notificationWorkerToWorker.ts
https://app.circleci.com/pipelines/github/dailydotdev/daily-api/9863/workflows/5ddbd083-427d-4a12-b759-06aa6135ce4f/jobs/39729
> fix: flaky worker notif attachments test

- bin/import.ts
- seeds/SourceCategory.json
Extracted from prod to have the same IDs throughout.
> chore: source category seeds

- __tests__/boot.ts
- src/routes/alerts.ts
- src/routes/automations.ts
- src/routes/boot.ts
- src/routes/devcards.ts
- src/routes/redirector.ts
- src/routes/redirects.ts
- src/routes/rss.ts
- src/routes/settings.ts
- src/routes/users.ts
- src/routes/webhooks.ts
- src/routes/webhooks/customerio.ts
- src/routes/whoami.ts
> feat(strict-ts): apply to routes

- __tests__/__snapshots__/feeds.ts.snap
- __tests__/feeds.ts
- __tests__/workers/__snapshots__/personalizedDigestEmail.ts.snap
- src/common/feedGenerator.ts
- src/common/personalizedDigest.ts
- src/integrations/feed/configs.ts
- src/integrations/feed/generators.ts
- src/integrations/feed/types.ts
- src/migration/1727848363303-SourceType.ts
- src/schema/feeds.ts
Added filtering option to set which sourceTypes to return.
Related Frontend: https://github.com/dailydotdev/apps/pull/3612
AS-625 #done
> feat: allow filtering of squads

- .infra/Pulumi.adhoc.yaml
- .infra/Pulumi.prod.yaml
- __tests__/feeds.ts
- __tests__/helpers.ts
- __tests__/submissions.ts
- src/Context.ts
- src/auth.ts
- src/common/users.ts
- src/routes/boot.ts
- src/schema/feeds.ts
- src/schema/submissions.ts
- src/telemetry/common.ts
- src/telemetry/opentelemetry.ts
- src/types.ts
Not ready for merge yet, but can be reviewed
> feat: send traces to opentelemetry-collector

- .infra/Pulumi.prod.yaml
- src/telemetry/opentelemetry.ts
🙈
#2303 didn't actually send it to the collector
> fix: actually send traces to opentelemetry-collector

- src/notifications/index.ts
[Incident](https://dailydotdev.slack.com/archives/C07LHS7RXA4/p1728296514536109)
> feat: chunk user notification when inserting

- __tests__/integrations/slack.ts
- __tests__/users.ts
- src/routes/integrations/slack.ts
- src/schema/users.ts
Added two parts here:
- Redirect with current integration id (it's only needed for new squad via this integration) (@capJavert happy to hear your thoughts)
- Singular integration query, we can use this from FE to query above returned element :)
> fix: integration changes

- src/schema/feeds.ts
Ensure we use the period filter on the comment feed.
AS-644 #done 
Related: https://github.com/dailydotdev/apps/pull/3652
> fix: add period filter to comment feed

- src/routes/boot.ts
I did notice that when cookie is not valid we treat user as anonymous because whoami (which revalidates) call happens in boot so `SEMATTRS_DAILY_APPS_USER_ID` does not get set to fetched value.
I add it to span in loggedInBoot so we can see it hopefully.
> feat: set user ids when resolving whoami

- __tests__/triggers/user.ts
- src/entity/posts/Post.ts
- src/migration/1727578711381-VordrUser.ts
- src/migration/1728978352110-VordrUser.ts
Just a quick attempt at a db trigger that also sets the correct vordr flags on posts when a user gets vordr'ed.
> feat: create new function that updates vordr flags on posts

- src/common/users.ts
- src/entity/View.ts
- src/migration/1728989030929-ViewRelationUserId.ts
Blocked due to heavy migration.
We should only merge once we spool up database a bit.
And run it on low time (Friday)
Should be reviewed in the meantime though.
> fix: optimize filtered view

- src/routes/boot.ts
Reverts dailydotdev/daily-api#2351
> revert: do not use rr in boot

- __tests__/contentPreference.ts
- __tests__/feeds.ts
- src/common/contentPreference.ts
- src/entity/contentPreference/ContentPreferenceSource.ts
- src/entity/contentPreference/types.ts
- src/migration/1728656542326-ContentPreferenceSource.ts
- src/schema/feeds.ts
> feat: add follow source support

- __tests__/alerts.ts
- __tests__/users.ts
- __tests__/whoami.ts
- src/entity/Alerts.ts
- src/graphorm/index.ts
- src/migration/1730379505031-AlertsTopReader.ts
- src/routes/alerts.ts
- src/schema/alerts.ts
- src/schema/users.ts
> feat: add `topReaderBadge` to alerts and create new query to fetch top reader badges

- __tests__/users.ts
- src/graphorm/index.ts
- src/schema/users.ts
> feat: add latest top reader badge relation to User in GraphORM

- __tests__/posts.ts
Addressing https://github.com/dailydotdev/daily/issues/1533
It turns out the character count update was already included in this PR: https://github.com/dailydotdev/daily-api/pull/2374. Only the test was missing.
> chore: update test name

- src/schema/feeds.ts
Closes https://github.com/dailydotdev/daily/issues/1539
> fix: show hidden posts in source feed

- __tests__/notifications/index.ts
- src/common/mailing.ts
- src/entity/notifications/NotificationAvatarV2.ts
- src/entity/notifications/NotificationV2.ts
- src/notifications/builder.ts
- src/notifications/common.ts
- src/notifications/generate.ts
- src/notifications/icons.ts
- src/notifications/types.ts
- src/workers/newNotificationV2Mail.ts
> feat: create notification for user top reader badges

- __tests__/private.ts
- src/entity/user/utils.ts
Most users get the feed as soon as they register while going through onboarding, but when quitting or going through other signup flows feed gets created only when they add some filters to feed.
This makes it not consistent and some of our FKs that rely on feed existing for users sometimes fail. 
There is about 40k user rows that don't have feed (I'll run a separate query to update those after this is merged).
> feat: create feed on user creation

- __tests__/posts.ts
- src/common/cloudinary.ts
- src/schema/posts.ts
- src/schema/sources.ts
- src/schema/users.ts
Override the image urls to use the image proxy. This implementation is partial just to try it out.
Some aspects are not covered here, for example markdown images, boot, etc.
> infra: use image proxy

- __tests__/__snapshots__/posts.ts.snap
- __tests__/boot.ts
- __tests__/workers/newNotificationV2Mail.ts
- src/common/cloudinary.ts
- src/common/post.ts
- src/entity/Source.ts
- src/routes/boot.ts
- src/schema/comments.ts
- src/schema/posts.ts
- src/schema/users.ts
Add the missing bits:
* boot
* comments
* post content
* uploaded images
* top reader
* fallback image
> infra: use image proxy p2

- src/migration/1731065998183-SourceDefaultImage.ts
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1731063931975029
> fix: change default squad image to point to new domain

- __tests__/posts.ts
- src/common/post.ts
- src/schema/posts.ts
Flow for creating a moderation entry for when user wants to edit their existing post
> feat: Create moderation for existing post edit

- __tests__/common/contentPreference.ts
- __tests__/contentPreference.ts
- src/common/contentPreference.ts
- src/entity/contentPreference/ContentPreferenceUser.ts
so constraint does not fail in #2436
> feat: add feedId to content preference user to prepare for pk

- __tests__/__snapshots__/sources.ts.snap
- __tests__/posts.ts
- src/common/post.ts
- src/entity/posts/utils.ts
- src/schema/comments.ts
- src/schema/posts.ts
- src/schema/sources.ts
- Admin/Mod/Author can delete SourcePostModeration
- Only Author can edit own _non-approved_ SourcePostModeration
> feat: added edit/delete endpoint and tests

- src/paddle.ts
- src/remoteConfig.ts
- src/routes/webhooks/paddle.ts
This should probably fix the deployment, stuck in dep cycle imoport
> fix: small type cycle issue

- __tests__/feeds.ts
- __tests__/integrations/feed.ts
- __tests__/rss.ts
- src/common/feedGenerator.ts
- src/graphorm/index.ts
- just an aggregate branch so I can deploy/revert at once
> feat: move feed to content_preference

- .infra/package-lock.json
- src/remoteConfig.ts
- src/routes/webhooks/paddle.ts
- src/schema/paddle.ts
Removed the need for function, just use vars inline
> fix: remove plantypes to use remoteconfig directly

- .infra/common.ts
- __tests__/workers/userUpdatedPlusSubscription.ts
- src/common/contentPreference.ts
- src/schema/sources.ts
- src/workers/index.ts
- src/workers/userUpdatedPlusSubscription.ts
Adds plus members to the squad automatically once they become subscriber.
AS-736 #done
> feat: add plus subscribers to squad

- src/common/cloudinary.ts
- src/common/personalizedDigest.ts
- src/onesignal.ts
- src/schema/notifications.ts
- src/workers/newNotificationV2Mail.ts
Migrate emails and push to image proxy
> refactor: some more image proxy optimizations

- .infra/Pulumi.prod.yaml
- .infra/index.ts
- src/common/pubsub.ts
* Update deployments resources
* Tweak max messages (experiment)
> infra: resource optimizations

- src/routes/localAds.ts
Can see the comment ads in local env now
> fix: add local ad endpoint for comment ad

- __tests__/__snapshots__/settings.ts.snap
- __tests__/boot.ts
- __tests__/settings.ts
- src/common/flags.ts
- src/entity/Settings.ts
- src/schema/settings.ts
- need new flag for sidebar so frontend can send and not break
> feat: add sidebar bookmark flag

- src/schema/feeds.ts
Add supported types for following feed
> fix: support types

- __tests__/posts.ts
- __tests__/workers/cdc/primary.ts
- src/common/post.ts
- src/common/vordr.ts
- src/entity/Comment.ts
- src/entity/SourcePostModeration.ts
- src/migration/1733244072344-SourcePostModerationFlagsVordr.ts
- src/schema/posts.ts
- src/workers/cdc/primary.ts
- Check vordr when user submits a post for moderation.
- Query for pulling pending requests will filter vordred request.
- Of course only for moderators, for regular users, you will still see your submission 😈 
- Fixed some copy-pasta issue with the index naming.
> feat: vordr source post moderation submissions

- __tests__/bookmarks.ts
- src/schema/bookmarks.ts
See [thread](https://dailydotdev.slack.com/archives/C02E2C3C13R/p1733749081634089)
> fix: bookmark response backward compatibility

- src/entity/ReputationEvent.ts
- src/workers/commentDownvotedRep.ts
- src/workers/commentUpvotedRep.ts
- src/workers/postDownvotedRep.ts
- src/workers/postUpvotedRep.ts
Encapsulate reputation granting criteria to a function and apply it where necessary
> fix: ignore vordr reputation

- __tests__/workers/postUpvotedRep.ts
- docker-compose.yml
- src/entity/ReputationEvent.ts
- src/workers/commentDownvotedRep.ts
- src/workers/commentUpvotedRep.ts
- src/workers/postDownvotedRep.ts
- src/workers/postUpvotedRep.ts
Also remove the version property in docker compose as it's legacy
> feat: limit reputation events per user per day

- __tests__/posts.ts
- __tests__/workers/postUpdated.ts
- src/entity/posts/Post.ts
- src/graphorm/index.ts
- src/schema/posts.ts
- src/types.ts
- src/workers/postUpdated.ts
https://github.com/dailydotdev/apps/pull/3947
AS-822
> feat: add admin option to manually protect posts with clickbait shield

- __tests__/posts.ts
Adds missing tests for smart title
AS-811
> test: add missing tests for clickbait shield titles

- __tests__/boot.ts
- src/entity/user/User.ts
- src/migration/1733987625520-UserDefaultFeed.ts
- src/routes/boot.ts
- src/schema/users.ts
Add default feed for users and expose id in boot.
Made it relationship to have cascasing, not sure we need anything besides ID?
> feat: add default feed for users

- __tests__/bookmarks.ts
- __tests__/feeds.ts
- __tests__/helpers.ts
- __tests__/keywords.ts
- __tests__/leaderboard.ts
- __tests__/posts.ts
- __tests__/publicSquadRequests.ts
- __tests__/rss.ts
- __tests__/sourceRequests.ts
- __tests__/sources.ts
- __tests__/submissions.ts
- __tests__/workers/completedUserActions.ts
- src/Context.ts
- src/auth.ts
- src/common/users.ts
- src/directive/auth.ts
- src/types.ts
Since we had a lot of legacy use of premium and now have plus I thought it would be neater to remove this.
> chore: remove premium notation

- __tests__/feeds.ts
- src/common/feed.ts
- src/entity/Feed.ts
- src/errors.ts
- src/schema/feeds.ts
> feat: add new flags to Feed entity

- src/schema/contentPreference.ts
Content preference should expose sources and users optionally from each other.
> chore: expose more types of content preference

- __tests__/search.ts
- src/common/search.ts
- src/schema/search.ts
We need to add feed id to search as well.
(excluded specific tests)
> fix: search also needs a feed id

- .infra/application.properties
- .infra/package-lock.json
- .infra/package.json
Now ready to v3.0.
Already applied
> chore: migrate debezium 3 of 3

- src/entity/Feed.ts
- src/schema/contentPreference.ts
Missing type of feed ordering
AS-877
> fix: order by date

- __tests__/feeds.ts
Accidentally pushed to main already, but forgot the tests.
> hotfix test where missing

- .infra/index.ts
- __tests__/contentPreference.ts
- __tests__/feeds.ts
- src/schema/contentPreference.ts
- src/schema/feeds.ts
Since we now allow enrolled users to try out custom feeds settings we need to allow storing it.
> fix: auth level

- __tests__/prompts.ts
- src/graphorm/index.ts
- src/graphql.ts
- src/schema/prompts.ts
List all prompts ordered by order
> feat: query to list all prompts

- src/entity/Settings.ts
- src/schema/common.ts
- src/schema/settings.ts
Setting additions for custom prompt
> fix: setting additions

- src/migration/1735645895838-Prompt.ts
> fix: id of prompts

- src/schema/prompts.ts
Need to access the prompt value from front-end
> fix: expose prompt in prompts query

- .circleci/config.yml
It expects object and not array, fixing as it might get broken in the future
> fix: circleci env type

- .infra/index.ts
Adds the `bigquery.jobs.create` role to API
> fix: add bigquery permission

- __tests__/posts.ts
- src/Context.ts
- src/common/post.ts
- src/graphorm/index.ts
Return original post title of content language is disabled (header is missing)
AS-930
> fix: return original post title of content language is disabled

- __tests__/workers/cdc/primary.ts
- src/entity/posts/FreeformPost.ts
- src/workers/cdc/primary.ts
This reverts commit 4d5cd745cbf4c9453e80ca586abbabd905113902.
> Revert "AS-613 disable freeform processing threshold (#2587)"

- __tests__/comments.ts
- __tests__/setup.ts
Just adding a test case to make sure it works
> test: add test case for vordr word list with spaces

- .infra/common.ts
- __tests__/setup.ts
- __tests__/workers/postTranslated.ts
- src/common/typedPubsub.ts
- src/entity/posts/Post.ts
- src/remoteConfig.ts
- src/workers/index.ts
- src/workers/postTranslated.ts
Adds new worker that listens for post translations from Kvasir.
AS-923
> feat: add translation worker

- src/types.ts
With the changes of creating a feed more easily on frontend I increased a limit a bit. Nobody hit it yet but just as a precaution.
> feat: max feeds per user increase

- __tests__/posts.ts
- src/entity/posts/Post.ts
- src/schema/posts.ts
> feat: add `smartTitle` as a translatable field

- __tests__/settings.ts
- package-lock.json
- package.json
- src/schema/posts.ts
- src/schema/settings.ts
Ensure only booleans can be send as flags.
We already had the JSONObject scalar on it.
> fix: prompt flags can only be object and booleans

- src/entity/Settings.ts
- src/schema/settings.ts
Just for safekeeping so we know it exists.
Didn't put it into the prompts one as it needs to support string.
> fix: add last prompt flag

- __tests__/private.ts
- src/routes/private.ts
New endpoint for retrieving actions for users.
Only for internal use.
https://dailydotdev.slack.com/archives/C01473UNK9C/p1739196537063589
> fix: add actions endpoint

- __tests__/search.ts
- src/schema/search.ts
Bigger initial request to deal with high level of private posts.
Also added criteria that non public threshold post shouldn't show here.
> fix: post suggestion missing data

- .infra/common.ts
- __tests__/workers/transactionBalanceLog.ts
- package.json
- pnpm-lock.yaml
- src/background.ts
- src/common/typedPubsub.ts
- src/workers/index.ts
- src/workers/transactionBalanceLog.ts
- src/workers/worker.ts
- just logging for now so I can inspect payloads as I work on other things
- it will be replaced with proper logic in separate PR
> feat: transaction log worker

- __tests__/paddle.ts
- src/schema/paddle.ts
See description here:
https://github.com/dailydotdev/apps/pull/4215
> fix: request name not description

- package.json
- pnpm-lock.yaml
> chore: schema update

- .env
- .infra/Pulumi.prod.yaml
- __tests__/common/njord.ts
- __tests__/njord.ts
- __tests__/setup.ts
- src/Context.ts
- src/common/njord.ts
- src/entity/Product.ts
- src/entity/user/UserTransaction.ts
- src/graphql.ts
- src/migration/1740414691929-UserTransaction.ts
- src/remoteConfig.ts
- src/schema/njord.ts
- src/types.ts
Lot of TODOs but trying to get it out of the door for initial stuff, implementation will change with Njord side as well.
> feat: award user

- .infra/Pulumi.prod.yaml
https://github.com/dailydotdev/njord/pull/28
> chore: update njord host

- src/schema/paddle.ts
The API endpoint is showing all existing prices, rather than taking into account A/B test prices. This PR should fix that issue
> fix: list correct prices from the api

- __tests__/comments.ts
- src/schema/comments.ts
Since we rate limit by reputation, I increased the generic rate limit to support power users.
Closes dailydotdev/daily#1777
> refactor: increase comment rate limit

- __tests__/njord.ts
- src/common/njord.ts
- src/graphorm/index.ts
- src/schema/njord.ts
I will add some products to the prod DB manually and also update real one once all assets are ready from design.
Products are returned sorted by value ASC.
> feat: products query

- __tests__/__snapshots__/comments.ts.snap
- __tests__/comments.ts
- __tests__/njord.ts
- __tests__/triggers/comment.ts
- src/common/njord.ts
- src/entity/Comment.ts
- src/entity/user/UserComment.ts
- src/graphorm/index.ts
- src/migration/1741621921297-AwardComment.ts
- src/migration/1741624559787-AwardCommentTriggers.ts
- src/schema/comments.ts
- src/schema/njord.ts
- add support for comment award
- add columns and triggers same as for posts
- expose new fields on comment entities
> feat: award comment

- __tests__/boot.ts
- __tests__/comments.ts
- __tests__/common/njord.ts
- __tests__/helpers.ts
- __tests__/njord.ts
- __tests__/posts.ts
- __tests__/triggers/comment.ts
- __tests__/triggers/post.ts
- __tests__/workers/transactionBalanceLog.ts
- package.json
- pnpm-lock.yaml
- src/common/njord.ts
- src/common/typedPubsub.ts
- src/entity/user/UserTransaction.ts
- src/workers/transactionBalanceLog.ts
- transfer payloads
- balance log format
- minor adjustments to enums and types
> feat: njord schema update and compatibility

- src/routes/webhooks/apple.ts
This is the endpoint that Apple testing will use, so we need to ensure it works.
A quick and dirty fix by just re-using the same logic, ideally it'd have some extra safety features like limiting by users, but I'll improve it later, now I just need to for submission to pass.
> fix: expose sandbox endpoint

- src/common/utils.ts
- src/remoteConfig.ts
- src/routes/webhooks/apple.ts
- src/routes/webhooks/paddle.ts
- Adds a check to prevent unauthorised users getting subscription via Sandbox endpoint (TestFlight app)
- Log analytics events
- Send new subscription events to Slack
> feat: add analytics logging and slack notifications

- __tests__/comments.ts
- __tests__/common/njord.ts
- __tests__/posts.ts
- __tests__/triggers/comment.ts
- __tests__/triggers/post.ts
- src/common/njord.ts
- src/common/paddle.ts
- src/common/utils.ts
- src/dataLoaderService.ts
- src/entity/Product.ts
- src/entity/user/UserTransaction.ts
- src/graphorm/index.ts
- src/migration/1741868793950-UserTransactionProcessor.ts
- src/remoteConfig.ts
- src/routes/boot.ts
- src/routes/webhooks/paddle.ts
- src/schema/njord.ts
- src/schema/paddle.ts
[RFC section](https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/1435172886/RFC-108+-+Credits+backend#Paddle)
> feat: purchase cores

- __tests__/njord.ts
- src/schema/njord.ts
> feat: transaction list and summary queries

- __tests__/paddle.ts
- src/config.ts
- src/schema/paddle.ts
- paddle is rate limiting us so for now cache in redis
> feat: cache cores price preview

- __tests__/common/njord.ts
- __tests__/helpers.ts
- __tests__/njord.ts
- src/common/njord.ts
- src/common/utils.ts
- src/errors.ts
- src/routes/boot.ts
- src/routes/webhooks/paddle.ts
- handle njord errors and record the status in `UserTransaction` row
- revert any entities for awards when njord fails
- return balance of user on transfer errors
- handle error messages
TODO:
> feat: transaction error handling

- __tests__/njord.ts
- src/common/njord.ts
Added comment when note is provided on awarding post
> fix: add comment for note award on post

- __tests__/paddle.ts
- src/remoteConfig.ts
- src/routes/webhooks/paddle.ts
- Removed the pricing ids.
- Used the billing cycle from the event data.
- Refactored the analytics function to use a function to get the `extra` values. Was a bit hard to follow which one was going to have value and which ones would not.
> refactor: pricing ids removal from remote config

- src/schema/notifications.ts
- src/schema/posts.ts
Couldn't sleep, so tried to take a stab at fixing the ws memory leak, which might be caused by the iterator never properly closing
> fix: attempt fixing ws memory leak

- .infra/index.ts
Doesn't need to be stored as a secret to be re-created each deployment, so can put as env instead.
> fix: move `SERVICE_VERSION` out of secrets

- __tests__/helpers.ts
- src/common/njord.ts
- src/routes/webhooks/paddle.ts
It was added in https://github.com/dailydotdev/daily-api/pull/2719 this just assigns real value from njord
> feat: balance on error

- __tests__/comments.ts
- __tests__/common/njord.ts
- __tests__/njord.ts
- __tests__/posts.ts
- __tests__/triggers/comment.ts
- __tests__/triggers/post.ts
- src/common/njord.ts
- src/entity/user/UserTransaction.ts
- src/migration/1743776947033-UserTransactionValueFee.ts
- src/routes/webhooks/paddle.ts
- src/schema/njord.ts
On transfer save value after fees to db so we can show receiver balance/summary correctly
> feat: save transaction fees value after transfer

- src/entity/Comment.ts
- src/entity/Product.ts
- src/entity/user/UserTransaction.ts
- src/migration/1744037437681-TransactionIndexes.ts
- src/schema/njord.ts
Mostly added per column indexes, and single bigger index for summaries. We can look into optimization when a bit more data is in the table.
> feat: transaction indexes

- src/routes/webhooks/paddle.ts
On multiple updates to transaction there can be edge case on writes so in that case also upsert over `flags->providerId`.
> fix: transaction upsert on multiple updates

- __tests__/common/mailing.ts
- __tests__/cron/validateActiveUsers.ts
- __tests__/workers/cdc/primary.ts
- __tests__/workers/newNotificationV2Mail.ts
- __tests__/workers/newNotificationV2Push.ts
- __tests__/workers/userUpdatedCio.ts
- src/cio.ts
- src/common/mailing.ts
- src/graphorm/index.ts
- src/schema/users.ts
- src/workers/newNotificationV2Mail.ts
- src/workers/newNotificationV2Push.ts
Forgot to add this logic in previous PR 🙈
> fix: handle unsubscribes from award email and push notifications

- src/notifications/generate.ts
- src/workers/newNotificationV2Mail.ts
Update notification copy
AS-1086
> fix: return different copy for free award notifications

- src/remoteConfig.ts
- src/routes/boot.ts
- not needed anymore since we are fully deployed now
> chore: remove enable balance config

- __tests__/fixture/paddle/transaction.ts
- __tests__/routes/webhooks/paddle.ts
- __tests__/setup.ts
> feat: purchase cores tests

- __tests__/routes/webhooks/paddle.ts
- src/routes/webhooks/paddle.ts
- make sure error status is updated correctly after repeated errors
> fix: transaction always update state after error

- __tests__/njord.ts
- src/schema/njord.ts
Show received cores in transaction summary.
> fix: transaction summary to show received cores

- __tests__/routes/webhooks/paddle.ts
- __tests__/setup.ts
- src/common/paddle/index.ts
- src/remoteConfig.ts
- src/routes/webhooks/paddle.ts
Since we are using test discounts sometimes for e2e purchase testing we don't want to actually log those in njord balance sheet.
> feat: skip njord if test discount

- src/routes/webhooks/paddle.ts
Log full payload on specific errors for better debugging. [Example](https://console.cloud.google.com/monitoring/alerting/alerts/0.nrwhe4wu89hh?channelType=slack&project=devkit-prod)
> feat: paddle additional logging

- bin/assignCores.ts
- bin/checkNjordBalance.ts
- bin/topUpNjordBalance.ts
[Docs for scripts](https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/1555824648/Cores#Cores-scripts)
> feat: cores scripts

- src/index.ts
Breaking change in cors package https://github.com/fastify/fastify-cors/pull/359
> fix: default cors methods

- seeds/Product.json
Was saved as string to flags in jsonb column, with this change it actually saves it as json.
> fix: product seeds flags

- README.md
- Removed grammatical errors and incorporated slight improvements.
- Improved the spacing across the list items and some other sections.
> 📝 Trivial Update: README.md

- __tests__/comments.ts
- __tests__/posts.ts
- src/graphorm/index.ts
- src/schema/comments.ts
- src/schema/njord.ts
- src/schema/posts.ts
- list awards
- get awards total (separate query but on frontend its queries as a single one)
Frontend: https://github.com/dailydotdev/apps/pull/4483
> feat: list awards

- .infra/crons.ts
- __tests__/cron/cleanStaleUserTransactions.ts
- src/cron/cleanStaleUserTransactions.ts
- src/cron/index.ts
- src/migration/1747300279523-StaleUserTransactionIndex.ts
> feat: clean stale transactions

- __tests__/paddle.ts
Fix:
- The error message thrown.
- Rounding down value.
- Removed unused tests.
> test: error thrown and value update

- __tests__/__snapshots__/comments.ts.snap
- __tests__/comments.ts
- __tests__/common/mailing.ts
- __tests__/cron/cleanZombieUsers.ts
- __tests__/private.ts
- __tests__/users.ts
Merged too soon and forgot tests https://github.com/dailydotdev/daily-api/pull/2830
> fix: system user test cases

- __tests__/organizations.ts
- src/common/paddle/organization/processing.ts
- src/entity/Organization.ts
- src/entity/contentPreference/ContentPreferenceOrganization.ts
- src/graphorm/index.ts
- src/roles.ts
- src/schema/organizations.ts
Adds query to fetch single organization
> feat: view organization

- .infra/common.ts
- __tests__/organizations.ts
- src/common/mailing.ts
- src/common/pubsub.ts
- src/common/typedPubsub.ts
- src/common/users.ts
- src/config.ts
- src/entity/notifications/NotificationAvatarV2.ts
- src/entity/notifications/NotificationV2.ts
- src/graphorm/index.ts
- src/notifications/builder.ts
- src/notifications/common.ts
- src/notifications/generate.ts
- src/notifications/types.ts
- src/schema/organizations.ts
- src/schema/users.ts
- src/workers/index.ts
- src/workers/newNotificationV2Mail.ts
- src/workers/notifications/index.ts
- src/workers/organization/organizationUserJoined.ts
- src/workers/organization/organizationUserLeft.ts
- src/workers/organization/organizationUserRemoved.ts
Adds a mutation to be able to delete an organization when it passes all the checks
- Not active
- No members with assigned seats
- Owner tries to delete
> feat: mutation to delete organization

- seeds/ExperimentVariant.json
Quick fix to the seed because recent changes to tables makes the db seed function not work due to constraints
> fix: set type on experimentVariant seed

- src/common/paddle/index.ts
- src/common/paddle/organization/eventHandler.ts
- src/common/paddle/slack.ts
- src/common/plus/subscription.ts
> fix: analytics events on organization paddle events

- .github/workflows/comment-jira-ticket.yml
Miss this from the apps repo 🙈
> feat: GitHub workflow for automagically comment Jira ticket

- src/graphorm/index.ts
Continuation of #2782
For some reason the exists causes the "read" subquery to use the `IDX_9cb4aa5be0760354054764eefb` index (just userId) instead of the correct index `IDX_e74e00c9de47272d1a9ea327ab` which is postId and userId. So for users who have read a lot of posts, it would actually load all views (which in my case is 10k views).
<table>
<tr>
<td>
<td>Before (cold)
<td>Before (hot)
<td>After (cold)
<td>After (hot)
<td>Change
</tr>
<tr>
<td>Cost
<td>0.43..10730.96
<td>0.43..10730.96
<td>0.43..10730.96
<td>0.43..10730.98
<td>No real change here, more in #2782 actually
</tr>
<tr>
<td>Planning Time
<td>4.316 ms
<td>4.502 ms
<td>7.583 ms
<td>4.634 ms
<td>After cold is slight bump, bot still low
</tr>
<tr>
<td>Execution Time
<td>5195.495 ms
<td>22.332 ms
<td>10.105 ms
<td>5.954 ms …
> refactor: wrap in `case` instead of `exists`

- __tests__/posts.ts
- src/common/post.ts
- src/cron/updateSourcePublicThreshold.ts
- src/schema/posts.ts
- src/schema/sources.ts
Allow users to share links and post freeform content to their own user source. Added a compatibility check so ensure the user source is created if it does not already exist.
Also don't think we need to create it when user is created, as many users might never post to their own source, so we can limit the amount of "empty" sources.
AS-1157
> feat: post to user source

- __tests__/workers/postBoostCanceledCores.ts
- src/common/typedPubsub.ts
- src/workers/postBoostCanceledCores.ts
Float, when passed around services, becomes a string.
MI-888
> fix: worker that receives for refund is float which becomes string

- src/common/feedGenerator.ts
Apply the filter to remove non public threshold user source from feed
> fix: remove non public threshold user source

- __tests__/cron/updateSourcePublicThreshold.ts
- src/cron/updateSourcePublicThreshold.ts
Re-used the existing cron job, just adjusted the SQL so that it accepts both squad and user source, then wrapped some squad specific requirements
AS-1165
> fix: update `updateSourcePublicThreshold` cron to set public threshold on user source

- __tests__/__snapshots__/feeds.ts.snap
- __tests__/feeds.ts
- src/schema/posts.ts
Reference to one of the jobs where it failed https://app.circleci.com/pipelines/github/dailydotdev/daily-api/13180/workflows/f41e51a0-a660-43b3-ae66-682b226e9d40/jobs/53233/tests
> fix: some flaky tests

- __tests__/common/standardizeURL.ts
> fix: remove console.log from test

- src/integrations/skadi/api/clients.ts
Just to be sure we won't get any runtime error when using the values to calculate the estimated reach after the client fetches.
MI-888
> fix: fallback values just in case any is null

- __tests__/posts.ts
- src/schema/posts.ts
- src/schema/sources.ts
Since now briefs are public we should support viewing them as non authors as well
> fix: allow non authors to view brief

- bin/migrateNotificationFlags.ts
> update migrateNotificationFlags script to stream

- src/errors.ts
- src/workers/postUpdated.ts
[Thread](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1754495450178329)
> fix: throw so that post update is retried in case of deadlock

- src/common/cloudinary.ts
- src/schema/sources.ts
Unfortunately, I don't think we ever tested image uploads in the past.
MI-984
> feat: allow user to upload squad header image

- .infra/common.ts
- __tests__/posts.ts
- __tests__/workers/cdc/primary.ts
- __tests__/workers/postAnalytics/postAuthorReputationEvent.ts
- src/common/typedPubsub.ts
- src/graphorm/index.ts
- src/workers/cdc/primary.ts
- src/workers/index.ts
- src/workers/postAnalytics/postAuthorReputationEvent.ts
- src/workers/postAuthorReputationEvent.ts
- accumulate author reputation post analytics
> feat: post reputation analytics

- .infra/common.ts
- __tests__/workers/postAnalytics/postAuthorCoresEarned.ts
- src/workers/index.ts
- src/workers/postAnalytics/postAuthorCoresEarned.ts
- accumulate author cores earned post analytics
> feat: post cores earned analytics

- __tests__/posts.ts
- src/common/post.ts
- src/schema/posts.ts
We are allowing only authors to [see their analytics](https://dailydotdev.slack.com/archives/C0987S3AERH/p1756116957852929).
> feat: only allow post author to view analytics

- __tests__/posts.ts
- src/common/brief.ts
- src/entity/user/UserTransaction.ts
- src/remoteConfig.ts
- src/schema/posts.ts
Reverts dailydotdev/daily-api#2993
if one account has generated brief it shows for all new accounts 
MI-969
> Revert "feat: add brief generation for cores"

- __tests__/posts.ts
- src/common/brief.ts
- src/entity/user/UserTransaction.ts
- src/remoteConfig.ts
- src/schema/posts.ts
Reverts dailydotdev/daily-api#3022
Was not a real issue on backend - https://dailydotdev.slack.com/archives/C02E2C3C13R/p1756377115755509?thread_ts=1756372407.525639&cid=C02E2C3C13R
> Revert "Revert "feat: add brief generation for cores""

- src/common/campaign/common.ts
This does not affect prod since we haven't ported the old queries and mutations to the v2 yet - and the functions modified here are only used on v2.
> tmp: do not affect cores when transacting a team member

- .infra/crons.ts
- __tests__/cron/postAnalyticsBoostClickhouse.ts
- __tests__/cron/postAnalyticsClickhouse.ts
- src/common/schema/postAnalytics.ts
- src/cron/index.ts
- src/cron/postAnalyticsBoostClickhouse.ts
- src/entity/posts/PostAnalytics.ts
- src/migration/1756806542962-PostAnalyticsBoost.ts
Add sync for boost metrics from skadi.
> feat: post analytics boost

- package.json
- pnpm-lock.yaml
- src/common/schema/organizations.ts
- src/entity/Organization.ts
- src/entity/opportunities/Opportunity.ts
- src/entity/opportunities/types.ts
- src/entity/user/UserCandidatePreference.ts
- src/migration/1756822434859-OpportunityEnums.ts
Updates to use enums from schema instead of ts enums to ensure correct value
> fix: use schema enums for opportunities and organizations

- __tests__/campaigns.ts
- bin/importCampaignsFromSkadi.ts
- src/entity/campaign/Campaign.ts
- already run initial import in prod db, committing to keep the script for future use if needed
> feat: import skadi campaigns

- src/directive/rateLimit.ts
- src/schema/posts.ts
> feat: add rate limit to create moderation mutation

- __tests__/fixture/opportunity.ts
- __tests__/schema/opportunity.ts
- src/common/utils.ts
- src/entity/opportunities/types.ts
- src/graphorm/index.ts
- src/graphql.ts
- src/schema/opportunity.ts
- src/schema/organizations.ts
Initial draft for opportunity queries.
Need @omBratteng main PR merged to get all new types from Schema.
Would love to here thoughts on this protoToGraphQL function :)
> feat: opportunity queries

- __tests__/workers/cdc/primary.ts
- package.json
- pnpm-lock.yaml
- src/common/opportunity/pubsub.ts
- Adds user candidate keywords to user candidate preference payload
- Fetch the match from database instead of relying on cdc payload, since `[]` is a string and not array :lolsob:
> fix: add keywords to candidate preference payload and fix match payload

- __tests__/schema/opportunity.ts
- src/common/opportunity/pubsub.ts
- src/common/schema/userCandidate.ts
- src/entity/user/UserCandidatePreference.ts
- src/graphorm/index.ts
- src/migration/1757501690774-UCPDefault.ts
- src/schema/opportunity.ts
Query to return user candidate preferences
TODO:
AS-1203
> feat: getCandidatePreferences query

- __tests__/workers/notifications/sourcePostModerationRejectedNotification.ts
Missed updating this typedWorker tests
> fix: missed test cases

- __tests__/schema/opportunity.ts
- src/entity/user/UserCandidatePreference.ts
- src/migration/1757682053334-UserCandidatePreferenceStatusDefault.ts
Default should be open to offers, not disabled
> fix: change default status in UserCandidatePreference

- __tests__/fixture/opportunity.ts
- __tests__/schema/opportunity.ts
- src/common/opportunity/pubsub.ts
- src/schema/opportunity.ts
> feat: mutation to accept opportunity

- __tests__/fixture/opportunity.ts
- __tests__/schema/opportunity.ts
- src/entity/questions/Question.ts
- src/graphorm/index.ts
- src/migration/1757935568161-QuestionOrder.ts
- src/schema/opportunity.ts
Add ordering of screening questions
AS-1213
> feat: add new column questionOrder to question table

- __tests__/schema/opportunity.ts
- src/common/schema/userCandidate.ts
- src/schema/opportunity.ts
Allow sending multiple keywords when adding/removing from candidate profile
AS-1210
> feat: accept multiple keywords

- __tests__/posts.ts
- __tests__/workers/cdc/primary.ts
- src/common/post.ts
- src/common/schema/polls.ts
- src/entity/SourcePostModeration.ts
- src/migration/1758170436298-PostModerationPolls.ts
- src/migration/1758182468623-PollPostModeration.ts
- src/schema/posts.ts
Creating and editing a moderation post, which then turns into an actual Poll Post if approved.
MI-1013
> feat: poll post moderation

- __tests__/schema/opportunity.ts
- src/common/protobuf.ts
- src/entity/user/UserCandidatePreference.ts
- src/migration/1758128497962-UserCandidatePreferenceDefaults.ts
- src/schema/opportunity.ts
Return default values of user candidate preferences when the row does not exist.
Also adds defaults for company stage and size
> fix: return default values for getCandidatePreferences

- .infra/common.ts
- __tests__/cron/validateActiveUsers.ts
- __tests__/notifications.ts
- __tests__/notifications/index.ts
- __tests__/workers/cdc/primary.ts
- __tests__/workers/userUpdatedCio.ts
- src/cio.ts
- src/common/schema/notificationFlagsSchema.ts
- src/notifications/common.ts
- src/notifications/generate.ts
- src/workers/cdc/primary.ts
- src/workers/newNotificationV2Mail.ts
- src/workers/notifications/index.ts
- src/workers/notifications/pollResultAuthorNotification.ts
- src/workers/notifications/pollResultNotification.ts
I think the workers were causing issues because they were missing the `parsedMessage` prop. I thought this was not needed since it was a typed worker, but I think I misunderstood the TODO comment 😅
> fix: poll worker

- __tests__/cron/validateActiveUsers.ts
- __tests__/workers/userUpdatedCio.ts
- src/cio.ts
- src/common/schema/notificationFlagsSchema.ts
- src/notifications/common.ts
- src/notifications/generate.ts
- src/workers/newNotificationV2Mail.ts
Part 1 of the staggered poll worker merge.
This should just add the notification type itself and CIO topic so that the frontend doesn't error.
> feat: poll notification

- __tests__/workers/cdc/primary.ts
- package.json
- pnpm-lock.yaml
- src/common/opportunity/pubsub.ts
- src/common/typedPubsub.ts
- src/workers/cdc/primary.ts
Recruiter accepted event.
Had to remove state tests as they now can trigger on both making them unreliable/wrong.
> feat: recruiter accepted event

- __tests__/notifications/index.ts
- src/notifications/generate.ts
Design update only this part should be colored
> fix: color part

- .infra/common.ts
- __tests__/workers/notifications/warmIntroNotification.ts
- bin/demoTopic.ts
- src/notifications/builder.ts
- src/notifications/common.ts
- src/notifications/generate.ts
- src/notifications/types.ts
- src/workers/newNotificationV2Mail.ts
- src/workers/notifications/index.ts
- src/workers/notifications/warmIntroNotification.ts
Warm intro notification.
Open points:
- Email still missing
- Contact us still missing
Added [demoTopic](https://dailydotdev.slack.com/archives/C02E2C3C13R/p1759387831849689).
> feat: warm intro notification

- __tests__/workers/cdc/primary.ts
- package.json
- pnpm-lock.yaml
- src/common/opportunity/pubsub.ts
Add excluded user ids to topic. (and test)
> fix: publish excluded ids

- src/common/schema/opportunities.ts
- src/entity/OpportunityMatch.ts
- src/workers/newNotificationV2Mail.ts
- src/workers/notifications/warmIntroNotification.ts
Add email for warm intro, (basically empty with title+copy)
Had to store it, otherwise email worker can't access it.
> feat: warm intro email

- __tests__/workers/notifications/warmIntroNotification.ts
- src/workers/notifications/warmIntroNotification.ts
> chore: we should parse markdown for warm intro

- __tests__/redirector.ts
- src/routes/redirector.ts
Closes https://github.com/dailydotdev/daily/issues/1973
> refactor: when url is not available redirect to post page
