__tests__/NotificationResolver.ts
__tests__/helpers.ts
src/Context.ts
src/apollo.ts
src/index.ts
src/middleware/index.ts
src/middleware/trace.ts

A global middleware is attached to the apollo server to trace every resolver call.

feat: trace graphql resolvers

---

__tests__/SourceRequestResolver.ts
__tests__/__snapshots__/SourceRequestResolver.ts.snap
__tests__/helpers.ts
src/common/pubsub.ts
src/compatibility/entity.ts
src/compatibility/publications.ts
src/resolver/SourceRequestResolver.ts

Two new mutations `approveSourceRequest` and `declineSourceRequest` to approve or decline a source request, respectively. Compatibility routes also included.

feat: approve and decline mutations for source request

---

__tests__/__snapshots__/bookmarks.ts.snap
__tests__/bookmarks.ts
__tests__/fixture/post.ts
__tests__/fixture/sourceDisplay.ts
src/apollo.ts
src/common/feedGenerator.ts
src/common/index.ts
src/schema/bookmarks.ts
src/schema/posts.ts
src/schema/sources.ts
src/schema/trace.ts

To resolve efficiently tags and source, I created a `feedGenerator` utility which builds only one query to fetch both the feed and all the necessary information.

feat: add tags and source fields to post type

---

__tests__/__snapshots__/bookmarks.ts.snap
__tests__/__snapshots__/feed.ts.snap
__tests__/bookmarks.ts
__tests__/feed.ts
__tests__/fixture/post.ts
__tests__/helpers.ts
src/apollo.ts
src/compatibility/posts.ts
src/entity/Post.ts
src/schema/feed.ts

`anonymousFeed` query returns feed for unregistered users. It allows to generate ad-hoc feeds by sources and tags. Compatibility route `GET /v1/posts/latest` added accordingly.

feat: anonymous feed query

---

__tests__/__snapshots__/feed.ts.snap
__tests__/feed.ts
src/compatibility/posts.ts
src/schema/feed.ts

`tagFeed` query generates a dedicated feed for a single tag. Compatibility route `GET /v1/posts/tag` added accordingly.

feat: tag feed query

---

__tests__/__snapshots__/tags.ts.snap
__tests__/fixture/tagCount.ts
__tests__/tags.ts
src/apollo.ts
src/compatibility/index.ts
src/compatibility/tags.ts
src/entity/Bookmark.ts
src/entity/Post.ts
src/entity/TagCount.ts
src/migration/1588607400115-TagCountIndex.ts
src/schema/feed.ts
src/schema/posts.ts
src/schema/tags.ts

`popularTags` and `searchTags` are new queries to get the most popular tags and search. Compatibility routes `GET /v1/tags/popular` and `/v1/tags/search` added accordingly.

feat: get popular tags and search tags queries

---

__tests__/__snapshots__/posts.ts.snap
__tests__/posts.ts
src/apollo.ts
src/compatibility/posts.ts
src/compatibility/utils.ts
src/directive/UrlDirective.ts
src/errors.ts
src/schema/posts.ts

`post` query returns a post by id. Compatibility route `GET /v1/posts/:id` added accordingly

feat: get post by id query

---

__tests__/__snapshots__/feeds.ts.snap
__tests__/feeds.ts
src/apollo.ts
src/compatibility/feeds.ts
src/compatibility/index.ts
src/schema/feeds.ts

Add two mutations to add and remove filters from user's feed. Compatibility routes added accordingly as well.

feat: mutations to manage feed filters

---

__tests__/__snapshots__/feeds.ts.snap
__tests__/feeds.ts
src/common/feedGenerator.ts
src/compatibility/posts.ts
src/compatibility/utils.ts
src/schema/feeds.ts

`feed` query fetches a preconfigured feed. Compatibility route `/v1/posts/latest` updated to return preconfigured feed when logged-in.

feat: feed query to fetch preconfigured feed

---

__tests__/sourceRequests.ts
src/compatibility/publications.ts

The correct body schema for the source request is `{source: ''}'`

fix(compat): POST /publications/request body schema

---

src/common/algolia.ts
src/common/feedGenerator.ts

There are two ways to do pagination with Algolia page/hitsPerPage or offset/length, before we were mixing the two which caused wrong pagination.

fix: use algolia offset/length pagination

---

src/schema/posts.ts

Remove the premium authorization for the bookmark list field as it breaks every query that request this field.
Instead just return null when not premium.

refactor: change permissions for bookmark list field

---

__tests__/__snapshots__/posts.ts.snap
__tests__/fixture/post.ts
__tests__/fixture/source.ts
__tests__/fixture/sourceDisplay.ts
__tests__/posts.ts
src/common/feedGenerator.ts
src/compatibility/posts.ts
src/schema/feeds.ts

Allow access to any post by id. Currently, there is nothing personal in posts of private sources.
This commit fixes the issue of throwing 404 when trying to navigate to posts of private sources.
Closes #109

fix: allow access to posts of a private source

---

__tests__/sources.ts
package.json
src/schema/sources.ts

In case superfeedr fails while adding a private source, the request still has to succeed.
If it fails, an error log should be written so a manual action can be taken to fix this issue.
Closes #105

fix: complete adding private source even if superfeedr fails

---

src/schema/bookmarks.ts

Before this commit the created at field was updated upon changing the bookmark list.
Now it remains the same so it will not affect the order of the bookmarks.

refactor: keep created at when adding bookmarks to list

---

__tests__/__snapshots__/tags.ts.snap
__tests__/__snapshots__/updateTags.ts.snap
__tests__/updateTags.ts
helm/daily-api/templates/cronjobs.yaml
src/cron/updateTags.ts
src/schema/tags.ts

Tags count table is now calculated every week and takes into account posts of the last 180 days.
The threshold for finding a tag was lowered to 10 posts from 50.
These changes should enable better discovery of tags.
Closes dailydotdev/daily#166

refactor: update tags discovery mechanism

---

__tests__/__snapshots__/bookmarks.ts.snap
__tests__/__snapshots__/feeds.ts.snap
__tests__/bookmarks.ts
__tests__/feeds.ts
src/common/feedGenerator.ts
src/common/pagination.ts
src/schema/bookmarks.ts
src/schema/common.ts
src/schema/compatibility.ts
src/schema/feeds.ts
src/schema/posts.ts
src/schema/sourceRequests.ts
src/schema/sources.ts

To boost performance, I reimplemented the pagination mechanism to use `where` instead of `offset`.
`where` clause can utilize indexes and increase drastically the performance of the query compared to the traditional `offset` implementation.
This implementation is backward compatible thanks to the cursor pagination that is already implemented in the client.

refactor: pagination optimization

---

__tests__/newPost.ts
src/workers/newPost.ts

From now, before adding a new post, its canonical url will be checked as well to prevent duplication of cross-posted articles

feat(newPost): prevent duplicates based on canonical url

---

src/common/feedGenerator.ts
src/graphorm/graphorm.ts
src/graphorm/index.ts
src/routes/rss.ts
src/schema/feeds.ts

Use GraphORM to fetch the user`s feed settings in one almighty resolver

refactor: migrate feed settings to graphorm

---

__tests__/__snapshots__/updateFeaturedComments.ts.snap
__tests__/updateFeaturedComments.ts
src/common/pubsub.ts
src/compatibility/utils.ts
src/cron/updateFeaturedComments.ts

Once a new comment is featured a Pub/Sub message is sent.
Max featured comments per article is set to 3.
This will enable sending emails and increasing reputation in the future.

feat: send pubsub event when new comment is featured

---

__tests__/__snapshots__/newUser.ts.snap
__tests__/__snapshots__/updateUser.ts.snap
__tests__/updateUser.ts
src/entity/User.ts
src/migration/1600691199678-Username.ts
src/workers/updateUser.ts

With the introduction of the new user profile, the API must save a local copy of the username and the twitter handle for future use

feat(user): denormalize username and twitter handle

---

__tests__/__snapshots__/sourceRequests.ts.snap
__tests__/__snapshots__/sources.ts.snap
__tests__/sources.ts
src/entity/Source.ts
src/migration/1602427333872-ActiveSources.ts
src/schema/sources.ts

The active property indicates if the source is still active and should be returned in the sources list.
Inactive sources exist to keep posts that are already in the database and might be bookmarked

feat: add active property to source

---

__tests__/__snapshots__/newPost.ts.snap
__tests__/__snapshots__/newUser.ts.snap
__tests__/__snapshots__/posts.ts.snap
__tests__/__snapshots__/updateUser.ts.snap
__tests__/newPost.ts
__tests__/posts.ts
__tests__/updateUser.ts
src/common/pubsub.ts
src/entity/Post.ts
src/entity/User.ts
src/graphorm/graphorm.ts
src/migration/1602572107385-PostAuthor.ts
src/schema/posts.ts
src/workers/newPost.ts
src/workers/updateUser.ts

When a post is added, the twitter handle is matched against our database to find the user who wrote the post.
If the user is found, it is saved in the database and send a pub/sub message

feat: match author to post

---

__tests__/postCommentedAuthorTweet.ts
src/workers/postCommentedAuthorTweet.ts

The old format used to create a lot of duplicate tweets which is not allowed by the Twitter API.
The new format contains the number of comments which makes it unique.

refactor: add comments count to tweets to make it unique

---

src/common/feedGenerator.ts
src/schema/common.ts
src/schema/feeds.ts

If the response size equals the page size, the `hasNextPage` property will be set to true which is wrong.
The new implementation limits the query to the pageSize+1 and checks if indeed this was the response size
Closes dailydotdev/daily-webapp#174

fix: pagination edge case where response size equals the page size

---

__tests__/workers/__snapshots__/updateUser.ts.snap
__tests__/workers/updateUser.ts
src/workers/newView.ts
src/workers/updateUser.ts

To prevent race conditioning, it is better to upsert the user instead of updating which can fail

fix: upsert user on update instead of updating

---

src/common/pageGenerator.ts
src/schema/comments.ts
src/schema/posts.ts

DD-219#done
The Generic Page Generator is reliant on the order of the actual query. So the condition must come from the parameter that the consumer would send.
Since `orderBy` overrides the existing parameters, I used `addOrderBy` so consumers would still be able to apply their own set of rules for the order in the query builder.

fix: generic page generator order condition based on parameter

---

.env
__tests__/__snapshots__/feeds.ts.snap
__tests__/feeds.ts
__tests__/personalizedFeed.ts
__tests__/workers/checkDevCardEligibility.ts
infra/Pulumi.prod.yaml
src/Context.ts
src/common/feedGenerator.ts
src/index.ts
src/personalizedFeed.ts
src/redis.ts
src/schema/common.ts
src/schema/feeds.ts

Add a new version field to the anonymous feed and user feed queries.
The new field allows running a/b tests on the feeds and optimizing the algorithm.
Version 2 uses Tinybird's API to fetch the feed and cache it.
DD-189

feat: anonymous feed and user feed v2

---

__tests__/__snapshots__/feeds.ts.snap
__tests__/feeds.ts
src/common/feedGenerator.ts

DD-286 #done
While working on the mutations of the UI, I bumped into a case where the user will have two or more false `enabled` values for the feed advanced settings.
- Included a commit where the test would fail if there are 2 or more false `enabled` values.
- Also included a commit where the tests would pass after the fix.

fix: feed filters query with 2 or more false advanced settings

---

__tests__/__snapshots__/feeds.ts.snap
__tests__/feeds.ts
src/schema/feeds.ts

DD-302 #done
For newly created users, when feed doesn't exist yet. The mutation might fail since the `feedId` is an FK at `FeedAdvancedSettings` entity going to `Feed` entity.

fix: if feed is missing on feed advanced settings mutation

---

.circleci/config.yml
__tests__/feeds.ts
__tests__/personalizedFeed.ts
src/personalizedFeed.ts
src/redis.ts
src/schema/feeds.ts

We change the way we invalidate v2 cache by presenting a new key that indicates when was the last update to a given feed.
Comparing the new timestamp with the last generated timestamp indicates if we need to invalidate the cache.

fix: invalidate v2 cache correctly

---

src/common/users.ts

The timezone was parsed as null instead of fallback to UTC.
This double check makes sure it's either a timezone or default back to UTC.
Related issue: https://github.com/dailydotdev/daily/issues/349

fix: timezone was parsed as null in the latest change

---

__tests__/cron/__snapshots__/updateFeaturedComments.ts.snap
__tests__/cron/updateFeaturedComments.ts
src/cron/updateFeaturedComments.ts
src/graphorm/index.ts

Fixed the duplicate authors for featured comments.
Note: We need the " quotes hence the force backticks.
DD-307 #done

fix: fix duplicate authors for featured comments

---

__tests__/__snapshots__/comments.ts.snap
__tests__/comments.ts
src/common/markdown.ts

Make sure markdown links get target blank and rel attribute.
Note: When pushing life, we have to re-seed the comments.
- Remove all existing content_html and run the helper again.

fix: markdown links target and rel

---

__tests__/__snapshots__/newPost.ts.snap
__tests__/newPost.ts
src/auth.ts
src/common/index.ts
src/entity/Post.ts
src/routes/index.ts
src/routes/private.ts
src/workers/newPost.ts

The new route will be used by our new Gatekeeper service to push new content to the database.
Currently, adding new articles is supported only through Pub/Sub and the Gatekeeper requires a synchronous solution so Pub/Sub is not suited for this.

feat: add new route to add posts

---

__tests__/__snapshots__/feeds.ts.snap
__tests__/feeds.ts
src/schema/feeds.ts

Feed v2 introduced a bug where if the user is logged-in then it will automatically fetch the feed with the filters. This PR fixes the issue and adds support for anonymous feed for logged-in users.

fix: anonymous feed support for logged in users

---

src/index.ts

Due to many timeouts and sigterm errors, I suspect there's a memory leak somewhere in the app. My first concern is the GraphQL Subscriptions, so I temporarily disable them to check what happens.

refactor: disable graphql subscription

---

src/common/slack.ts

Swapped around the title and the comment field for the slack message.
New format:

fix: new slack comment format

---

src/schema/users.ts

We introduced the timezone for all reading history queries, but not the actual overview.
This fix makes sure we convert the timezone to the user's set timezone.
DD-497 #done

fix: timezone was not actively used for the reading history overview

---

src/schema/users.ts

In the way I was loading the user before it would fail if the user didn't have a timezone set.
Meaning they wouldn't be able to load their reading history.
After fixing this issue it also seems that the removing started working locally again.
Will have to double check on merge.
DD-498 #done

fix: reading history was failing on users with no timezone

---

__tests__/users.ts
src/common/users.ts
src/schema/users.ts

The `userReadingRank` now accepts a `limit` param for the number of tags to return but the default value is 6.

refactor: tags limit on reading rank

---

src/common/users.ts
src/schema/users.ts

Let's take the following data as an example:
In the current live version (double timezone) we actually reset the timezone back to UTC
When only using one timezone conversion it shows the time in that users zone:
Let me know what you think.
I left the weekly rank, as this is based on the users week, which might start on a different day.
DD-550 #done

fix: In some cases the timezone was actually negative

---

src/common/users.ts

Since the name was the one used for searching the LIKE fails on username even being null.
This should explicitly restrict the result for users without usernames.

fix: restrict mention on null username

---

src/index.ts

Disable GraphQL subscriptions due to the memory and CPU overload which caused performance regression.
We can evaluate separating subscriptions to a new deployable unit

refactor: disable graphql subscriptions

---

__tests__/__snapshots__/alerts.ts.snap
__tests__/alerts.ts
__tests__/workers/cdc.ts
src/entity/Alerts.ts
src/migration/1649851992869-AddCompanionHelper.ts
src/routes/alerts.ts
src/schema/alerts.ts

Added a companion helper alert.
This alert will keep track of wether someone has opened the companion before (if so we don't show the helper again)
The default is true: meaning companion helper should be shown
If it's set to false we don't show the companion helper.
We can possibly event update this alert in the boot query for the companion to update to false, since it's a once-off thing.
DD-458

feat: Add companion helper alert

---

.circleci/config.yml
infra/index.ts

We now use `us.gcr.io` as our public registry.
`gcr.io` will be turned private soon.
DD-235

ci: change docker registry

---

__tests__/__snapshots__/comments.ts.snap
__tests__/comments.ts
src/common/markdown.ts

We had the HTML option enabled in the markdown parser, allowing all HTML to be valid.
We removed this so the rendered only renders markdown to HTML, and converts HTML into plain strings.
We also added a test case to validate this change, and tested it locally.
DD-595 #done

fix: remove HTML option from markdown parser

---

__tests__/__snapshots__/settings.ts.snap
__tests__/settings.ts
__tests__/workers/cdc.ts
src/compatibility/settings.ts
src/entity/Settings.ts
src/migration/1651214210491-AutoDismissSettings.ts
src/routes/settings.ts
src/schema/settings.ts

As part of our accessibility compliance, we will have to allow the user to decide whether they want to automatically dismiss notifications or not.
- The property is known as `autoDismissNotifications`
- Default value is true. The false value is intended for users that might not be able to react quickly enough and click the action button inside our notifs.

refactor: settings entity - additional property (autoDismissNotifications)

---

__tests__/posts.ts
src/schema/posts.ts

In line with the toast component having an undo button - we don't have yet a way to actually remove a report or unhide a post once saved.

feat: unhide and removal of report on post

---

infra/workers.ts

There's an error with the current `pulumi-up` as it tried to register a subscription to a non-existent topic.

refactor: unnecessary subscription

---

.circleci/config.yml
__tests__/cron/tweetTrending.ts
__tests__/cron/updateFeaturedComments.ts
__tests__/sourceRequests.ts
__tests__/workers/cdc.ts
__tests__/workers/commentCommented.ts
__tests__/workers/commentCommentedAuthor.ts
__tests__/workers/commentCommentedThread.ts
__tests__/workers/commentFeaturedMail.ts
__tests__/workers/commentUpvoted.ts
__tests__/workers/communityLinkAccessMail.ts
__tests__/workers/communityLinkRejectedMail.ts
__tests__/workers/postAuthorMatchedMail.ts
__tests__/workers/postBannedEmail.ts
__tests__/workers/postCommentedAuthor.ts
__tests__/workers/postCommentedAuthorTweet.ts
__tests__/workers/postReachedViewsThresholdTweet.ts
__tests__/workers/postScoutMatchedMail.ts
__tests__/workers/sendAnalyticsReportMail.ts
package.json

We where using the old implementation of `mocked` and should use `jest.mocked`.

chore: refactor mocked to jest.mocked

---

__tests__/submissions.ts
infra/workers.ts
src/schema/posts.ts

We exposed the deleted property, in this fix we change it to be only selected for the specific query and not open.

fix: remove exposed deleted property

---

__tests__/__snapshots__/submissions.ts.snap
__tests__/submissions.ts
__tests__/workers/cdc.ts
src/entity/Submission.ts
src/migration/1655452252620-ChangeSubmissionStatus.ts
src/schema/posts.ts

The not start status was unneeded as we always start on adding it, so we can simply change the default to `Started`.

fix: setting the default to started

---

src/workers/postScoutMatchedSlack.ts

Change the slack color to our branded purple for submissions messages

fix: change slack message color for submissions

---

__tests__/__snapshots__/comments.ts.snap
__tests__/comments.ts
src/common/markdown.ts
src/schema/comments.ts

I have written numerous test cases to ensure all the edge cases will be covered. The behavior of when to allow the mention of what special character it was beside, was based on Twitter. On Twitter, they allow any special character so long as it is not the at (@) sign.
First, we replace the special characters with spaces to figure out which ones are valid mentions of users.
Then while we check each word for any mention, we replace again the special characters but this time we store them in an array so we can easily reconstruct the word for which one was replaced.
If the mention was found we will generate the anchor tag with it.

fix: user mention beside a special character

---

__tests__/private.ts
src/routes/private.ts

Currently it's possible for the gatekeeper to send duplicate request to addNewPost and rejectPost routes.
The addNewPost will simply return that the post already exists.
However with the rejection we kept updating the status to Rejected even if it already was approved or rejected.
This fix prevents duplicate resets.
WT-174 #done

fix: prevent duplicate rejection

---

__tests__/private.ts
__tests__/submissions.ts
__tests__/workers/__snapshots__/communityLinkRejectedMail.ts.snap
__tests__/workers/cdc.ts
src/entity/Post.ts
src/entity/Submission.ts
src/errors.ts
src/routes/private.ts
src/schema/submissions.ts
src/workers/communityLinkRejectedMail.ts
src/workers/newPost.ts

We decided to remove string variants of error messages for community links.
As we don't have a clear plan for error codes we decided to move forward with the introduction of generic error keys.
The API manages these API keys, and we made a first start by introducing community links related keys.
Related PR:
Gatekeeper: https://github.com/dailydotdev/gatekeeper/pull/184

feat: introducing generic error messages for community links

---

__tests__/workers/communityLinkRejectedMail.ts
src/workers/communityLinkRejectedMail.ts

After deploying the fix it still seemed to give issues on production.
Inspected the subscription payload and noticed it actually gets send as a unix timestamp. (microseconds)
Decided to have the test reflect the same value so this won't happen in the future.
WT-200 #done

fix: convert unix timestamp to actual dates

---

src/workers/postScoutMatchedMail.ts

Following our other email guidelines there seems to be some formatting issue in the way we send it.
This fixes the community links approval email to contain valid links.
Also formatted the image differently on the sendgrid side so it will reflect.
WT-225 #done

fix: the approval link was messed up in formatting

---

__tests__/workers/__snapshots__/commentCommentedAuthor.ts.snap
__tests__/workers/__snapshots__/postCommentedAuthor.ts.snap
__tests__/workers/__snapshots__/sendAnalyticsReportMail.ts.snap
__tests__/workers/commentCommentedAuthor.ts
__tests__/workers/postCommentedAuthor.ts
__tests__/workers/sendAnalyticsReportMail.ts
src/common/mailing.ts
src/common/post.ts
src/common/users.ts
src/workers/commentCommentedAuthor.ts
src/workers/postCommentedAuthor.ts
src/workers/sendAnalyticsReportMail.ts

We send emails to authors whenever a user has commented on their post or commented in a comment. These emails must also be sent to the scout if there are any.
The reason why the analytics was not being sent since then is, that we have a cron job that checks for post analytics to send, and if it found any, it will automatically set the property `sentAnalyticsReport` to true. Which will then trigger a CDC pubsub notification to our worker.
But then on the actual worker, we have a condition it will only send if the value is false, but the actual reason why this worker was triggered, was due to the value being true.
https://github.com/dailydotdev/daily-api/pull/993/files#diff-21447dd107efb6a2c1bc5f6b8efd19a811618dbd67a092324739f5cccb954196L22

refactor: author emails to send on scout

---

__tests__/workers/__snapshots__/sendAnalyticsReportMail.ts.snap
__tests__/workers/cdc.ts
__tests__/workers/sendAnalyticsReportMail.ts
src/workers/cdc.ts

As discussed, we are preparing the sending out of email once the user has reached such reputation points to be able to submit community picks article.
Relevant reverted commit: https://github.com/dailydotdev/daily-api/pull/968/commits/3eb35a297d41a22ce5ccc19a737d793980c7ce2c

refactor: community picks access granting email

---

__tests__/private.ts
__tests__/workers/cdc.ts
__tests__/workers/postBannedRep.ts
src/entity/Source.ts
src/workers/cdc.ts
src/workers/postBannedRep.ts

During beta we don't want to penalize scouts when banning or deleting their posts.

refactor: disable penalization for community picks

---

src/common/users.ts

We had a recent issue with counting the total submission for the day and was fixed. We've thought to introduce the same fix on the user reading rank since it is the same timezone-related issue.
It can be seen below in the history of commits that the first one failed and after applying the fix, the tests have passed.
Shoutout to @vpol for providing the fix in the submission issue which was also used here 🚢 
WT-254 #done

fix: timezone user reading rank failing test on monday

---

.infra/index.ts
Dockerfile
__tests__/health.ts
docker-compose.yml
package.json
src/index.ts

Subscribe to `SIGTERM` to allow graceful termination and avoid 5xx on deploys

ci: graceful termination

---

__tests__/__snapshots__/users.ts.snap
__tests__/users.ts
__tests__/whoami.ts
src/common/cloudinary.ts
src/common/object.ts
src/entity/User.ts
src/errors.ts
src/migration/1660640181400-UniqueSocialHandles.ts
src/routes/whoami.ts
src/schema/users.ts

Since the source of truth is now for the profile information, we will be having an API to allow updating it.
Question:
- Should we now remove the subscription on the gateway for watching changes in the user?
- Would we want to instead create a worker to send a post request to the Kratos server? (current one sends a post request in the FE)

feat: updating account profile

---

__tests__/workers/deleteUser.ts
src/common/pubsub.ts
src/schema/users.ts
src/workers/cdc.ts
src/workers/deleteUser.ts

Introduces API user deletion.
Since we have foreign key constraints on userId's we have to follow the existing deletion flow.
We also need to support existing deletion from the Gateway side of things.
Thus added a Kratos flow to not duplicate run queries when the user is already deleted.
WT-333

feat: API user deletion

---

src/schema/users.ts

Reduce the strictness of the regex to make sure requests will not fail because of an invalid name.

refactor: weaker name policy for users

---

.infra/crons.ts
__tests__/cron/cleanZombieUsers.ts
src/cron/cleanZombieUsers.ts
src/cron/index.ts

Zombie users are users that have `infoConfirmed = false` and are older than one hour. A new cron job is added to remove zombie users from the database.
WT-486#done

feat: clean zombie users 🧟

---

__tests__/private.ts
src/config.ts
src/entity/User.ts

When a user signs up with GitHub we prepopulate the GitHub handle. This may yield a unique key violation which we want to prevent.
WT-621 #done

fix: ignore the github handle if it already exists when adding new user

---

src/schema/comments.ts
src/schema/users.ts

Excluding deleted posts comment in the comment section and comment count.
Before:
After:
WT-283 #done

fix: don't show/count deleted post comments

---

src/schema/settings.ts

~~WIP: still spooling up my local env to test the changes.~~
Running 2 save commands in the same transaction seems to result in conflict with one another even though we used upsert. Probably the ORM has thought the same command should use the insert as the first save is deferred due to being in the same transaction.

fix: settings create conflict on same transaction

---

src/Context.ts
src/auth.ts
src/index.ts

Cookies are not provided when using WebSocket in the extension. Hence, our authentication doesn't work in GraphQL Subscriptions from the extension. 
This PR adds another step in the connection to check the token provided by the client explicitly. 
This is required for the notifications.
Apps PR: https://github.com/dailydotdev/apps/pull/1394

feat: add authentication support for graphql subscriptions

---

__tests__/__snapshots__/users.ts.snap
__tests__/users.ts
__tests__/workers/cdc.ts
__tests__/workers/newNotificationMail.ts
src/entity/User.ts
src/migration/1671161744023-EmailNotificationPreference.ts
src/schema/users.ts
src/workers/newNotificationMail.ts

As discussed, to keep things simple, we will include the notification email preference in the user's table than creating a new one.
We will then create a separate table once we decide to implement a more granular control of the notification preference.

feat: notification email preference

---

__tests__/users.ts
__tests__/workers/newNotificationRealTime.ts
src/schema/users.ts

Users are not able to update their community newsletter setting because the mutation is too strict. I loosen it a bit to allow partial update if the profile is already confirmed.

fix: allow partial user profile update when profile is confirmed

---

.infra/index.ts
__tests__/helpers.ts
__tests__/users.ts
src/index.ts
src/subscription.ts
src/workers/newNotificationPush.ts

Use Redis to keep a list of connected users to our gql subscription. Using this list we decide whether to send a push notif or not.

feat: do not send push notif to connected users

---

__tests__/notifications/index.ts
__tests__/posts.ts
__tests__/sources.ts
src/common/links.ts
src/graphorm/index.ts
src/notifications/builder.ts
src/schema/posts.ts
src/schema/sources.ts

* Add `permalink` field to `Source`
* Add `viewPost` mutation to generate view event for non-article posts
* Add `sourceMemberByToken` query for the invitation page

feat: more squad queries and mutations

---

__tests__/comments.ts
__tests__/compatibility.ts
__tests__/feeds.ts
__tests__/posts.ts
src/common/feedGenerator.ts
src/schema/comments.ts
src/schema/feeds.ts
src/schema/posts.ts
src/schema/sources.ts

Limit the ability of users to comment/upvote/fetch data of posts that they cannot access. 
This might impact the performance of some pages, so we should keep it in mind.

fix: proper permissions enforcement

---

src/notifications/generate.ts

Based from the excel file, it is only the approval of source that required a change on its title.
https://docs.google.com/spreadsheets/d/1bvKkik_b-woB6slDp-MIqnmMgXJoS-7nOy9X3yIggUs/edit#gid=0

refactor: source accepted title copy

---

__tests__/sources.ts
src/schema/sources.ts

To validly check whether the `handle` is available or not, we must check it outside of the user's permission. To consider the security of the information, we will only return a boolean value instead of the whole `Source` data itself as commonly done in other queries.
Relevant discussion: https://dailydotdev.slack.com/archives/C03QZBF46JC/p1674486326108479?thread_ts=1674402848.080819&cid=C03QZBF46JC

feat: check handle outside of permission

---

src/entity/posts/Post.ts
src/entity/posts/utils.ts

Moved from the beforeInsert query to inline function.
Test cases already existing for post privacy
WT-1019 #done

fix: redirect privacy check to inline functions

---

__tests__/sources.ts
src/common/object.ts
src/schema/sources.ts
src/schema/users.ts

When we check for the availability of the handle, we must also check if the given parameter is actually valid based on our rules.
This would also allow us to keep the form validations in the same step rather than doing it when the user is finishing the Squad they are trying to create.

fix: validate handle based on regex before checking availability

---

__tests__/workers/newNotificationMail.ts
src/workers/newNotificationMail.ts

Added the full_name property to the squad access mail
WT-1043 #done

fix: add full_name to squad access mail

---

__tests__/workers/notifications.ts
src/workers/notifications/commentMention.ts

When the author or scout was mentioned, they receive two notifications, one from being an author/scout of the post that is subscribed to the post's activity and one when you get mentioned.
The condition of early return should fix and not send a notification when not needed.

fix: double notification for authors mentioned

---

.infra/workers.ts
__tests__/alerts.ts
__tests__/boot.ts
__tests__/workers/cdc.ts
__tests__/workers/postChangelogAdded.ts
src/config.ts
src/entity/Alerts.ts
src/migration/1675936666556-AlertsChangelog.ts
src/redis.ts
src/routes/alerts.ts
src/routes/boot.ts
src/schema/alerts.ts
src/workers/postChangelogAdded.ts

Added a new alert flag for lastChangelog, FE will be responsible for updating it through existing channels.
Added a new worker to set a redis cached value of our last changelog date.
Boot can then check wether this date is more up to date, and set Changelog to true.
WT-1054 #done

feat: introducing changelog flag for boot

---

__tests__/sources.ts
src/schema/sources.ts

There was an issue that a user could join multiple times to a squad which will yield updating their memberships causing new referral link and changing role to member even for owners

fix: disable "joining twice" to squad

---

__tests__/__snapshots__/alerts.ts.snap
__tests__/alerts.ts
__tests__/workers/cdc.ts
src/entity/Alerts.ts
src/migration/1677030838294-AlertViewedTour.ts
src/routes/alerts.ts
src/schema/alerts.ts

Introduced a new alert property to identify whether to display the squad tour and be synced across devices.

refactor: alert entity to include state of squad tour viewed

---

__tests__/workers/notifications.ts
src/workers/notifications/featureAccessNotification.ts

Prevent notification for squad access for users who are already in a squad
WT-1095 #done

fix: prevent notification for users who are part of squad

---

__tests__/workers/notifications.ts
src/workers/notifications/articleUpvoteMilestone.ts
src/workers/notifications/utils.ts

A comment notification is duplicated when the author/scout is following a thread where they will receive a "reply notificaion" when there is a new comment.
After the discussion, Sab has decided to prioritize the "reply notification" and forego the author/scout post new comment notification for these cases.
https://dailydotdev.slack.com/archives/C03QZBF46JC/p1676885204557179?thread_ts=1676878287.868739&cid=C03QZBF46JC

fix: do not send notification to author/scout from comment following a thread

---

__tests__/boot.ts
src/routes/boot.ts

Fix edge case where if redis value is empty boot `changelog` will always be `false`.

feat: update redis cache inline during changelog computation

---

__tests__/posts.ts
__tests__/sources.ts
src/schema/posts.ts
src/schema/sources.ts

Allow moderators and owners to delete a post.
Had one issue while running some tests so I updated the `canAccessSource` to check for members if they exist.

feat: squad moderator privileges

---

src/workers/newNotificationMail.ts

Our previous `comment_reply` email was heavily focussed on people always responding to the receiving user.
The reality is that our comment system supports "thread" like notifications.
The email template has been adjusted to reflect this content wise, [see here](https://dailydotdev.slack.com/archives/C02AA18RD1D/p1677663574970499?thread_ts=1677572131.388829&cid=C02AA18RD1D).
This means from a API side we should always fetch the active user from the parent comment.
WT-1111 #done

fix: migrated to reply thread notifications

---

__tests__/boot.ts
src/cookies.ts
src/kratos.ts
src/routes/boot.ts

Instead of patching the expiration of the kratos cookie, we use the returned `set-cookie` header. This will make sure there are no discrepancies.

fix: use the `set-cookie` header to set properly kratos cookie

---

__tests__/sources.ts
src/common/object.ts

Allowing new lines in the description of squad.
By default `.` only checks for any character excluding new lines.
Also added a test case for it.
WT-1131 #done

fix: allow newlines in description

---

__tests__/__snapshots__/private.ts.snap
__tests__/private.ts
__tests__/workers/cdc.ts
src/entity/posts/Post.ts
src/entity/posts/utils.ts
src/migration/1677645829524-PostOrigin.ts

Introduce 3 new properties for the post entity.
- visible: boolean
- visibleAt: date
- origin: text - have set this as a private property so we won't mistakenly update the value.

refactor: post entity updated properties

---

__tests__/workers/notifications.ts
src/workers/notifications/postAdded.ts

With external links we need to be careful not to send notifications for authors that can't access the post. So if the post belongs to a machine source we will not send a notification for private posts

fix: don't add article picked notification for private posts

---

src/schema/sources.ts

We have to support backwards compatibility and step one is to make post id optional for create squad endpoint.
WT-1152

fix: make post creation optional for new squad

---

__tests__/sources.ts
src/schema/sources.ts

Should only be merged once v3 is in production.
It will set squad active by default (non breaking for the frontend)
WT-1163

fix: make squads active by default

---

__tests__/posts.ts
src/graphorm/index.ts
src/schema/posts.ts

* Check permissions for posts returned by `postByUrl`
* Minor perf improvement to post query for public posts

fix: enforce permissions in postByUrl query

---

__tests__/sources.ts
src/graphorm/index.ts
src/schema/sources.ts

We agreed on the web team sync to add member fields to the source entity to be able to show roles on the post feed and member listings for the squad members. 
We also agreed that it might not be best decision scaling wise because if squads have hundreds of moderators and other members this fields would become quite big. `50` limit was added to prevent any excess cases while in beta - this should catch most of the squads though since they don't have many privileged members.

feat(squads): source members fields

---

__tests__/__snapshots__/sources.ts.snap
__tests__/boot.ts
__tests__/comments.ts
__tests__/cron/__snapshots__/updateTagsStr.ts.snap
__tests__/cron/__snapshots__/updateTrending.ts.snap
__tests__/fixture/post.ts
__tests__/fixture/source.ts
src/schema/comments.ts
src/schema/sources.ts

Allow deletion of comments by relevant roles.
Let me know if you guys think postDelete scope is ok, or we want a seperate scope?
WT-1183 #done

fix: add check for deletion of comments by relevant role

---

__tests__/__snapshots__/sources.ts.snap
__tests__/sources.ts
src/graphorm/index.ts
src/schema/sources.ts

- Unblock a member by removing the row from the table which would allow the user to re-join when they want to.
- I have also deleted the commented test cases for `removing a member` as it was already reused on the role update tests.
- Update `sourceMembers` query to accept a boolean parameter to return all blocked users only.
- Also updated the queries of tests to include `role` property to easily check snapshots.

feat: unblock a squad member

---

__tests__/notifications/index.ts
__tests__/workers/newNotificationMail.ts
__tests__/workers/notifications.ts
src/entity/Notification.ts
src/notifications/generate.ts
src/workers/newNotificationMail.ts
src/workers/notifications/sourceMemberRoleChanged.ts

We changed the copy to be uniform to role (owner and moderator) these promotions now also get a email.
Added test cases and modified existing ones.
WT-1220 #done

fix: new role evaluation

---

__tests__/sources.ts
src/graphorm/index.ts
src/roles.ts
src/schema/sources.ts

Update posting permissions during `editSquad` mutation. Also expose `memberPostingRole` field.

feat(squad): update posting permissions

---

__tests__/sources.ts
src/graphorm/graphorm.ts
src/schema/sources.ts

We display an indicator to let the our users know whether the author of the comment they are replying to won't be able to have access on their response by showing some alert. We display that alert after checking whether the user is blocked or not a member of the squad.
Changes:
- Seeing the graphorm used for fetching single-row items on numerous areas, I've decided to abstract the throwing of error when none is found.
- Introduced a query to check the user's membership.

feat: query user's membership

---

__tests__/sources.ts
src/graphorm/index.ts
src/schema/sources.ts

Make sure `referralToken` of other users can not be queried through relations or listings. From what I talked with Ido before this should cover all cases.

feat: filter out referral token for other users

---

__tests__/boot.ts
__tests__/sources.ts
src/graphorm/index.ts
src/routes/boot.ts
src/schema/sources.ts

Since `permissions` are used on the frontend to check if user should see any action/ui element we wanted to automatically exclude `SourcePermissions.Post` permissions array based on `memberPostingRank` setting for squad. 
Also adds `currentMember.permissions` to `boot.squads` (only `SourcePermissions.Post` to keep boot size lean).
Initial discussion and alternatives can be found here https://github.com/dailydotdev/apps/pull/1723#discussion_r1159470225
Note to @idoshamun I am not sure if this kind of `select` is performant or is there a better way to do it - considering everything `graphorm` does under the hood.

feat: exclude post permission for squad based on memberPostingRank

---

__tests__/posts.ts
__tests__/workers/postUpdated.ts
src/schema/posts.ts

Re-submitting a not yet finished private link would result in making the shared post immediately visible in squad (also breaking UI since `post.sharedPost` was `undefined`).
During private link creation `visible` property of the original post is now checked and shared post visibility is set to the same value. 
Also updated `postUpdated` test to make sure all the pending squad posts are made visible once the content requirements are met through scraping (was already the case but just to be more specific).

fix: squad shared post visibility condition

---

__tests__/workers/notifications.ts
src/workers/notifications/articleUpvoteMilestone.ts
src/workers/notifications/commentUpvoteMilestone.ts
src/workers/notifications/postAdded.ts
src/workers/notifications/utils.ts

When a user shared a post then gets removed/blocked/left the squad. They should not receive notifications related to the Squad it came from. Removed from:
- Article new comment
- Comment new comment
- Article upvote milestone
- Comment upvote milestone.
- Post added notification
Let me know if I missed anything 🚢

refactor: stop sending notifications when user is not a member anymore

---

__tests__/posts.ts
src/entity/posts/utils.ts
src/schema/posts.ts

We now accept parameters for the title and image to use for the external link, but to support backwards compatibility, the said parameters are kept optional.

feat: submitting private link and be displayed real-time

---

__tests__/workers/cdc.ts
src/workers/cdc.ts

Don't send notifications when posting a link that is visible already (sync external link).

fix: stop sending notification on sync posting external links

---

__tests__/sources.ts
src/entity/Submission.ts
src/entity/User.ts
src/entity/posts/utils.ts
src/errors.ts
src/routes/private.ts
src/schema/sources.ts

With invite permission on squad there is a chance now that member shared a link on twitter or something and then after that admin restricted squad invites to moderators and above.
In that case since the link is out and we block the actual join request when it happens on our API.
Per comments here I refactored `errors.ts` to be `enum` instead of types https://github.com/dailydotdev/apps/pull/1761#discussion_r1173722616

feat: check permission when joining squad

---

__tests__/posts.ts
src/common/post.ts
src/schema/posts.ts

After discussing the list of links we have that produces no title or null values, it was mentioned that there is nothing that can be applied to fix it at the moment, so after checking with Product, we should continue returning our default title of `No title`.
Link to discussion: https://dailydotdev.slack.com/archives/C04UQUBDWKD/p1682418073810469
When the title is empty, we now return the default title we use since the scraper can return either `null` or an empty string.
Though when it returns an error, our mutation should still continue to return the proper error.

refactor: link preview to return default title when null or empty

---

__tests__/workers/cdc.ts
__tests__/workers/newNotificationMail.ts
__tests__/workers/notifications.ts
src/entity/Notification.ts
src/notifications/generate.ts
src/workers/cdc.ts
src/workers/newNotificationMail.ts
src/workers/notifications/postAdded.ts

**Blocked**: until [preview PR in FE](https://github.com/dailydotdev/apps/pull/1744) is merged.
Sync external link submission post-release removal of the post_live notification.

refactor: unnecessary live post notification

---

__tests__/workers/notifications.ts
src/workers/notifications/postAdded.ts

Until we do the retro check for those who have already subscribed, we don't want to show it to those who have existing subscriptions.
This also got me thinking after we do the retro checks for completed actions specifically the first post, should we also send a notification for those unsubscribed for PN yet?

refactor: temporarily disable subscribe to notification

---

__tests__/users.ts
src/schema/users.ts

Created a new query `generateUniqueUsername `, that takes the users name on signup and attempts to generate a username for them. It has 3 attempts to do so or it will exit without a suggestion. If the name of the user is already a username in the system, it will attempted 3 times to add a random string of numbers at the end to generate a unique username
WT-804 #done

feat: we should auto populate the usernames for auth onboarding

---

__tests__/posts.ts
src/schema/posts.ts

Without this mutation throws unexpected error when you just press save in the UI with the same post content since updated object is empty on the API side and typeorm does not like that.

fix: do not perform update if no post properties changed

---

__tests__/workers/notifications.ts
src/workers/notifications/postAdded.ts

If the post is a welcome post, we should not send a notification to users by returning early on the postAdded worker.

refactor: stop sending notification on welcome post to members

---

src/entity/posts/utils.ts
src/graphorm/graphorm.ts
src/graphorm/index.ts
src/migration/1684239736772-PinnedPost.ts
src/schema/comments.ts
src/schema/users.ts

Whenever we introduce a schema change to Post it required to replace the view which causes deadlocks. We introduce a new feature to GraphORM that simulates the view functionality.

refactor: stop using active post view

---

src/entity/FeedTag.ts
src/migration/1684512961790-FixFeedTagIndex.ts

It's a low hanging fruit that ideally will optimize the feed settings query. If not we will have to optimize the query as well

fix: add relevant index to feed tag to optimize query

---

__tests__/feeds.ts
src/graphorm/index.ts
src/schema/posts.ts

From the guideline, Freeform and Welcome posts should be allowed to return a null value as we should handle it in the FE rather than returning our placeholder images.

refactor: freeform and welcome post nullable image

---

__tests__/__snapshots__/feeds.ts.snap
__tests__/feeds.ts

The score value of the order by the score is the same, the query sometimes returns `p1` first over the other and vice-versa. Since they have the same score in terms of the actual issue, there should be no concern with regard to which one should come first or second.

fix: flaky test due to order

---

__tests__/posts.ts
src/common/markdown.ts

When providing code snippets if lang is not provided we didn't escape the html. This PR fixes it and also tries to automatically guess the language

fix: handle markdown injections

---

__tests__/workers/postUpdated.ts
src/cron/exportToTinybird.ts
src/workers/postUpdated.ts

* Set `showOnFeed` to true when order is missing
* Set `banned` to true when `showOnFeed` is false while exporting to tinybird

fix: showOnFeed madness

---

src/onesignal.ts
src/workers/addToMailingList.ts

When in development mode, some of the workers endless throw errors which throw logs that make it difficult to catch the right you are waiting for.
After further investigation, it was from integrations when you lack some API keys or secrets.

chore: prevent unnecessary logs on development

---

__tests__/boot.ts
src/routes/boot.ts

Expose referral properties from `join_referral` cookie in boot. Needed for https://github.com/dailydotdev/apps/pull/1853/commits/66ad21fb60b5c5f161d06117168d5d827429925e

feat(boot): expose referralId and referralOrigin

---

src/common/markdown.ts
src/common/slack.ts
src/common/twitter.ts
src/notifications/builder.ts
src/notifications/generate.ts
src/workers/postScoutMatchedSlack.ts

Searched through the codebase for any usage of the post title and applied a default value.

fix: nullable post title usages

---

__tests__/boot.ts
__tests__/posts.ts
src/graphorm/index.ts
src/routes/boot.ts
src/schema/posts.ts

Add `downvoted` property to gql post and boot to be used in companion.

feat: add downvoted property to gql post

---

__tests__/posts.ts
__tests__/workers/notifications.ts
src/migration/1686749310179-UpvoteTrigger.ts
src/migration/1686835784506-DownvoteTrigger.ts
src/schema/posts.ts

As per comments in the [DR](https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/544768013/Downvoting+and+reporting+posts#Other-notes) replacing inline increments with db triggers to avoid race conditions while upvoting and in the future downvoting.
Also added downvote triggers.
Also updated two tests that were right but expected wrong values due to test setup, see 4962c92f3eac11f3af9ab6e4ff06fe9f3ec5be33 commit message.
As additional note, in general we could apply this for comments too.

feat: add db triggers to handle upvotes count

---

__tests__/posts.ts
src/entity/PostReport.ts
src/migration/1687171948216-PostReportTags.ts

The array of strings for the `tags` column when reporting irrelevant tags.
The updates on the mutation will be included in a different PR.

refactor: post report entity tags column

---

__tests__/posts.ts
src/schema/posts.ts

Allow users to include the tags they think are irrelevant to the post.
When the reason is `IRRELEVANT` we must have at least one tag for it.

feat: include tags when reporting a post

---

__tests__/workers/cdc.ts
src/common/slack.ts
src/workers/cdc.ts

Added the newly added tags to the slack port report worker.
WT-1450 #done

fix: add tags to slack report post

---

src/schema/comments.ts

This was inspired by the existing mapping of our post report reasons. They already work as needed, so I thought of why not have the same process.

feat: report comment reason map

---

__tests__/posts.ts
src/schema/posts.ts

This surfaced now that we added downvote option.
If you already downvoted since downvote also calls `saveHiddenPost` the report after that would always silently fail since `saveHiddenPost` would return `false` as the `hidden_post` row existed.
FIx here returns `true` if post is already hidden and throws error in all other cases as it should be to notify frontend of any API errors.

fix: reporting hidden post not correctly writes report to database

---

src/common/cloudinary.ts
src/schema/posts.ts
src/schema/sources.ts

After further investigation, we will have to manually invalidate the cache for replacing an asset with the same name/public id.
Relevant sources:
https://support.cloudinary.com/hc/en-us/articles/202520852-I-ve-replaced-an-existing-asset-with-a-new-file-but-my-site-or-application-still-shows-the-old-asset-Why-is-that-
By default, invalidation is disabled (for good reasons), but we should invalidate in this case for replacing a thumbnail.
https://cloudinary.com/documentation/managing_assets#invalidating_cached_media_assets_on_the_cdn
Relevant API:
https://cloudinary.com/documentation/image_upload_api_reference#upload_optional_parameters
_Also just fixed some types while at it_

fix: invalidating cdn cache on cloudinary

---

src/schema/sources.ts

After checking, there was already a test for joining a public source and it works.
Though it seems the test was kind of a "false positive" due to the condition for fetching the member of `.findOneBy({ referralToken: token });`. Since the `token` was `undefined`, the query basically returns the very first row every time as it tells the condition to be none, hence, the `member` object always has a value.
Also, the refactor should reduce the number of queries to execute since we enclosed the condition to be checked only when it is for a private source.
The existing test:
https://github.com/dailydotdev/daily-api/blob/c2b0ac4d435295e51e431bde855f849f21a11fa8/__tests__/sources.ts#L1887-L1897

fix: join public source

---

__tests__/sources.ts
src/graphorm/index.ts

While working on new squad create and edit pages I noticed `public` was always `true`.

fix: public property now correctly calculated from private

---

__tests__/boot.ts
src/config.ts
src/redis.ts
src/routes/boot.ts

We now generate the `firstVisit` and turned it into a number to make it easier to consume at the frontend.
Note: we might need another value in the cache in the future relating to the user, should we probably store an object instead (with `firstVisit` as its property) so that we will only have to fetch once whenever we introduce new properties instead of touching the cache twice? Thoughts?

feat: first visit in cache

---

src/schema/comments.ts
src/schema/posts.ts

When the error is not about duplicated entries, we should throw an error.

refactor: throwing of error when unable to save to db

---

.gitignore

Just noticed that `coverage` is not in our `.gitignore` so if running tests locally with `--coverage` you get a bunch of files in your git changes.

chore: add coverage directory to gitignore

---

src/schema/sources.ts

Moved the sources query (unused for now) to graphORM paginated query to support the custom types we have there.
The one we needed was `membersCount` it also is more inline with our existing queries.

fix: move to graphORM query for support

---

__tests__/boot.ts
src/featureFlags.ts
src/routes/boot.ts

To make it easier to identify if the user is valid for v2 or not, we calculate the dates on the API instead of FE to avoid any discrepancy.

feat: identify pre onboarding v2 users

---

.infra/application.properties
.infra/index.ts
.infra/package-lock.json
.infra/package.json
src/workers/cdc.ts

During debezium upgrade to 2.0 we encountered a lot of snapshot messages with `op=r` property. 
This ensures those messages are ignored and not sent to pubsub and cdc worker.
Before merging this we need to test out locally that debezium 2.0 starts-up ok and that this fix really handles all the excess messages.

feat: filter read messages in cdc

---

__tests__/dataLoaderService.ts
__tests__/helpers.ts
__tests__/sources.ts
package-lock.json
package.json
src/Context.ts
src/dataLoaderService.ts
src/schema/sources.ts

Adding new `referralUrl` field to source to be used on frontend for invite links. Supports public and private squads.
Added in request caching with [dataloader](https://github.com/graphql/dataloader). 
Idea was to also create a generic service `DataLoaderService` that we can extend with additional loaders to provide in request caching capabilities. 
What does this enable: we can batch a lot of same database calls, 3party services calls and any promise to be batched and fetched only once in request context.
Example here is that we cache calls to our URL shortening service to avoid repeated calls while resolving multiple sources.

feat: add referralUrl field to source

---

__tests__/comments.ts
__tests__/feeds.ts
__tests__/posts.ts
__tests__/sources.ts
src/schema/posts.ts
src/schema/sources.ts

Restricting access to post and squad pages for public sources (squads).
Blocked user of open squad should not be able to:
- view squad page
- view squad posts
- comment on squad posts
Discussion [here](https://dailydotdev.slack.com/archives/C0592NL7YCU/p1689770365788359)

feat: restrict open squad content for blocked members

---

__tests__/notifications/index.ts
__tests__/workers/notifications.ts
src/notifications/common.ts
src/workers/notifications/commentReply.ts
src/workers/notifications/postAdded.ts
src/workers/notifications/squadMemberJoined.ts
src/workers/notifications/utils.ts

Skip notifications based on notification types as below:
- `comment_reply`
- `squad_reply`
- `squad_member_joined`
- `squad_post_added`
- `article_new_comment`
~~WIP: still waiting on a response from the threads below but already went ahead and fixed the assumptions but this PR should be complete already.~~
Threads:
- ~~https://dailydotdev.slack.com/archives/C02E2C3C13R/p1689776730496559~~
- ~~https://dailydotdev.slack.com/archives/C0592NL7YCU/p1689778547622899~~ (answered)
Note: will update this PRs description based on the response.

feat: skipping muted notifications

---

__tests__/posts.ts
src/directive/auth.ts
src/schema/posts.ts

Added a manual evaluation if field type is a `GraphQLScalarType` in which case we should simply return a null value.
Otherwise we can always throw forbidden error as it will be a query or mutation.
WT-1551 #done

fix: return null is auth on scalar value

---

src/schema/notifications.ts

In order for us to show the current preference of the user towards the said notification type, we need to fetch it first and the reference id is one of the requirements to do so.

fix: missing property on notification type

---

__tests__/notifications.ts
src/notifications/common.ts

after further development, I noticed that even though we strictly set the proper `type` of the `NotificationPreference`, it is getting overridden by what was defined in the class. Using the base class results in always setting it to `NotificationPreference` string as shown below. I have pushed a commit to fix this and ended up with a switch case, I tried doing a map of the class but wasn't working.

fix: correct notification preference type

---

src/notifications/generate.ts

- Refactored terminology from `article` to `post`
- Applied other minor semantical copy changes

fix: brush up notifications micro copy

---

.infra/Pulumi.adhoc.yaml

`NODE_ENV` was undefined in our local environment for daily-api
Since most developers would assume it should be defined we inject it as `development` for our local setup.
This fixes some edge cases in development like send email infinite loop https://github.com/dailydotdev/daily-api/pull/1302 which was fixed but the fix did not work anymore since our `NODE_ENV` was `undefined`.

feat: set NODE_ENV to development for local env

---

__tests__/sources.ts
src/schema/sources.ts

When editing the Squad's details, we always check to restrict using `DisallowedHandle`, though the transaction should not necessarily want to change the handle, the FE sends the content of the form anyway, and we should check if there was really any change with it.

fix: editing squad details should ignore unchanged handle

---

__tests__/notifications.ts
src/schema/notifications.ts

Similar to the PR for muting notification types relating to `article_new_comment` (https://github.com/dailydotdev/daily-api/pull/1374) - we should also update the query counterpart and the clearing of notifications.
Note: I will also raise a PR to make the FE work with the new requirements.

fix: notification preference query on post related types

---

__tests__/workers/__snapshots__/postUpdated.ts.snap
__tests__/workers/postUpdated.ts
src/entity/posts/Post.ts
src/migration/1690963996461-PostYggdrasilId.ts
src/workers/postUpdated.ts

We decided to add the Yggdrasil id to the post API.
For now it can simply be set, no need to expose it anywhere.

fix: add yggdrasil id to content flow

---

__tests__/boot.ts
src/routes/boot.ts

Decided to simply set the value, which in turn will reset the TTL.
Also added dedicated test case to ensure TTL get's reset.
Tested locally as well by comparing TTL on redis pool.
WT-1655 #done

fix: extend redis cache on each visit

---

__tests__/posts.ts
src/entity/UserPost.ts
src/entity/index.ts
src/graphorm/index.ts
src/migration/1691668733329-UserPost.ts
src/schema/posts.ts

feat: add user post table and mutations

---

.infra/Pulumi.adhoc.yaml
src/index.ts

Add env to control log level of the app. Useful in development when debugging events for `/e` endpoint.
Falls back to `info` if not defined per [docs](https://github.com/fastify/fastify/blob/main/docs/Reference/Logging.md#enable-logging).

feat: set log level through LOG_LEVEL env

---

__tests__/__snapshots__/feeds.ts.snap
__tests__/feeds.ts
__tests__/personalizedFeed.ts
src/personalizedFeed.ts

Changed the final feed version to be mapped to feed_config_name.
Supporting only the two names at the moment.
I decided to keep the internal based on version, not sure that was intended behaviour?
WT-1661 #done

fix: add feed config names

---

bin/copyUserPostHiddenData.ts
bin/copyUserPostVoteData.ts
bin/syncUserPostData.ts

- we chunk inserts per createdAt
- hidden post chunking is done with limit/offset because it does not have `createdAt`
Migration is split into two scripts due to different chunking options as noted above. Did not want to complicate further.

feat: copy user post data from old to new table

---

__tests__/feeds.ts
__tests__/integrations/feed.ts
src/integrations/feed/generators.ts
src/integrations/feed/index.ts
src/schema/feeds.ts

New query to allow me experiment with different feed configs. This is enabled only in the private api mode so it shouldn't leak to users and cannot be abused.

feat: feed by config query

---

src/schema/posts.ts

Previous query took 5 recent upvotes without checking whether there are any questions related to these posts. I added a check to make sure we always return search recs when possible.

fix: always return search recs when possible

---

src/schema/posts.ts

Remove sub query to improve performance. Can introduce a case where some users will not get questions.

fix: remove sub query to improve performance

---

__tests__/posts.ts
src/config.ts
src/redis.ts
src/schema/posts.ts

Added a redis 3 minute cache for search rec.
Note: It could introduce edge-cases as we json stringify the graphORM data.
Basically means if we ever change the format of selection in the query we should invalidate/renew a key version.
WT-1816 #done

fix: cache search rec

---

src/common/cloudinary.ts
src/schema/posts.ts
src/schema/sources.ts

Changing the URL will force image invalidation on all fronts, service worker, cdn, browser cache, etc.

fix: force cloudinary to add version in the url of the image

---

__tests__/boot.ts
src/routes/boot.ts

Companion was missing `userState.vote` to be able to use new vote state. In scope of changes for engagement loop.
https://github.com/dailydotdev/apps/pull/2164

feat: add userState.vote for companion boot

---

__tests__/boot.ts
src/entity/Feature.ts
src/routes/boot.ts

To reduce growthbook payload size we have to use user attributes. This will allow us to move from defining hard coded user ids on GB to having them on our database. Hence, it will reduce significantly the payload.
NOTE: Requires apps changes but not blocking this PR

feat: provide user attributes as part of boot

---

__tests__/workers/postUpdated.ts
src/workers/postUpdated.ts

We needed to distinguish between content_type => post_type mapping.
Basically the old flow was only working for ArticlePost.
Also modified test cases to ensure non existing fields don't throw errors.
Note:
Currently only works for ArticlePost and FreeformPost (expected, but good to note)

fix: test case and update type based on content type

---

__tests__/workers/postUpdated.ts
src/entity/posts/FreeformPost.ts
src/workers/postUpdated.ts

The specs mention we needed to set summary as well as some other fields, which where not available on freeform post.
I added the ones we set in the specs (removed `toc` as it seemed pointless)
Also made the test a bit more concrete to what could happen, and added discussed test for welcome post.

fix: add missing fields to freeform content type

---

__tests__/boot.ts
src/featureFlags.ts
src/routes/boot.ts

Since everything is going through the GB flags now, we don't have to pull internal flags anymore for better performance.

refactor: internal feature flags to be hard coded

---

__tests__/integrations.ts
package-lock.json
package.json

We still have the legacy faker that would introduce a breaking update.
Decided to update to the successor package.

fix: remove broken faker version

---

package-lock.json
package.json

We had a spool of deprecated function messages on API.
Basically due to not updating all Fastify packages.

fix: fastify dependency issues

---

__tests__/boot.ts
src/entity/Feature.ts
src/migration/1695795022369-FeatureValue.ts
src/routes/boot.ts

Added option to allow values for features.
This way we can negative value people who shouldn't have access.
@idoshamun Let me know if this will work.
According to my plan we'll have to introduce a new evaluation saying if search = 1 show v1, if search = -1 show control.
But keep the `true` evaluation as well.

fix: added feature value option

---

.env
__tests__/boot.ts
src/auth.ts
src/routes/boot.ts

To reduce the load on heimdall side, we'll call the whoami only when we actually must. This should also optimize subsequent calls to boot in the same session.

refactor: send whoami calls only when jwt is about to expire or not available

---

.infra/workers.ts

Fixing [issue](https://console.cloud.google.com/monitoring/alerting/incidents/0.n32v3rv1s754?project=devkit-prod), subscription for enrolling into personalized digest was active but worker is not yet until we finish initial experiment.

fix: disable subscription for now since worker is not active

---

src/common/links.ts
src/common/post.ts
src/integrations/analytics.ts
src/integrations/feed/clients.ts
src/integrations/magni.ts
src/integrations/retry.ts
src/integrations/snotra/clients.ts
src/kratos.ts
src/routes/devcards.ts

I refactor our `retryFetch` function to support more generic use cases so we'll be able to apply system-wide. It's best practice to use retries and now that we know our retry library don't introduce issues we can actually apply it :P

refactor: streamline retryFetch and convert most usage to retry

---

package-lock.json
package.json
src/cron/personalizedDigest.ts

We found an issue where async method `notifyGeneratePersonalizedDigest` does not get to be resolved before the stream ends and the instance that is running a cron destroys itself. 
Utlizes async queue to manage notify tasks and awaits for queue to be drained (completed) before exiting.

feat: utlize async queue to wait for pending notify calls

---

__tests__/cron/personalizedDigest.ts
__tests__/helpers.ts
__tests__/workers/personalizedDigestEmail.ts
src/common/pubsub.ts
src/cron/personalizedDigest.ts
src/workers/personalizedDigestEmail.ts

Based on the thread [here](https://dailydotdev.slack.com/archives/C05G8BHHVBR/p1696840091899069?thread_ts=1696581507.796259&cid=C05G8BHHVBR) I added `generationTimestamp`. 
That timestamp can be used to set timestamp for time of generation of digest message and allow us to forward/backward between actual sending days without a need to wait for cron. 
It can also be useful if for any reason digest fails to send we can just provide `generationTimestamp` for previous day and digest will process like it's that day. We would still need to watch out for people timezones but at least it gives us flexibility to do it.
It will also help us with initial testing.

feat: add generationTimestamp for digest worker

---

package-lock.json
package.json

As it was a breaking change version I wanted to test it separate from the minor bumps.
Explicit tests on the rate limiter work as intended.
Note:
We actually didn't use and of the [breaking changes](https://github.com/animir/node-rate-limiter-flexible/releases/tag/v3.0.0) luckily.

chore: bump rate limiter to new version

---

__tests__/__snapshots__/users.ts.snap
__tests__/private.ts
__tests__/sources.ts
__tests__/users.ts
src/common/handles.ts
src/common/object.ts
src/entity/User.ts
src/routes/private.ts
src/schema/sources.ts
src/schema/users.ts

Enforce the same rules on user and squad handles.
The rules:
* Transform to lowercase
* No forbidden handles
* Uses alphanumeric, underscore or dash
* No dups
The rules are enforced only when updating the handle or creating a new entity. We want to make sure users who update something else will not suddenly get an error.
WT-744 #done

refactor: streamline handles throughout the app

---

__tests__/workers/personalizedDigestEmail.ts
src/workers/personalizedDigestEmail.ts

name can not be null, so defaulting to use the set `userName` object.

fix: name can not be null

---

src/workers/commentUpvoteCanceledRep.ts

We have this failsafe in the upvote, but not upvote cancel.
This just makes it inline and avoid a [error](https://console.cloud.google.com/errors/detail/CLHxl67d54W9_wE;service=api-bg?project=devkit-prod).

fix: failsafe as we use for the upvote comment itself already

---

__tests__/feeds.ts
src/entity/Keyword.ts
src/integrations/feed/generators.ts
src/migration/1698230451545-OnboardingTagsIndex.ts

Basically in my testing I figured that due to caching key for cached feed client is per user id and generator identifier user will always get the same feed for cache duration which we don't want.
Using regular feed client user will always get fresh feed. It should not be expensive since onboarding generator generates only one page with 20 feed items.
Also added missing index for onboardingTags because I noticed query takes on average around a 1-2 seconds, probably due to amount of rows. Index should fix it.

feat: make preview feed always fresh

---

__tests__/workers/__snapshots__/personalizedDigestEmail.ts.snap
src/entity/Keyword.ts
src/migration/1698323453474-OnboardingTagsTextIndex.ts
src/schema/tags.ts

After deployment of https://github.com/dailydotdev/daily-api/pull/1504 I noticed that onboarding tags were still slow. 
After further debugging I found out why the query is slow. It was not due to index (I mean they help) but the main culprit is how typeorm assembles the query when you use json fields, I logged it under the hood and the query is something like:
```sql
SELECT value FROM keyword WHERE flags = '{ "onboarding": true }' ORDER BY value ASC
```
With the above query we don't actually hit the index since query queries the whole flags field. Optimal query (and what I was expecting `typeorm` was doing) would be:
```sql
SELECT value FROM keyword WHERE (flags->'onboarding') = 'true' ORDER BY value ASC
```
After replacing inefficient query from `typeorm` with the raw one it actually …

feat: use text instead of boolean cast index

---

__tests__/tags.ts
src/schema/tags.ts

To prevent many search results being returned with too general of a query.

feat: limit search results to 100 and min query to 2 chars

---

src/ids.ts
src/integrations/analytics.ts
src/kratos.ts
src/routes/boot.ts
src/tracking.ts

Add metric to measure how many times we generate a tracking id. This is part of an ongoing effort to fix issues in our authentication.

chore: measure tracking id generation

---

__tests__/private.ts
src/entity/User.ts
src/ids.ts
src/kratos.ts
src/routes/private.ts
src/tracking.ts

Due to legacy reasons we generate user id upon first visit and this can cause quite a lot of issues. One of them is id clashes on sign up. This PR handles the id clashes and retries several times before giving up. I also refactored a bit to make it look better 😬
It's not ready to be merged yet as I wait for an heimdall change that will be deployed tomorrow hopefully.

fix: id conflicts when signing up

---

__tests__/alerts.ts
__tests__/boot.ts
__tests__/workers/cdc.ts
src/entity/Alerts.ts
src/migration/1698838065767-AlertsFlags.ts
src/routes/alerts.ts
src/routes/boot.ts
src/schema/alerts.ts

Added new alerts columns as described in [DR](https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/659161109/Referral+program+and+profile+UX+improvements#Persistent-data-for-referral-reminder).
had to adjust from Date as it's not supported in JSONB, decided to go for bigint to avoid y2k issues down the line (2038)
WT-1921 #done

fix: add new alerts columns

---

__tests__/users.ts
__tests__/workers/cdc.ts
src/entity/User.ts
src/graphorm/index.ts
src/schema/users.ts

Fetch all the users that have been referred by the login user.
From the entity itself, the `createdAt` is not nullable, hence, updated the types.
Made the `createdAt` to be always required as it is part of the query for fetching the list which does not necessarily need to be displayed in FE.

feat: referred users query

---

__tests__/workers/__snapshots__/personalizedDigestEmail.ts.snap
src/common/mailing.ts

Sendgrid logs warning whenever it detects template data contains some special chars, we don't want it in production since it spams our logs and makes hard to see any other errors.
See: https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/hide-warnings.md

feat: disable sendgrid warnings in production

---

src/schema/trace.ts

Currently the query `TagCategories` is according to the metrics the most requested query, however it turns out if a `Query` contains multiple sub queries, just like `TagCategories` does, it increments the counter for each sub query, therefore skewing the metrics to show that this query is the most requested. When in reality it should have 1/3 of the amount of requests it currently have.
Before
```
graphql_operations_total{graphql_operation_name="TagCategories",graphql_operation_type="query"} 3
```
After
```promql
graphql_operations_total{graphql_fieldName="tagsCategories",graphql_operation_name="TagCategories",graphql_operation_type="query"} 1
graphql_operations_total{graphql_fieldName="feedSettings",graphql_operation_name="TagCategories",graphql_operation_type="query"} 1 …
```

fix: increase cardinality for GraphQL metrics

---

src/workers/personalizedDigestEmail.ts

Currently for each user that does not get any recommendations for the digest the worker writes two log entries:
Second one contains user id and feed config that was requested so it allows us to debug those when we want. 
First one I am removing in this PR since it is a duplicate and contains digest subscription data which is not relevant in that case.

chore: remove additional logging from digest worker

---

src/common/links.ts
src/common/mailing.ts
src/schema/users.ts

Ensure new parsed people get their referral link added to the new custom field in Sendgrid.
Next step is to do a batch CSV to insert all existing users with this field set.
WT-1978 #done

fix: add referral link to sendgrid users

---

__tests__/posts.ts

Since it is explicitly defined which types should only be edited, we just need to add a test to ensure collection type of post should never be allowed.
WT-1960 #done

test: collections should not be editable

---

__tests__/workers/sourceSquadCreatedOwnerMailing.ts
src/common/mailing.ts
src/workers/sourceSquadCreatedOwnerMailing.ts

Add shortened URL for sendgrid.
WT-1980
@idoshamun We only need to worry about the data loader in graphQL requests? (thus can omit like in this PR?)

fix: shortened URL for referral

---

.infra/crons.ts

The count of users with `false` for `showGenericReferral` is 77k. If it goes down, it means the cron has updated users mistakenly since everyone has either the `true` value of the said property or has seen it.
Again, thank you to @rebelchris for running the scripts on a day-to-day basis 🥳 
Note: kindly ignore the changes on other lines, made by prettier automatically.

chore: enable cron for referral reminder

---

src/graphorm/index.ts
src/schema/posts.ts

We need updated at value to show in collections post page. `metadataUpdatedAt` is `updated_at` from platform so it should suffice and we can always adjust it with other field thus i called it `updatedAt` generically.

feat: add updatedAt field for post

---

src/schema/posts.ts

Basically this enables following case when post does not have an image, until this point it returned a placeholder.

feat: collection post type can have state without image

---

__tests__/__snapshots__/feeds.ts.snap
__tests__/feeds.ts

Our feed has been configured to support working with advanced settings, this means any additional item in that table would automatically be considered working as soon as it hits production.
With that, I just modified the test to return what is expected rather than the snapshot just to make it easier to understand.
The fixture saved below would make some sources have certain advanced settings IDs, namely `1` and `4`. Then those Sources IDs are found from `excludedSource` and `settingsCombinationSource` as seen from the code.
https://github.com/dailydotdev/daily-api/blob/7b6fb970a07f821629a0da2a46b9e9dc15f17cde/__tests__/feeds.ts#L166-L179

test: sources are excluded

---

.infra/workers.ts
__tests__/workers/notifications/collectionUpdated.ts
src/common/pubsub.ts
src/graphorm/index.ts
src/notifications/generate.ts
src/schema/notifications.ts
src/workers/notifications/index.ts

Integration fixes found when connecting on frontend and e2e testing:
- missing worker subscription
- missing worker registration in export
- notification icon and template
- notification unique key, using `metadataUpdatedAt` because without it `ID_notification_uniqueness` would fail and any notification after first one would not save to DB thus any collection updated after first one would be missed
- expose `numTotalAvatars` field for frontend

fix: collection notification integration

---

__tests__/triggers/notifications.ts
src/migration/1702224104423-NotificationV2Triggers.ts

Prerequisite for: https://github.com/dailydotdev/daily-api/pull/1572
New triggers to update avatars when needed and delete relevant notifications.
I don't delete avatars and attachments, I feel like after the optimization the hassle doesn't worth it. I will have to index these fields in the notifications table and update the array too much effort for too little value.

feat: notification v2 triggers

---

__tests__/workers/postUpdated.ts
src/workers/postUpdated.ts

When we share a YouTube link in a Squad, it is saved as an `article`. So we need to update it to `video:youtube` when we get the updated data from Yggdrasil.

fix: update the post type on youtube video when we get it from Yggdrasil

---

src/common/slack.ts
src/workers/postScoutMatchedSlack.ts

Add fallback to show post id when title is not present for slack messages.
This way you can click on something in slack.
WT-2024 #done

fix: slack link title fallback

---

__tests__/notifications/notificationWorkerToWorker.ts
src/notifications/index.ts

Hotfix to ignore duplicate notifications, unless unique key is not set. In this case I'd like to get an alert to check manually if it's a bug.

fix: handle duplicate notifications

---

src/common/pubsub.ts
src/workers/cdc.ts

Add email prop as we need it in our API `user-deleted-api-mailing` worker.
I didn't want to be to intrusive to add the whole change object for now.
WT-2016
Do note: This meant for whenever this change was made deleted users have not been unsubscribed in sendgrid.

fix: add email so deleted users get unsubscribed in sendgrid

---

__tests__/notifications.ts
src/graphorm/index.ts

Thanks to Ole-Martin for hunting this one. This fixes the issue of not reading properly the `readAt` field

fix: notification v2 select readAt properly

---

__tests__/workers/postUpdated.ts
src/workers/postUpdated.ts

If a video have no captions, Yggdrasil is not able to generate keywords in `keyword` field, so we can fallback to `keywords_native`.

fix: fallback to `keywords_native` on video post if no keywords are given

---

__tests__/workers/postUpdated.ts
src/workers/postUpdated.ts

We expect the readTime to be minutes, but duration is seconds, so we need to divide by 60.

fix: divide video duration by 60 to get minutes

---

__tests__/cron/personalizedDigest.ts
__tests__/helpers.ts
pull.ts
src/background.ts
src/commands/personalizedDigest.ts
src/cron.ts
src/index.ts

This lets Google Cloud Logs Explorer to automagically show the log message instead of the entire payload
Docs: https://getpino.io/#/docs/api?id=messagekey-string

feat: change the message key from `msg` to `message`

---

__tests__/feeds.ts
__tests__/integrations/feed.ts
src/integrations/feed/configs.ts
src/integrations/feed/generators.ts
src/integrations/feed/types.ts
src/schema/feeds.ts

Feed service supports now returning similar posts which is way better than our current implementation. Not all posts support that, hence I'm keeping the old implementation as well for now.

feat: fetch similar posts from feed service

---

__tests__/workers/postUpdated.ts
src/workers/postUpdated.ts

Solves [thread](https://dailydotdev.slack.com/archives/C0601MRBJJU/p1702556332306539?thread_ts=1701787711.730699&cid=C0601MRBJJU)
Yggdrasil is unaware of api post id.

feat: resolve post id from yggdrasil id when post id is missing

---

src/workers/postUpdated.ts

It should not happen but just additional guard since there could be null values for `yggdrasilId` in db.

feat: make sure yggdrasil id is available to avoid null queries

---

__tests__/workers/postUpdated.ts
src/entity/posts/utils.ts
src/workers/postUpdated.ts

Basically a bug when post was already visible the condition was flipped with becomes visible. Everything else logic wise looks fine and platform DOES send whole payload during updates. 
Requirements for post visible updates:
- visible is once off, once post is visible it can't become invisible
- post becomes visible if it has the title
- post visibleAt is updated when post becomes visible (default null during creation)

fix: do not flip visible condition when post is already visible

---

.infra/application.properties
.infra/workers.ts
__tests__/workers/cdc/notifications.ts
__tests__/workers/cdc/primary.ts
pull.ts
src/workers/cdc/common.ts
src/workers/cdc/notifications.ts
src/workers/cdc/primary.ts
src/workers/index.ts

To overcome the ordering constraint of CDC, we separate the notifications to a new topic to allow much faster handling with spikes
WT-2048 #done

refactor: split notifications to a new cdc handler

---

__tests__/workers/notifications/collectionUpdated.ts
src/workers/notifications/collectionUpdated.ts

Ensure notifications work when sources are still empty (edge-case)
Summary could still be updated based on the main collection.

fix: handle empty sources for collection update

---

src/entity/Keyword.ts
src/entity/PostKeyword.ts
src/entity/Source.ts
src/entity/SourceMember.ts
src/entity/UserPost.ts
src/entity/posts/Post.ts
src/migration/1703422184359-AdditionalMissingIndexes.ts

According to [everSQL](https://www.eversql.com/sql-query-optimizer/?code=fb8424a3-d3fc-4a6e-9ae8-414754aaf52b#/) we missed the following to optimal indexes.
And [this](https://www.eversql.com/sql-query-optimizer/?code=fb8424a3-d3fc-4a6e-9ae8-414754aaf52b#/) one:
And [this](https://www.eversql.com/sql-query-optimizer/?code=fb8424a3-d3fc-4a6e-9ae8-414754aaf52b#/) one:
This should help improving a very slow query we had.

fix: we missed two indexes according to everSQL

---

__tests__/sources.ts
src/schema/sources.ts

New query to receive all the public squads the given user is part of.
This query doesn't require authentication.

feat: public source memberships query

---

src/schema/feeds.ts

I used twice the `userId` param with different values and it caused the wrong output

fix: query params mismatch

---

__tests__/helpers.ts
__tests__/workers/cdc/primary.ts
__tests__/workers/sourceRequestApproved.ts
src/background.ts
src/common/index.ts
src/common/pubsub.ts
src/common/typedPubsub.ts
src/workers/cdc/primary.ts
src/workers/index.ts
src/workers/sourceRequestApprovedRep.ts
src/workers/worker.ts

**This PR is a proposal nothing that should go to production at the moment.**
The main goal is to ensure type safety when using pubsub both on the publisher and consumer side and keep them consistent.
My approach uses a centralized schema type that is enforced by a single function for sending events (`triggerTypedEvent`) and on the worker side by a new `TypedWorker` interface. The DX is significantly improved as you get auto complete and validation for topic names and payload as long as we have the schema up to date.
In this PR, I migrated some topics and a single worker to show how we can make it work if we agree on this approach. I wanted to demo how it's gonna look before suggesting an action plan so if you don't like it at all, say it explicitly.

refactor: type safety pubsub implementation

---

__tests__/workers/cdc/primary.ts
__tests__/workers/newNotificationV2Mail.ts
__tests__/workers/notifications/collectionUpdated.ts
src/entity/posts/utils.ts
src/notifications/generate.ts
src/notifications/types.ts
src/workers/notifications/collectionUpdated.ts

Previously we ensured sources where distinct de-duplicated, however according to new insights we should allow all sources including duplicates.
Secondary effort for this task will be to run a query to update existing post-relations and once-off update the `collectionSources` to reflect this change. (My suggestion is a query, but please let me know if you have different ideas)

fix: sources should not be deduplicated

---

__tests__/cron/cleanZombieUsers.ts
__tests__/private.ts
src/migration/1704948666033-GhostUserProtect.ts

As discovered while debugging deletion of users, I noticed that the 404 / ghost user had disappeared.
So this migration creates a rule to prevent `DELETE` and `UPDATE` of the row.

fix: create rules for protecting the ghost user from accidental deletion or modification

---

__tests__/workers/updateMailingList.ts
src/common/utils.ts
src/workers/updateMailingList.ts

This fixes a long hanging unacked pubsub message on the `user-updated-api-mailing` subscription because we had to re-add the ghost user to the database.

fix: do nothing in `updateMailingList` if user is ghost user

---

__tests__/feeds.ts
src/integrations/feed/configs.ts

Since we no longer cache locally the feed, we need to limit the total pages to 1 not 40 :P

fix: hotfix too many posts returned from feed

---

src/schema/feeds.ts

Remove the post_similarity GB enrolment as it seemed to work fine now.
Kept the GB function as we might need it later again.

fix: remove GB rollout catch

---

__tests__/triggers/post.ts
src/entity/posts/SharePost.ts
src/migration/1706363895498-SharePostTrigger.ts

Introduce new triggers to keep SharePost tagsStr up-to-date with the tags of the shared post itself.

feat: share post tags trigger

---

__tests__/users.ts
src/graphorm/index.ts
src/schema/users.ts

Introduce a new query to fetch the user's reading streak.
Note: this PR is purely retrieval. The additional logic that resets the user's current streak based on some checks will be for a different ticket/PR.
MI-72 #done

feat: get user streak

---

src/graphorm/index.ts
src/index.ts

After checking we actually set the FE limit to 5MB:
```
export const imageSizeLimitMB = 5;
```
So decided to set this one to match so we will catch it on both sides correctly.

fix: set upload limit to match FE limit

---

__tests__/workers/cdc/primary.ts
src/common/pubsub.ts
src/entity/posts/FreeformPost.ts
src/workers/cdc/primary.ts

Reduces the amount required amount of characters for triggered content requested on freeform.

fix: reduce the freeform minimum content length to 50 chars

---

__tests__/workers/newView.ts
src/workers/newView.ts

Fixes bad return value if we create the reading streak record from the newView worker.
Fixes trying to write data without having the userId on the message.
More details in slack: https://dailydotdev.slack.com/archives/C05TQL6HWTH/p1706694707591509?thread_ts=1706621305.668089&cid=C05TQL6HWTH

fix: return value for incrementing reading streaks

---

src/schema/search.ts

Based on the [discussion](https://dailydotdev.slack.com/archives/C063RS0QZTM/p1706698311092559) adding support to return post id for search suggestions. This will allow to open the suggested post directly from search panel suggestions vs searching and then clicking the card.

feat: return post id for search suggestion hit

---

__tests__/workers/newView.ts
src/workers/newView.ts

On anonymous events, the newView worker receives a message with `userId`, but there is no such user with the userId. Our temporary code for inserting rows into the `user_streak` table when there is none didn't work correctly for such cases.
Rewritten to first get the user and only try to insert if the user exists.

fix: do not update reading streak for non-existing user

---

__tests__/triggers/post.ts
src/migration/1706779866978-SharedPostTriggerFix.ts

For some odd reason PG not equal operator doesn't care about null 😅
This means if a value was null and then changed it will not be captured by `<>`
#FML

fix: shared post trigger

---

.env
.infra/Pulumi.prod.yaml
__tests__/__snapshots__/feeds.ts.snap
__tests__/feeds.ts
src/integrations/feed/generators.ts

The popular feed configuration was broken for a while but the issue was surfaced when we introduced caching.
This PR fixes it and also includes blocking the tags and sources on this feed.

fix: popular feed

---

__tests__/users.ts
src/common/date.ts
src/common/users.ts
src/entity/user/UserStreak.ts
src/graphorm/index.ts
src/schema/users.ts

- Update the `userStreak` query to clear the user's `currentStreak` whenever applicable.
- The test cases have covered all the possible cases which involve weekends. Feel free to go through it.
MI-108 #done

refactor: query user streak - clear when possible

---

.eslintrc.js
package-lock.json
package.json

This way whenever you run `eslint --fix`, it will remove all of the unused imports.

chore: add eslint-plugin-unused-imports

---

__tests__/devcard.ts
src/routes/devcards.ts

The `Params` and `Querystring` are two different objects. The former is for required values and the latter is for optional, the type is for the latter.
Should fix (and verified locally) that the correct type is passed.

fix: object used for query params

---

__tests__/devcard.ts
src/routes/devcards.ts
src/schema/devcards.ts

- Removed the check from the REST API `/devcards/v2/` route that checks if the devcard exists. No 404 returned there anymore.
- Modified the logic, so that when we query a devcard with the graphql query, it is created if it not exists, instead of returning a 404.

fix: create devcard if not exists and remove 404 checks

---

src/common/devcard.ts
src/schema/devcards.ts

I noticed the query for sources is quite heavy so I reduced the logic a bit to make it easier on the db. DevCard is gonna be more popular now that it's shown on tooltip and everywhere essentially

refactor: reduce load from the devcard query

---

src/routes/devcards.ts

With the original code, we ended up with `https://app.daily.dev/devcards/v2/userId.png` instead of `https://app.daily.dev/api/devcards/v2/userId.png` in the end. The `/api` portion got swallowed somewhere on the way.
With this code, we point to `https://api.daily.dev/devcards/userId.png` instead.

fix: devcard svg embedded png url not correct in prod

---

package.json
src/routes/devcards.ts

Use `he` `encode` function to encode the png URL.
Also simplify the svg itself, since the [`xlink` namespace is not needed anymore](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href) and we can just use `href` attribute.

fix: encode embedded png url so that svg parser does not choke

---

src/errors.ts
src/workers/notifications/index.ts

There was a edge-case where the user constraint would fail if the user got deleted before subscription finishes.
We said to only listen to this specific constraint for now.

fix: user constraint fail fix

---

__tests__/alerts.ts
__tests__/common/fibonacci.ts
__tests__/workers/newView.ts
src/common/fibonacci.ts
src/common/users.ts
src/entity/Alerts.ts
src/migration/1708024370161-readingStreaksAlert.ts
src/routes/alerts.ts
src/schema/alerts.ts
src/schema/users.ts
src/workers/newView.ts

- Adds new `column` `showStreakMilestone` boolean in `alerts` table.
- Sets value in `newView` worker to `true` if currentStreak is a number from the fibonacci sequence.
- Fixed an issue where graphQL always returned `currentStreak` as 0, because we missed an `await` keyword on a promise.
- Added unit tests, so pretty sure this works. Maybe 🤞

feat: streak milestone alert computation

---

__tests__/redirector.ts
src/routes/index.ts
src/routes/redirector.ts

Set robots.txt to block all traffic, add noindex to redirector endpoints just in case

feat: block search from api.daily.dev

---

__tests__/sources.ts
src/schema/sources.ts

As mentioned in the Slack conversation, public Squads are more like sources now, which means it is less noisy than it was before.
With that, we are bringing back the default to notify members when a new post is added.
MI-148 #done

revert: post notification muted for public squads

---

__tests__/workers/personalizedDigestEmail.ts
src/integrations/analytics.ts
src/workers/personalizedDigestEmail.ts

See [discussion](https://dailydotdev.slack.com/archives/C05G8BHHVBR/p1709034207244029?thread_ts=1709018432.641809&cid=C05G8BHHVBR)
This basically failed our allocation events for digest due to schema validation not going through on analytics side.

fix: variation_id should be sent as string

---

__tests__/urlShortener.ts
src/graphql.ts
src/schema/urlShortener.ts

Adds a graphql query so that we can request shortened URLs from the frontend.
Related: 
- MI-188

feat: add graphql query for URL shortener

---

__tests__/workers/newView.ts
src/workers/newView.ts

We need to set `showStreakMilestone` to true when the user meets a new streak record as well.
Related issue: 
- MI-192
Related PR: 
- https://github.com/dailydotdev/apps/pull/2710

fix: set showStreakMilestone to true when currentStreak >= maxStreak

---

__tests__/users.ts
src/schema/users.ts

In the case the user does not have an entry in the database for their user streak, we just return an empty one.

fix: return 0 streak when there is no record in the database

---

src/graphorm/graphorm.ts
src/schema/users.ts

We don't have a `queryOne` function that doesn't fail. Added a new one that returns `null` instead.
https://github.com/dailydotdev/daily-api/pull/1727#discussion_r1508707129

feat: add `queryOne` without fail to graphorm

---

.circleci/config.yml

CircleCI removed some runner images that this orb was using. Version `0.16.2` updated it to be latest runner image
https://github.com/CircleCI-Public/gcp-gcr-orb/pull/80

chore: update gcp orb

---

__tests__/workers/newView.ts
src/workers/newView.ts

Alternative approach to 
- https://github.com/dailydotdev/daily-api/pull/1729
Here we update the SQL query to return if the streak was incremented or not and based on that continue setting the alert value if needed.
Doing it via DB logic avoids the problem with timezones.

fix: don't trigger alerts multiple times on the same day

---

__tests__/workers/__snapshots__/personalizedDigestEmail.ts.snap
__tests__/workers/personalizedDigestEmail.ts
src/common/personalizedDigest.ts
src/workers/personalizedDigestEmail.ts

This ticket just adds the properties, to actually display them in the digest we need to update the template in sendgrid. 
Todo:

feat: include user streak related attributes in personalized digest

---

__tests__/notifications/index.ts
__tests__/triggers/feedSource.ts
__tests__/workers/notifications.ts
src/migration/1709739543179-FeedSourceBlockUnsubscribe.ts
src/notifications/common.ts
src/notifications/generate.ts
src/workers/newNotificationV2Mail.ts
src/workers/notifications/postAdded.ts

AS-154
- add new notification type
- allow it for frontend subscribe
- update `postAdded` worker to notify for `machine` sources
- tested notification dispatch locally
- added trigger to unsubscribe user when he blocks a source automatically so we don't have to run requests from frontend, also added [automatic cache invalidation on frontend](https://github.com/dailydotdev/apps/pull/2750/commits/3c7d32fbeb4a69bb076345a4161b8096bd47bfd4)

feat: add new source post added notification type and notify logic

---

src/schema/feeds.ts

Previously we added this guard as we thought it fixes a performance issue, but actually Ole-Martin fixed the root cause. Now we can have it on for everyone

fix: allow anonymous users to use the new similar posts

---

__tests__/integrations/feed.ts
src/integrations/feed/configs.ts
src/integrations/snotra/types.ts

Downstream the personalization threshold based on the feed version to snotra.
Currently, there's no real change just support for future experiments.

feat: support personalization threshold experiment

---

src/common/users.ts
src/kratos.ts
src/routes/users.ts

With the surge in new users, it would be interesting to see how many of them deletes their accounts.
Saw a surge of manual logouts in the metrics, but it doesn't differentiate between actual logout or deletion of the user.
This adds a new reason, `deletion logout`, to the counter

feat: add separate meter reason for deleted users

---

src/graphorm/index.ts
src/schema/comments.ts

Added a comment feed endpoint.
Rules set are: 
- No welcome post
- Only people with over 10 reputation
Not the biggest fan of the 3 joins, but for now it should be ok to experiment quickly with.
Also needed to add the parent context since we want to showcase if you replied to set person.
AS-202

fix: additional feed for all comments with context

---

__tests__/workers/__snapshots__/personalizedDigestEmail.ts.snap
__tests__/workers/personalizedDigestEmail.ts
__tests__/workers/userCreatedPersonalizedDigestSendType.ts
src/common/personalizedDigest.ts
src/common/pubsub.ts
src/growthbook.ts
src/routes/index.ts
src/workers/personalizedDigestEmail.ts
src/workers/userCreatedPersonalizedDigestSendType.ts

Idea to [solve](https://dailydotdev.slack.com/archives/C06L6UB03U0/p1711028492991389), discussion and enable experimentation on both digest types.
Also request [here](https://dailydotdev.slack.com/archives/C06L6UB03U0/p1711097204217649?thread_ts=1711096239.730069&channel=C06L6UB03U0&message_ts=1711097204.217649)
- added new property `newUserSendType` to enrol new users to either send type (replaces current `personalized_digest_send_type` feature flag)
- weekly send type uses current personalized_digest config for weekly digest
- workdays send type uses new daily_personalized_digest config for daily digest

feat: replace send type feature with daily digest config

---

.infra/crons.ts
__tests__/cron/dailyDigest.ts
src/cron/dailyDigest.ts

With cron schedule it would leak for timezones with large offset where cron would not run or would run early while still in workday.
1. Friday 19:00 UTC is Saturday 04:00 Australia/Brisbane
2. cron runs since it is still Friday in UTC and schedules email
3. User gets the email on Saturday morning 08:00
Example [logs](https://cloudlogging.app.goo.gl/dx2J4ok7LddnAdgN6)
Same thing can happen for western timezones behind UTC but it would happen from Sunday->Monday where people would not get an email on Monday.
Checking in cron logic we can verify local time and skip send if it is a weekend.

fix: avoid sending daily digest on weekends

---

.circleci/config.yml

Use CircleCI to run tests in parallel to reduce the CI time

ci: split tests

---

__tests__/comments.ts
src/schema/comments.ts

- Removed check for same user when reading comment by ID. This is needed to show comment previews for mobile UX.
Related PR: 
- https://github.com/dailydotdev/apps/pull/2841

feat: allow reading comments by any user

---

src/telemetry/opentelemetry.ts

It is already counted in the graphql counter, so we don't really need it twice.

fix: ignore `/graphql` from requests counter

---

src/index.ts

In the meantime, we will remove caching of the `source` query to properly display user membership after joining/leaving.

fix: post-join-squad stale state of the source query

---

src/schema/trace.ts

This removes the `graphql_operation_type` column. Not really useful data since we don't re-use function names for query and mutation.

fix: remove the graphql operation type from metrics

---

src/integrations/feed/configs.ts

I missed the order so errors don't show up as they should in GC.

fix: proper arguments for error when logged

---

bin/copyUserCommentUpvoteData.ts

After https://github.com/dailydotdev/daily-api/pull/1785 is merged we can run the migration to bring two tables in parity with data. There is only ~60k rows so it can probably be run in single go.

feat: migrate from comment_upvote to user_comment

---

__tests__/cron/dailyDigest.ts
src/cron/dailyDigest.ts

Make the cron job agnostic to when it was triggered to make sure digest is sent on the same time every day.

fix: send proper time in the daily digest

---

.infra/index.ts

Reduces the requested resources as they're a bit over requested compared to the actual usage.
<table>
<tr>
<td>Memory usage
<td>CPU usage
<tr>
<td><img src=https://github.com/dailydotdev/daily-api/assets/1681525/811f6640-13e5-4152-b4db-7c6029f82b71>
<td><img src=https://github.com/dailydotdev/daily-api/assets/1681525/8ed77628-f3c1-4146-9852-165235ccbdb7>
<tr>
<td colspan=2>
Reduces the requested memory from 640MiB to 400MiB<br />
And CPU request from 1000m to 800m
</td>
<tr>
<td><img src=https://github.com/dailydotdev/daily-api/assets/1681525/a9c54e50-e7a1-429d-af54-43b833487e48>
<td><img src=https://github.com/dailydotdev/daily-api/assets/1681525/dd9c22ec-7339-4d45-b9e0-33b616588f59>
<tr>
<td colspan=2>
Reduces the requested memory from 256MiB to 150MiB<br />
And CPU request from 250m to …

chore: reduce api requests resources

---

__tests__/posts.ts
src/entity/posts/Post.ts
src/migration/1712315208717-PostSlugMaxLength.ts

Added truncate of 100 to title part.
Had to add replica to typeorm table (some of the old migration downs would actually fail if we ever needed to run them)
Added specific test case as well to ensure it.

fix: truncate title for slug

---

.infra/index.ts

Last 180 days it's never really passed 10milli cpu

chore: reduce requested cores for api-private

---

__tests__/posts.ts
src/schema/posts.ts

Adding support for `extensions.postId` to allow clients to query private posts on client side. See https://github.com/dailydotdev/apps/pull/2951

feat: return postId with forbidden error

---

__tests__/workers/cdc/primary.ts
__tests__/workers/commentUpvoteCanceledRep.ts
__tests__/workers/commentUpvotedRep.ts
__tests__/workers/postDownvoteCanceledRep.ts
__tests__/workers/postDownvotedRep.ts
__tests__/workers/postUpvoteCanceledRep.ts
__tests__/workers/postUpvotedRep.ts
src/common/pubsub.ts
src/common/typedPubsub.ts
src/workers/cdc/primary.ts
src/workers/commentUpvoteCanceledRep.ts
src/workers/commentUpvotedRep.ts
src/workers/index.ts
src/workers/postDownvoteCanceledRep.ts
src/workers/postDownvotedRep.ts
src/workers/postUpvoteCanceledRep.ts
src/workers/postUpvotedRep.ts

AS-237
Current worker logic that was applied from post never worked when user changes from upvote to downvote or vice verse. This fixes it and adds additional tests to cover the case.
Also refactored rep workers to typed workers because it allowed me to streamline cdc logic for any kind of future vote entities.

fix: vote change handling and move to typed workers

---

__tests__/workers/cdc/primary.ts
bin/retroFixCommentImages.ts
src/common/pubsub.ts
src/workers/cdc/primary.ts

Classic reason why we need the type safe topics.
Didn't implement here though because this topic has way too many subscribers to quickly iterate "please note we should eventually do this as backlog ticket" :hidethepain:
Subscription expects `contentHtml` from the topic.
Topic never publishes this.
```js
export const generateNewImagesHandler =
<T extends Data<Content> = Data<Content>>(
key: keyof T,
type: ContentImageUsedByType,
contentKey: keyof Data<Content> = 'contentHtml',
) =>
async (message, con): Promise<void> => {
const data: T = messageToJson(message);
const obj = data[key];
if (!obj || !obj?.id || !obj?.[contentKey]) return;
await updateUsedImagesInContent(con, type, obj.id, obj[contentKey]);
};
```
Resulting in comment cleaned every 30 days, we can't retro bring these back 😢 …

fix: zombie process for images

---

__tests__/workers/commentMarkdownImages.ts
src/workers/commentMarkdownImages.ts
src/workers/generators/generateNewImagesHandler.ts
src/workers/postFreeformImages.ts

We actually send `post` as ChangeObject<Post>` but comment as raw data basically so we can't just rely on abstracting the type here.
I know it's a little bit messy, but for a quick fix the fastest solution.
Do think we should re-evaluate if we can move this topic to full object rather 🫠

fix: comment don't send as changeObject

---

__tests__/keywords.ts
bin/updateKeyword.ts
src/entity/Keyword.ts
src/schema/keywords.ts

AS-241
- add title and description to `flags` 
- open keyword query so we can fetch it on `/tags/:tag` on frontend and get `description`
- added script for CSV import
- also added [Retool app](https://dailydotdev.retool.com/apps/8470354e-f745-11ee-b6ec-8b108f7c86be/%5BWIP%5D%20Update%20keyword%20(tag)) for keyword description update

feat: open keyword query and add meta props to flags

---

__tests__/sources.ts
src/schema/sources.ts
src/schema/tags.ts

Add query to sources to get relatedTags for the source.
Based on:
- last 90 days post
- keyword count
- allowed keywords
(subnote: would actually be nice to have a postman collection shared 😅)

fix: add query to get related tags for source

---

src/entity/PostKeyword.ts
src/entity/posts/Post.ts
src/migration/1712910394483-KeywordIndexes.ts
src/schema/sources.ts

It was either this query or the reverse double one (query post-keyword then do where IN [sourceId], but felt one query might be easier.
Could potentially be a heavy one due to count, so let's monitor everSQL closely with this :) 
Decided to make it a paginated one in case we want to use it for something else later on.
It can get a list of sources ranked by how many of the keyword occurrences happen on post it has.  (excluding private sources)
On prod run:

fix: source by tag query

---

.infra/crons.ts
src/cron/updateSourceTagView.ts
src/entity/SourceTagView.ts
src/migration/1712930614437-SourceTagView.ts

Added a materialized view for source-tag-count 
Will modify use-cases in a separate PR to keep things easier to review.
Local example:

feat: add source tag materialized view

---

__tests__/search.ts
src/schema/search.ts

The actual search resolver will order based on position in the idStr.
So we pass the same logic to the suggestion v2 resolver now.
Added to test to notify if this ever changes by accident.

fix: search suggestion ordering

---

__tests__/workers/cdc/primary.ts
src/workers/cdc/primary.ts

Clears the boot cache when a user is assigned to a campaign.
Important to note, all this logic will most likely be refactored when the customer.io integration is implemented

fix: clear boot cache on user assignment to Marketing CTA campaign

---

__tests__/workers/notifications/collectionUpdated.ts
src/workers/notifications/collectionUpdated.ts

NotificationV2 system is optimized and reuses avatars between multiple notifications (and notification types). Which means that for all notifications referencing avatar X, there will be only one instance of that avatar in notification avatar table.
Due to missing `handle` column in `SELECT` inside `collectionsUpdated` worker this avatar would be created with:
I added column to select and adjusted test to specifically look for URL structure.  
This edge case would happen specifically when there was a collection created that was connected to source X and then when notification was created in `source_post_added` due to new post being added to source the new notification would reuse avatar created by collections notification bundle which would contain `undefined` instead of proper handle.
I …

fix: targetUrl would be constructed with undefined due to missing handle

---

src/telemetry/opentelemetry.ts

Just [found the error](https://console.cloud.google.com/logs/query;query=labels.%22k8s-pod%2Fapp%22%3D%22api-personalized-digest%22%0Aseverity%3DERROR%0AtextPayload%3D%22The%20'spanProcessor'%20option%20is%20deprecated.%20Please%20use%20'spanProcessors'%20instead.%22;summaryFields=:false:32:beginning;cursorTimestamp=2024-04-30T09:55:01.561443039Z;duration=P7D?project=devkit-prod&authuser=2) randomly while browsing some other logs.

fix: use span processors option since other is deprecated

---

bin/import.ts

This makes sure that materialized view is refreshed after import so that frontend gets the data. Without it tags are empty for all soruces. Does not affect production, only local DX.

feat: refresh source tag materialized view

---

__tests__/__snapshots__/feeds.ts.snap
__tests__/feeds.ts
__tests__/integrations/feed.ts
__tests__/workers/__snapshots__/personalizedDigestEmail.ts.snap
src/common/feedGenerator.ts

Make watercooler as opt-in even though it's a public feed. Watercooler mostly has memes which not all the users want, surfacing it as default to all users seems to be controversial.
I also fixed a bug that even though "show on my feed" was set to false there could be an edge case where we show the posts of the squad. Unrelated to the original task but I noticed it as I go.

feat: set watercooler to be opt-in

---

src/workers/newNotificationV2Mail.ts

This email had the wrong template ID.
The data it sends seems valid.

hotfix: use the right template id

---

__tests__/common/search.ts
__tests__/search.ts
src/common/search.ts
src/schema/search.ts

AS-281
Add query to use in search panel. https://github.com/dailydotdev/apps/pull/3067
Similar query is in `schema/keywords` but it is only for moderators and I wanted to expose this one from`schema/search` to match specific format we return for all of our search providers.

feat: add search tags suggestions query

---

src/schema/feeds.ts

Need to test it via postman but can't mimic the post_similarity locally.
So plan was to deploy/test with postman then come back and adjust/add tests

feat: add similar posts as a feed option

---

src/schema/feeds.ts

After tedious debugging I realized our `feedResolverCursor` doesn't allow post_id by default, thus a manual generator setting is needed to actually add the `post_id`.

fix: actually send post_id as prop

---

__tests__/posts.ts
__tests__/triggers/post.ts
src/common/post.ts
src/entity/posts/utils.ts
src/migration/1714633817175-SquadTotalPostsTrigger.ts
src/migration/1714662136871-SquadTotalUpvotesTrigger.ts
src/migration/1714667947050-SquadTotalViewsTrigger.ts
src/schema/posts.ts

As the RFC has mentioned, we should update the mutation for creating new posts related to Squad.
There was no mention of deleting posts, but I assumed we should reduce the count by 1. Feel free to mention if we should not make any changes to it.
Notable changes here:
- Created a generic function for saving changes to posts, this is to allow us to streamline the updating of flags (maybe we could have done the increment on the new post worker, but I might have missed the discussion around it).
- Created a generic function for deleting a post, to do the same above.
MI-322 #done

refactor: squad posting to increment squad total posts

---

__tests__/submissions.ts
src/schema/submissions.ts

I noticed that the submission date check was dependent on the date of the database server, and actually not on the user.
So `2024-04-13 01:33:54` at `Europe/Oslo` would be `2024-04-12 23:33:54` at `UTC`, but when casting the timezones, that would become `2024-04-12 02:00:00`.
The same would `2024-04-12 23:59:59` at `Europe/Oslo` become `2024-04-12 02:00:00` at `UTC`.

fix: move at timezone into date_trunc for submission check

---

__tests__/comments.ts
__tests__/helpers.ts
__tests__/posts.ts
src/directive/rateLimit.ts

The error message for high rate squad, like Watercooler, should say `last ten minutes` instead of `last hour`.

fix: correct copy for high rate squads

---

__tests__/__snapshots__/sources.ts.snap
__tests__/sources.ts
src/schema/sources.ts

For successfully querying squads that the user belongs to, we need to be able to filter the sources by type. 
Changed the unit tests not to depend on snapshots as well, AFAIK that's the new practice.
Related issue: 
- https://dailydotdev.atlassian.net/browse/MI-324
Related PR for the UI changes:
- https://github.com/dailydotdev/apps/pull/3084

feat: filter mySourceMemberships by type

---

__tests__/actions.ts
__tests__/alerts.ts
__tests__/bookmarks.ts
__tests__/compatibility.ts
__tests__/rss.ts
__tests__/settings.ts
__tests__/workers/cdc/primary.ts
src/entity/Alerts.ts
src/entity/Bookmark.ts
src/entity/Settings.ts
src/entity/user/UserAction.ts
src/entity/user/UserState.ts
src/migration/1715095164142-AddUserRelationFK.ts
src/routes/boot.ts
src/schema/settings.ts
src/workers/notifications/index.ts

In addition to https://github.com/dailydotdev/daily-api/pull/1878, fixing other cases where FK was missing on `userId` column.
- adding 1:1 and M:1 relations depending on PK
- migration file each has `DELETE` statement to delete leftover entries from relation tables for deleted users, eg. leftover alerts, bookmarks, settings from those deleted users
- tests updates are mostly due to users fixture missing now that we added FK
this will delete:
- user_action - 6,596 rows
- alerts - 33,347 rows
- bookmark - 4,278 rows
- settings - 74,233 rows
- user_state - 9 rows

feat: add missing fk to user relations

---

__tests__/integrations/feed.ts
src/integrations/feed/configs.ts
src/integrations/lofn/types.ts

Some feed experiments are not part of the inner config but the request itself. Something we will probably have to fix in the future but for now we need it for the AIGC experiment.

feat: handle lofn extra field

---

.infra/index.ts

Last week I deleted ~4 GiB worth of old and untouched Redis keys. At the time we were using 5 out of 10 GiB of memory, which had been stable for months. Now we use 1.3 out of 10 GiB, so we can reduce it to 2 GiB and disable read-replica as we're not using it.

chore: reduce redis instance size

---

__tests__/__snapshots__/feeds.ts.snap
__tests__/feeds.ts
src/common/feedGenerator.ts
src/entity/AdvancedSettings.ts
src/integrations/feed/configs.ts
src/integrations/feed/generators.ts
src/integrations/feed/types.ts
src/schema/feeds.ts

Pass through the blocked_content_curation options to feed service.
@pnvasanth We send an example as such (this is correct?):
```
{
user_id: '0c3TpWWzGYHbOOFp9k3av',
page_size: 9,
offset: 0,
cursor: undefined,
allowed_post_types: [ 'article', 'share', 'freeform', 'video:youtube', 'collection' ],
total_pages: 1,
fresh_page_size: '3',
blocked_sources: [ 'community', 'fd062672-63b7-4a10-87bd-96dcd10e9613' ],
blocked_content_curations: [ 'listicle' ]
}
```

fix: send blocked content curation to feed service

---

__tests__/workers/postUpdated.ts
src/workers/postUpdated.ts

After https://github.com/dailydotdev/daily-api/pull/1915 the prematurely visible post would still not update with error. It was due to trigger updating notification attachment image during type update.
When post ID was created through new create post endpoint its `type` is `article` which is default. Due to bug in https://github.com/dailydotdev/daily-api/pull/1915 this post became visible immediately which in turn scheduled a notification with attachment and other elements.
When next `content-published` message arrived with correct `type=video:youtube` it tried to update the type of post in separate query we do in the beginning of `updatePost` function call. The issue was that this call triggered a trigger which tried to update an image as well but due to post not having an image (and no …

fix: pass image to content type update to avoid trigger failing

---

__tests__/workers/postUpdated.ts
src/workers/postUpdated.ts

After introduction of #1915 all post get created on API first to reserve post id. 
Our scout assignment logic runs only on `createPost` so it would miss attributing scouts for these new posts.
This PR adds the logic in `updatePost` as well and `scoutId` is set if it was not set before.
For more info see [thread](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1715872489501549)

feat: set scout during post update

---

.infra/Pulumi.prod.yaml

It always detected changes in the yaml file, but because the pulumi value was set the `table.include.list: "public.post"`, it always used that value, instead of the one in the yaml file 🙈

fix: remove `table.include.list` from `Pulumi.prod.yaml`

---

__tests__/boot.ts
src/routes/boot.ts

Our sidebar is prone to layout shifts so feeds have to go to boot. 😞 
It will be preloaded into `useFeeds` query on frontend during boot fetch see https://github.com/dailydotdev/apps/pull/3106/commits/4ca6cdf6ac7a935b0ce718b4e6be303b66a895c1

feat: add feeds to logged boot

---

__tests__/sources.ts
src/errors.ts
src/schema/sources.ts

Allow admins to make their public Squad go private (vice-versa) once approval has been received.
Something we missed on the RFC: https://dailydotdev.slack.com/archives/C069XNYMDGV/p1715851833290429?thread_ts=1715851745.713089&cid=C069XNYMDGV

fix: switching back to private mode

---

.infra/index.ts

Latest commits broke api-bg in adhoc, as it is unable to load JWT keys.

fix: add missing jwt keys to adhoc deployments

---

.infra/Pulumi.prod.yaml

Replaces the CIO webhook signing key to be production key

fix: update the CIO webhook secret to be production key

---

.infra/crons.ts
__tests__/__snapshots__/tags.ts.snap
__tests__/cron/updateHighlightedViews.ts
__tests__/sources.ts
__tests__/tags.ts
src/cron/index.ts
src/cron/updateHighlightedViews.ts
src/entity/PopularPost.ts
src/entity/PopularSource.ts
src/entity/PopularTag.ts
src/entity/PopularVideoPost.ts
src/entity/PopularVideoSource.ts
src/entity/TrendingPost.ts
src/entity/TrendingSource.ts
src/entity/TrendingTag.ts
src/migration/1717019094737-HighlightedViews.ts
src/schema/sources.ts
src/schema/tags.ts

Implementation [from](https://dailydotdev.slack.com/archives/C06S6HEUZB9/p1714918400969439)

feat: highlighted views and queries

---

src/telemetry/opentelemetry.ts

Didn't really use HTTP method or status code in metrics

fix: reduce cardinality of `requests` counter

---

__tests__/__snapshots__/keywords.ts.snap
__tests__/keywords.ts
src/schema/keywords.ts

I need the field for upcoming roadmap integration so I can link tag to its synonym if exists.

feat: add keyword synonym field

---

__tests__/webhooks.ts
src/routes/webhooks/customerio.ts

AS-369
cio does not support `DELETE` method so opted for `/delete` path. Alternative to use custom header can be limited by header size (because we will be sending JSON) so I think this is easier and in the future we can easily switch back the method if cio supports it.

feat(cio): webhook move to delete path instead of method

---

__tests__/privateRpc.ts
src/routes/privateRpc.ts

- url could be saved as `undefined | ''` and we want `null` value for the row (to avoid duplicate constraint)
- also added logging so on error we can see the payload for create post

fix(create-post): make sure url is saved as null if missing

---

__tests__/search.ts
src/schema/search.ts

Add search source suggestion endpoint.
Modified to expose subtilte/image as global names as we might use it for other purposes with search suggestions later on.

fix: add search source suggestions endpoint

---

Dockerfile.dev

This is just a minor DX improvement when working with scripts locally. Instead of doing `./node_modules/.bin/ts-node`, you can now just do `ts-node` directly.

fix: add node_modules bin directory to path

---

.infra/index.ts

After we adjusted requests and limits, the HPA has scaled up a bit more. The pods now idle around 80% of requested, where the HPA kicks in and scales up deployment.
This change sets the HPA to trigger at 130% usage of requested memory, which is 81.25% of limit.

fix: set HPA to trigger at 130% of requested memory (~80% of limit)

---

__tests__/__snapshots__/users.ts.snap
__tests__/common/timezone.ts
__tests__/users.ts
src/common/index.ts
src/common/timezone.ts
src/entity/user/User.ts
src/schema/users.ts

Adds validation for timezones. Users are now able to send in their own value, with would break the digest cron jobs as postgres expects valid timezones.
AS-394

fix: validate timezone input

---

__tests__/keywords.ts
__tests__/posts.ts
__tests__/workers/notifications/collectionUpdated.ts

It doesn't fix the main one we have :( (can't find what could cause the source id to change, maybe the parralism? although this shouldn't be affected from what I can read per suite)
Does fix some other flaky tests we had (same named tests basically is never a good idea)
Tried some random flaky test package and it didn't even find the main one. (So makes me wonder it's really due to parralism :))
Others found though:

fix: trying to fix some flaky tests

---

__tests__/sources.ts
src/schema/sources.ts

When we introduced the source directory, we did a workaround to overcome graphorm issue. But now I fixed the queries to follow our best practices

fix: fetch sources using our best practices

---

.infra/Pulumi.prod.yaml
src/common/slack.ts
src/workers/postScoutMatchedSlack.ts

Separate comments to the rest within Slack to make it easier to moderate

refactor: use different slack channels

---

__tests__/workers/newView.ts
src/workers/newView.ts

We detected that in the current streak system we always update each row in `user_streak` with a new `lastViewAt` and `updatedAt` this has heavy implications on the writes on this table.
In general it's not that bad, but when we add debezium to this table/cdc it overloads that system.
We decided to do two separate queries
- Query if streak should be updated
- If yes: Run update
This results in only 1 write per user a day.
Once approved I'll adjust the CDC flow again to bring it back.
For reference the old PR has notes around what's implemented already:
https://github.com/dailydotdev/daily-api/pull/1653

fix: update to queries to avoid writes

---

__tests__/users.ts
src/entity/Feature.ts
src/graphorm/index.ts
src/schema/users.ts

Ole-Martin's favorite feature enablement.
This way we can simply add it to each user fragment wherever we want to know it :)

feat: add team member output

---

src/cron/syncSubscriptionWithCIO.ts

Easier to see how many was synced, instead of having to sum all of the logs 🙈

refactor: change the log output of sync-subscription-with-cio cron

---

__tests__/workers/postUpdated.ts
src/workers/postUpdated.ts

The update hook didn't check if canonical/url already exists on the change causing catch errors.
Explicitly check now and uniform the check function

fix: add canonical check on update aswell

---

__tests__/webhooks.ts
src/onesignal.ts
src/routes/webhooks/customerio.ts
src/types.ts

Adds a new webhook endpoint that allows us to send notifications via OneSignal from customer.io
Also cleaned up the webhook tests to simplify the generation of signatures.
Expected JSON payload is
```json
{
"userIds": ["u1", "u2"],
"notification": {
"title": "Notification title",
"body": "Notification message"
}
}
```
And the `notification` can be extended like this. Where both `url` and `utm_campaign` are both optional. `utm_campaign` has no effect if no `url` is set.
```json
{
"userIds": ["u1", "u2"],
"notification": {
"title": "Notification title",
"body": "Notification message",
"url": "https://website.com",
"utm_campaign": "utm_campaign"
}
}
```
AS-412

feat: add generic notification webhook endpoint

---

__tests__/boot.ts
__tests__/feeds.ts
src/routes/boot.ts
src/schema/feeds.ts

Private feed for platform guys to play with.
I know it's not 100% secure on this side, but don't think it's exposing much realisticly.
The FE part is actually limited to team members (hence the boot addition)

fix: add new private feed by ids

---

__tests__/workers/notifications.ts
src/entity/user/UserStreak.ts
src/errors.ts
src/workers/cdc/common.ts
src/workers/cdc/notifications.ts
src/workers/commentCommentedSlackMessage.ts
src/workers/commentDownvotedRep.ts
src/workers/commentUpvotedRep.ts
src/workers/experimentAllocated.ts
src/workers/index.ts
src/workers/newNotificationV2RealTime.ts
src/workers/newView.ts
src/workers/notifications/devCardUnlocked.ts
src/workers/notifications/index.ts
src/workers/notifications/postMention.ts
src/workers/notifications/sourceMemberRoleChanged.ts
src/workers/notifications/sourceRequest.ts
src/workers/notifications/squadMemberJoined.ts
src/workers/notifications/squadPublicRequestNotification.ts
src/workers/notifications/utils.ts
src/workers/notifications/worker.ts
src/workers/personalizedDigestEmail.ts
src/workers/postCommentedSlackMessage.ts
src/workers/postDownvotedRep.ts
src/workers/postUpvotedRep.ts
src/workers/updateComments.ts
src/workers/usernameChanged.ts

This one focuses on:
- error type handling
- workers
- especially notification workers and their types

feat: apply strict typescript rules to workers

---

src/telemetry/metrics.ts
src/workers/cdc/primary.ts

Would be nice to know...
I see sometimes the CDC still gets overworked and kind of want to see which tables cause these spikes.
Do let me know if anyone thinks it's too much 😅

chore: add metric to see which table spools how many req

---

package-lock.json
package.json
src/telemetry/metrics.ts

This removes the GCP metric exporter, now we only use prometheus metrics

fix: remove gcp metrics exporter

---

__tests__/workers/notifications/collectionUpdated.ts

~~From looking at the tests it looks like some other test inserts `PostRelation` (there are few in notification and cdc tests) and then post used in `collectionUpdated` gets different sources. I changed the post ids to be unique in this test suite which will hopefully avoid collision and flakiness.~~
it failed..
actually, looking at it again, it could be the ordering issue since in `getAllSourcesBaseQuery` inside worker we order based on `createdAt` so basically `community` source is added to the post but db sometimes spills them other way around depending on the insert.
If I force it I get exact test fail which is good because now I can repro locally:

fix: flaky worker test

---

package-lock.json
package.json
src/common/markdown.ts

daily.dev strict mode PR template
This one focuses on:
- markdown
- utils

feat(strict-ts): apply to markdown utils

---

src/common/typedPubsub.ts
src/workers/notifications/postBookmarkReminder.ts
src/workers/notifications/worker.ts

- Introduce a typed notification worker.
- Removes the necessity of having to use `messageToJson` by introducing a worker generator.
- Typed data based on the topic.
- See the error below if I try to deconstruct an unknown property to what was defined.

feat: typed notification worker

---

src/graphorm/index.ts

Super big edge case...
But when viewing any of the comment feeds votes on comments would show as those from THAT user not your logged in user.
This was caused by the innerJoins on graphorm using the same parameter property basically.
EG:
Top level
Sub level (graphorm)
Resulting in sub level alone:
```
res [
'(SELECT "user_comment_pw4"."vote" AS "vote", user_comment_pw4."votedAt" AS "votedAt" FROM "public"."user_comment" "user_comment_pw4" WHERE user_comment_pw4."userId" = $1 AND user_comment_pw4."commentId" = comment_z2m."id" LIMIT 1)',
[ 'TPKCfSC2rYrYNShi8Ynxs' ]
]
```
But because the parameters are shared inside a bigger query the end result combination is:
```
'SELECT "comment_fny"."id" AS "id", "comment_fny"."contentHtml" AS "contentHtml", "comment_fny"."createdAt" AS "createdAt", …
```

hotfix: unique select merge

---

src/common/personalizedDigest.ts

We want to see if having small amount of posts in digest is more widespread.

feat: log when posts are lower then max

---

src/Context.ts
src/common/vote.ts
src/schema/comments.ts
src/schema/devcards.ts
src/schema/posts.ts
src/schema/sources.ts
src/schema/trace.ts
src/schema/users.ts

This one focuses on:
- users schema
- context (splitting to BaseContext & AuthContext)
- schemas that are not updated yet default to Context
This one squashed about 100 errors :success:

feat(strict-ts): apply to users schema

---

src/telemetry/opentelemetry.ts

Temporarily disables the pino telemetry instrumentation, as I noticed the logs appears twice, once as a single line, the once output on multiple lines.
Will come back later to this to look at why it happens, but in the meantime, not much value is lost.

fix: temporarily disable pino telemetry instrumentation

---

.infra/Pulumi.adhoc.yaml

fix: remove `api:image` from adhoc

---

__tests__/search.ts
src/schema/search.ts

[Thread](https://dailydotdev.slack.com/archives/C03C3JZPRU4/p1722243021223849?thread_ts=1722242588.418389&cid=C03C3JZPRU4)
if no ids are passed so it gets empty `IN ()` which is syntax error

fix: post suggestions query error when empty

---

package-lock.json
package.json
src/schema/search.ts
src/schema/settings.ts
src/schema/submissions.ts
src/schema/tags.ts

- search schema
- settings schema
- submissions schema
- tags schema
- uuid package types added

feat(strict-ts): apply to gql schemas

---

src/schema/actions.ts
src/schema/alerts.ts
src/schema/bookmarks.ts
src/schema/comments.ts

- actions schema
- alerts schema
- bookmarks schema
- comments schema

feat(strict-ts): apply to gql schemas 2

---

__tests__/temporal/notifications/activities.ts
__tests__/temporal/notifications/utils.ts
__tests__/temporal/notifications/workflows.ts
package-lock.json
package.json
src/temporal/common.ts
src/temporal/config.ts
src/temporal/notifications/utils.ts

- Create a function to catch errors that results to NotFound. As per documentation, running the `handle. describe` would result in a not found error rather than returning null.
- When the same workflow id is running, we should just ignore executing the same workflow.
- When workflow is not found and trying to cancel the id, we should just ignore it.
- Setup a test environment for Temporal. This involves worker registration in the test environment for integration testing.
~~TODO:~~

fix: temporal workflow has already started

---

src/common/post.ts
src/common/pubsub.ts
src/entity/posts/Post.ts
src/schema/comments.ts
src/schema/posts.ts
src/workers/postCommentedRedis.ts
src/workers/postUpvotedRedis.ts

- posts schema
- minor fixes from past few PRs that were added to `main`
- almost half way there 💦

feat(strict-ts): apply to posts schema

---

bin/import.ts

Seed import would fail locally because of dep cycle of `UserStats` so import would be `undefined`

fix: seed import cycle import

---

src/workers/postAddedSlackChannelSend.ts

Forgot to decrypt token in worker which resulted in failed auth on slack. Also added error handling so we can catch future errors in message handler.

fix: decrypt slack user token and error handling

---

__tests__/posts.ts
src/common/links.ts
src/graphorm/index.ts
src/schema/posts.ts

Since we don't want to expose url/canonical to FE, decided to handle it like this on API side.

fix: add domain exposure

---

package-lock.json
package.json
src/telemetry/opentelemetry.ts

Can now trace `fetch` requests too
```ts
await fetch('https://webhook.site/50afac16-4d86-4ae1-921e-73a40aa29cf3');
```

feat: add fetch/undici instrumentation

---

__tests__/integrations.ts
src/schema/integrations.ts

- with last change it was not sending if bot was part of slack channel already

feat: always send join message when channel is changed for source

---

__tests__/integrations.ts
__tests__/workers/postAddedSlackChannelSend.ts
src/common/userIntegration.ts
src/schema/integrations.ts
src/workers/postAddedSlackChannelSend.ts

- now supports private posts as well (since we no longer depend on slack link embeds)
- also refactored WebClient to single place so we can set appropriate log level
- add utm params to links

feat(slack): adjust message format after testing

---

src/common/post.ts
src/entity/Source.ts
src/schema/sourceRequests.ts
src/schema/sources.ts

- source schema
- sourceRequest schema

feat(strict-ts): apply to source schemas

---

__tests__/workers/postAddedSlackChannelSend.ts
src/common/userIntegration.ts

feat(slack): add source name and image for attachment

---

__tests__/comments.ts
__tests__/common/vordr.ts
__tests__/feeds.ts
__tests__/posts.ts
__tests__/submissions.ts
__tests__/workers/cdc/primary.ts
__tests__/workers/notifications/postAdded.ts
src/common/feedGenerator.ts
src/common/post.ts
src/common/vordr.ts
src/entity/Submission.ts
src/entity/posts/Post.ts
src/entity/posts/utils.ts
src/migration/1723135865854-SubmissionFlags.ts
src/schema/comments.ts
src/schema/posts.ts
src/schema/sources.ts
src/schema/submissions.ts
src/telemetry/metrics.ts
src/workers/notifications/postAdded.ts
src/workers/postUpdated.ts

Marking as ready for review, but I'm working on tests for:

feat: vordr on posts

---

__tests__/integrations.ts

`save([...])` can insert in random order depending on psql load so added `createdAt` manually as in other places

fix: slack flaky test

---

__tests__/feeds.ts
__tests__/fixture/post.ts
__tests__/workers/postAddedSlackChannelSend.ts
__tests__/workers/vordrPostPrevented.ts
src/workers/postAddedSlackChannelSend.ts

New worker was added. Don't send messages via slack integration if posts is prevented by vordr.

fix: don't send slack integration notification if post is vordr flagged

---

__tests__/submissions.ts
src/schema/submissions.ts

Currently community picks on already added but private/non visible fields would show it exists, on clicking result in 404.
So now we simply show it got added before, and cannot be re-added (as per deleted guidelines)
AS-502 #done

fix: don't show non visible community picks

---

src/common/feedGenerator.ts
src/schema/actions.ts
src/schema/alerts.ts
src/schema/bookmarks.ts
src/schema/comments.ts
src/schema/common.ts
src/schema/compatibility.ts
src/schema/devcards.ts
src/schema/feeds.ts
src/schema/integrations.ts
src/schema/keywords.ts
src/schema/leaderboard.ts
src/schema/notifications.ts
src/schema/settings.ts
src/schema/tags.ts
src/schema/urlShortener.ts
src/schema/users.ts

- feeds schema
- devcard schema
- notifications schema
- common schema
- some retro fixes for code that was added in the meantime
- remove `any` eslint-disable rules from all schemas (now that context is standardized)
This one concludes work on schemas.

feat(strict-ts): apply to gql schemas 3

---

src/telemetry/metrics.ts
src/workers/postAddedSlackChannelSend.ts

Add metric for slack post sends so we can see how many posts where sent to different channels/workspaces.

feat(slack): send post metric

---

__tests__/workers/newNotificationV2Mail.ts
__tests__/workers/notifications.ts
src/workers/newNotificationV2Mail.ts
src/workers/notifications/postAdded.ts

No longer sending new post notification if you where mentioned on set post.
Adds email for post_mention notification.
Open question to product if we can fix that freeform also sends email.
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1723715298467949?thread_ts=1718870031.393249&cid=C01L0QXQJNB

As 393 double notifications

---

src/common/slack.ts

Minor change in how messages are sent in slack

fix: add source ID to vordr post slack messages and use short field for username and ID

---

__tests__/search.ts
src/schema/search.ts

In order to enfore using the right indexes we need a ordering by (choose reputation as it makes a lot of sense)

chore: add ordering on search users

---

__tests__/users.ts
src/common/users.ts

When the start of the week is Sunday, the condition is not totally valid on all cases.
We now return early so if the condition doesn't apply, we won't have to unnecessarily check whether it would fit the second part of each remaining conditions.

fix: sunday as start of week

---

__tests__/workers/userStreakUpdatedCio.ts
src/cio.ts

Remove the temporary log
Fix the actual sending of the last_view_at (at UTC - so we can quicker compare it inside CIO)

chore: fix the correct sending of last_view_at

---

bin/insertMissingSourceFollows.ts

When we migrated from subscribe to follow-notify we missed the fact we need to retro make anyone that's currently subscribed also auto-follow that source.
This script inserts records into `feed_source` if they don't exist, but are subscribed to a source.
(We need to bypass the trigger, else it will auto remove the records from `notification_preference`)
Discussion here:
https://dailydotdev.slack.com/archives/C01473UNK9C/p1724134356244039

chore: bin script for missing feed_source follows

---

src/common/slack.ts
src/integrations/analytics.ts
src/integrations/feed/configs.ts
src/integrations/feed/types.ts
src/integrations/networkError.ts
src/integrations/retry.ts
src/types.ts

feat(strict-ts): apply to integrations

---

__tests__/workers/postUpdated.ts
src/workers/postUpdated.ts

@denisb0 backfills and also translates freeform post titles after creation so we want to save `contentMeta` for freeform posts as well.

feat: allow contentMeta update in freeform post

---

__tests__/users.ts
src/common/mailing.ts
src/schema/users.ts

Send email verification.
Also added a check to see if the email is already verified, to not generate new codes and sending emails. Edge case, but could be if user has verification open in two windows, verifies in one, then clicks re-send code in another windows.
Required to be merged before https://github.com/dailydotdev/apps/pull/3478
AS-536

feat: send company verification email

---

.infra/index.ts

trying to scale vertically first since workers were quite small and since we introduced more features they do quite a bit more work

chore: adjust digest pod limits

---

.infra/index.ts
src/commands/personalizedDigest.ts

We also ack only single message per worker :hidethepain:
put it to 25 now because this was a ack/s ration for pods so I think each pod should be able to handle it

chore: adjust digest limits and ack count

---

src/commands/personalizedDigest.ts

Aside from initial worker which gets overloaded until we scale pods we have a bit of legroom on the pods so I would try to increase the maxMessages to `50` so its parallelized a bit more. 
Oldest ack message is already much lower and not triggering alerts

chore: adjust digest max messages

---

.infra/workers.ts
src/commands/personalizedDigest.ts

- also lower dead letter to 3 to avoid many respools since probably something is down if it fails more then few times

chore: revert scaling to 25 to avoid hitting other services as much

---

__tests__/workers/postUpdated.ts
bin/insertCodeSnippets.ts
package-lock.json
package.json
src/common/googleCloud.ts
src/common/post.ts
src/common/utils.ts
src/entity/posts/Post.ts
src/entity/posts/PostCodeSnippet.ts
src/migration/1724929128486-PostCodeSnippets.ts
src/types.ts
src/workers/postUpdated.ts

Will add query for snippets in following PR.
Verified locally by pulling few snippets from prod. Need to merge this so I can back import with created script.
AS-496

feat: download and store code snippets

---

__tests__/workers/cdc/primary.ts
__tests__/workers/notifications.ts
src/common/users.ts
src/workers/cdc/primary.ts
src/workers/notifications/userStreakResetNotification.ts

Root cause: the column was `timestamptz`, so we should not use the debezium time function. Returned value was string.
Still added some logging for debugging purposes. This should only log when the user streak was greater than 2 and turned to 0.

fix: streak reset time calculation

---

.infra/index.ts
.infra/workers.ts
package-lock.json
package.json
src/commands/personalizedDigest.ts
src/common/personalizedDigest.ts
src/common/utils.ts
src/index.ts
src/integrations/feed/clients.ts
src/integrations/feed/generators.ts
src/integrations/garmr.ts
src/schema/feeds.ts
src/telemetry/metrics.ts

- circuit breaker implementation for FeedClient
- can be injected into other feed services like Lofn
- can also be used outside of classes/clients as regular instance/singleton
- possibly we can expose more options and different types of [breaker strategies](https://github.com/connor4312/cockatiel?tab=readme-ov-file#circuitbreakerpolicy--halfopenafter-breaker-initialstate-)
TODO

feat: add circuit breaker for feed client

---

.infra/index.ts
src/commands/personalizedDigest.ts
src/common/personalizedDigest.ts

- lower memory (we were nowhere close to 2Gi)
- increase parallel processing to 100 messages on worker
- adjust garmr to match

chore: adjust digest limits and processing

---

__tests__/users.ts
src/entity/user/UserStreakAction.ts
src/schema/users.ts

Restoring for the 3rd time might introduce an issue. In this case, we should just use when the restoration happened for the target id to provide uniqueness.

fix: reputation event for restoring streak

---

__tests__/users.ts
src/common/users.ts

When fetching the column, we need to set the right type so that the value will be in UTC format before converting it the user's configured timezone.
Similar to what we were doing in the past with user read history.
https://github.com/dailydotdev/daily-api/blob/350c878774a7838febe0d18f162f0f812c1e82f7/src/schema/users.ts#L1033

fix: formatting the streak recovery date to the correct timezone

---

.infra/crons.ts
__tests__/cron/dailyDigest.ts
__tests__/cron/personalizedDigest.ts
src/common/personalizedDigest.ts
src/cron/dailyDigest.ts
src/cron/personalizedDigest.ts

- send weekly digest per timezone offset same as daily digest
- should split the send over many batches throughout the day instead of single one at midnight
- should also increase weekly digest quality (article freshness) since generation is much closer to send
- currently weekly digest is still sent only on Wednesday (but this logic should support configuration change in the future)

feat: send weekly digest per timezone offset

---

__tests__/triggers/user.ts

Hopefully fixes flaky test with comments feed. https://app.circleci.com/pipelines/github/dailydotdev/daily-api/9579/workflows/ed62130f-b122-451c-bd8a-4350e8035d4a/jobs/38531/tests
I found that `vordr flag` suite saves fixture for 4 comments to have `vordr: true` which is exact difference of test case failing:
This happens because we run our tests in parallel (over multiple workers) so even though its in describe they will execute in the same time against the db, hence the flakiness.

fix: flaky comment feed test

---

src/temporal/config.ts
src/types.ts

- env files
- all required env files are typed as `string` so that they are not optional (`string | undefined`) as default `process.env` type

feat(strict-ts): apply to env variables

---

__tests__/sources.ts
src/schema/sources.ts

Filtering `featured` squads is easy, as we just need to know if the value is true. However, when we want to filter non-featured Squads, we must also check whether the flags exist already. As seen on the first commit, the query failed.

fix: filter non-featured flags

---

src/data-source.ts

When running seed script for example it would fail because password would be `undefined`.

fix: default values missing for local adhoc

---

__tests__/common/pubsub.ts
__tests__/fixture/post.ts
__tests__/workers/cdc/primary.ts
src/common/date.ts
src/common/pubsub.ts
src/workers/cdc/common.ts

- content updated topic will now get messages in protobuf format (Viktor is the only subscriber currently)
- added support to send Buffer messages to `publishEvent`
- also fixes sending ns/ms instead of seconds as timestamp

feat: content updated protobuf format

---

.infra/Pulumi.prod.yaml
package-lock.json
package.json
src/integrations/retry.ts
src/telemetry/common.ts
src/telemetry/metrics.ts
src/telemetry/opentelemetry.ts

I have verified on local environment if I set the traceparent header to force sampling, it will let us trigger tracing when sampling ratio is 0.

chore: fix deprecation warnings and re-enable tracing with 0 sampling

---

src/graphorm/graphorm.ts
src/graphorm/index.ts

feat(strict-ts): apply to graphorm

---

src/common/twitter.ts
src/common/utils.ts
src/entity/ContentImage.ts
src/entity/posts/ArticlePost.ts
src/entity/posts/Post.ts
src/notifications/types.ts
src/workers/cdc/common.ts
src/workers/cdc/primary.ts
src/workers/generators/generateEditImagesHandler.ts
src/workers/newNotificationV2Mail.ts
src/workers/notifications/userStreakResetNotification.ts
src/workers/notifications/utils.ts
src/workers/personalizedDigestEmail.ts
src/workers/postAddedSlackChannelSend.ts
src/workers/postUpdated.ts
src/workers/userCreatedPersonalizedDigestSendType.ts

- workers
- handling email/notification worker
- stuff that accumulated in the meantime

feat(strict-ts): apply to workers

---

bin/syncMembersCount.ts
src/migration/1726147441577-SourceMembersCountFix.ts

There is an instance where the user does not start being a member, that is when creating a new Squad. To make it more accurate, we check whether the user is not blocked.

fix: members count trigger when creating a squad

---

src/telemetry/opentelemetry.ts

Ensure that we only set span labels while the span is still open.
In cases where the request is cancelled while it is still running (i.e. user navigated away)

fix: only add span labels if span is still open

---

src/schema/posts.ts

We missed the offset on the snippet query.

fix: we need offset on snippet query

---

__tests__/sources.ts
bin/categorizedSquads.ts
bin/common.ts
bin/insertCategories.sql
bin/updateSquadsCategory.ts
src/entity/sources/SourceCategory.ts
src/migration/1726584940063-SourceCategoryPriority.ts
src/schema/sources.ts

- Introduce a new column to handle ordering based on our demand.
- Apparently, there are some changes with the categories. Rather than reusing an existing entity and just updating the title, it might become inaccurate. Hence, deleting the rows instead. Good thing that we also have no Squads with any category yet. Although they should be safe as cascading would take effect and null would be set in any case.
- Another option is to turn the `enabled` to `false` values.
- ~~Removed `['General', 'DevOps', 'Cloud', 'Data']`.~~
- ~~Added `['Basics', 'DevOps & Cloud', 'AI', 'Open Source', 'DevRel']`~~
- Removed every category (good thing no one is using any of the items yet). This is to make it easier to manage in the future and better devex. We will run a once off script to insert the data along …

feat: order by priority column

---

src/routes/index.ts

Removing `/boot` and `/graphql` from disallowed paths. 
But maybe we want do the the reverse at some point disabling only the crucial ones and allowing the rest [like gitlab do](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/39520).

fix: allowing boot and graphql endpoints to bots

---

.infra/Pulumi.adhoc.yaml
package-lock.json
package.json
src/telemetry/opentelemetry.ts

- Fix deprecated config
```
logRecordProcessor: LogRecordProcessor;
```
got deprecated in favour of
```
logRecordProcessors?: LogRecordProcessor[];
```
- Change exporter used in adhoc to a more stable one
The GRPC exporter was sometimes complaining about jaeger being too slow to respond, so replaced it with HTTP exporter. **This is only relevant for adhoc**
- Remove gcloud cloud-trace-propagator
It was not being used, and wont be used

chore: minor opentelemetry tweaks

---

src/graphorm/index.ts

Fixes following (no pun intended 😆 ) [issue](https://dailydotdev.slack.com/archives/C07ATUPBPJ9/p1726756727350719)
Basically following and followers queries already define `:userId` parameter which means that inside graphorm `contentPreference` field resolver it gets overwritten and then it always takes the state from parent entity.
This fixes it by naming the param inside the field resolver to unique name.

fix: content preference state on follow queries

---

__tests__/boot.ts
__tests__/workers/cdc/primary.ts
src/entity/user/User.ts
src/migration/1726691862710-User.ts
src/routes/boot.ts
src/schema/users.ts

Extends user table to add two new columns, `followingEmail` and `followNotifications`
AS-584

feat: add new notification columns to `User`

---

src/common/search.ts
src/schema/search.ts

@capJavert Please let me know what you think before I proceed.
The idea is that for the page query we can enable this and for the suggestion query we omit it.
Since the contentpreference is needed for more then 1 entity this seemed ok, but let me know if you are against it.

fix: allow content preference on search

---

src/schema/sources.ts

This was a retro-compatibility fix. 
Current frontend do not send the `isPrivate` field and make every squad created a public squad.
Tested create/edit/delete squads both private and public, everything seems to be ok 👍

fix: squad create as public if `isPrivate` was not passed;

---

src/schema/actions.ts
src/schema/comments.ts
src/schema/compatibility.ts
src/schema/feeds.ts
src/schema/keywords.ts
src/schema/posts.ts
src/schema/sources.ts
src/schema/tags.ts
src/schema/users.ts

Add implementations for read replica on all `graphorm.query` calls that can use it.

chore: add query read replica implementation

---

src/graphorm/graphorm.ts

No direct users, but wanted to enable so we can move some non graphORM queries

chore: add support for read replica to all query functions

---

src/graphorm/index.ts

By default we used to return 50 members and we show only 5.
That's a lot of unused data. and I mean A LOT! 🤯

fix: reduce members limit for source

---

src/schema/trace.ts

Noticed that there's still some error messages on the graphql requests

fix: ensure span is still recording when adding gql attributes

---

.env
.infra/Pulumi.prod.yaml
src/remoteConfig.ts

Just to make it easier when working locally to replace config key with something else without doing any code changes that can be committed accidentally.

feat: remote config key as env

---

__tests__/workers/notifications.ts
src/entity/notifications/NotificationV2.ts
src/migration/1727870383565-NotificationV2PostAddedUnique.ts

AS-602 When user is subscribed to source and user we want them to receive only one notification.
Tried a bunch of stuff, querying on different places, dedup logic and this morning had an idea with triggers but everything involved some kind of additional query(s) to the DB which I wanted to avoid because notifications can be sent to a lot of users at the same time. 
At the end realized that because all post added notifications have same post id (referenceId) and referenceType (post) with which we can dedup them with unique index over post added types.
Minor edge case is that depending on which order notifications get published user will sometimes get `user_post_added` notification and sometimes `source_post_added` because its basically race condition. We should not be worried about that …

feat: unique dedup post added notifications

---

__tests__/notifications/index.ts
__tests__/notifications/notificationWorkerToWorker.ts
src/entity/notifications/UserNotification.ts
src/migration/1728030331673-UserNotificationUniqueKey.ts
src/notifications/common.ts
src/notifications/index.ts

AS-602
Iteration on https://github.com/dailydotdev/daily-api/pull/2306, still using constraint approach but we now introduce `uniqueKey` for `user_notification` so we can dedup over notification type and other params. 
Unique key is built from notification type, referenceId and referenceType.
We unique constraint over `userId + uniqueKey` because we still want to have notifications across different users. 
By default `uniqueKey` is `NULL` and ignore by constraint.

fix: user post duplicate user notification

---

src/telemetry/opentelemetry.ts

Noticed traces lost some metadata since last week deployment of strict ts. 
In https://github.com/dailydotdev/daily-api/pull/2173 I refactored types so that span options defaults to `{}`. This could be the case of why metadata was missing because it would overwrite whatever active span already had. 
Not breaking anything and will be able to validate after deployment.

fix: telemetry span options

---

.infra/index.ts

This is to prevent the HPA for api-bg to scale up when digest subscription is filled

fix: use subapp instead on api-bg

---

__tests__/workers/cdc/primary.ts
src/entity/user/User.ts
src/workers/cdc/primary.ts

We set the expiry of the cache until the next day, regardless if the next day is a weekend.
There is one issue though, we have a cron job that resets the cache in an interval, and when it runs on the weekend, let's say Saturday, the cache expires on Sunday which the user might have not logged in and defeats the purpose of the restore on weekends.
We are now setting the cache until the next valid day, so the previous case still applies on weekdays, but now, on weekends, we set the expiry until EOD of the next weekday. In the case above, EOD Monday.

refactor: cache expiry to be next weekday

---

src/graphorm/index.ts

Intermediate fix to enable more children comment loading.
Current limit was 50, we have comments with over 50 sub comments.
See issue:
https://github.com/dailydotdev/daily/issues/1483
Note:
This is a quick fix, we should work on better comment handling in general.

chore: increase sub comment limit

---

__tests__/common/mailing.ts
__tests__/users.ts
__tests__/workers/userCreatedCio.ts
__tests__/workers/userUpdatedCio.ts
src/cio.ts
src/schema/users.ts
src/workers/userCompanyApprovedCio.ts
src/workers/userCreatedCio.ts
src/workers/userStreakUpdatedCio.ts
src/workers/userUpdatedCio.ts

> When sending `cio_subscription_preferences` from `cio.identify` (for user) we have to include all existing topics in the object. If not CIO will take what it has and make everything else a default value (that is set in cio topics area) and for stuff like digest and follow it will become "subscribed" again.
Above was hotfixed in https://github.com/dailydotdev/daily-api/pull/2314
In addition to above, this PR also sync other subs in the same way. 
In addition it also syncs digest after subscribe/unsubscribe mutations through `identifyUserPersonalizedDigest` util.
More discussion in [thread](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1728038592931229)

fix: properly sync all topics to cio

---

src/entity/notifications/UserNotification.ts
src/migration/1728894860612-UserNotificationIndex.ts

We where missing this tripple column index on UserNotification (which is the most requested query)
Pre tested in production (removed index after test and renamed it)

fix: add missing index for notifications

---

__tests__/notifications/index.ts
src/notifications/builder.ts
src/notifications/generate.ts

There's an [issue](https://github.com/dailydotdev/daily/issues/1488) where if you bookmark shared post without title it will show `null`.
This was actually a deeper lying issue in notification generation.
So decided to fallback in several places to sharedPost.title if it exists.

fix: null notifications

---

src/common/feedGenerator.ts

Already properly indexed and not much we can win here, besides doing a slightly better select (only omits 1 field)
Alternative extra ticket could be that we could potentially store this config in Redis as we always know when it updates?
CC: @capJavert for your evaluation if it's worth it.
WT-2226 #done

fix: prefer optimized select

---

src/data-source.ts

https://github.com/dailydotdev/daily-api/pull/2340 fixed amount of pool calls that boot does but I still see some longer calls. 
Now I can confirm that calls that take longer are the new connections that need to be added to pool, while just querying existing connection from pool is "cheap".
To try and mitigate I increased `max` connections allowed inside pool which should lower amount of times the pool needs to create new connections. Our max con on pg instances is 1000.
Trace below from production, below connect call takes 80% of total request time, which makes boot latency spike.
[WT-2230](https://dailydotdev.atlassian.net/jira/software/projects/WT/boards/11?selectedIssue=WT-2230)
[WT-2230]: https://dailydotdev.atlassian.net/browse/WT-2230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …

feat: increase pool size

---

src/common/users.ts
src/entity/View.ts
src/migration/1728989030929-ViewRelationUserId.ts

Decided not to introduce the uniqueKey index, see discussion [here](https://dailydotdev.slack.com/archives/C02E2C3C13R/p1728989949471359).
The query format changes a little bit (mostly order optimization that PG prefers)
And making the types of `userId` match to help reduce another 20/30ms delay.
| Before | After |
|--------|--------|
| ![Screenshot 2024-10-15 at 13 09 11](https://github.com/user-attachments/assets/728c0199-0dc2-4226-9856-617be03b06c6) | ![Screenshot 2024-10-15 at 13 10 04](https://github.com/user-attachments/assets/1db5c2d7-f20f-4902-8fb9-3eee4763d42c) | 
> Note: This doesn't include the varchar changes yet.
> Note: It's averages, ran about 10 queries on each type this was average
WT-2229 #done

fix: optimizations for reading tag query

---

src/common/users.ts
src/schema/users.ts

Reading streak queries also write while reading so we can't use read replica in this query. Found it from [logs](https://console.cloud.google.com/logs/query;query=labels.%22k8s-pod%2Fapp%22%3D%22api%22%0AjsonPayload.err.message%3D%22cannot%20execute%20UPDATE%20in%20a%20read-only%20transaction%22;summaryFields=:false:32:beginning;cursorTimestamp=2024-10-15T12:23:00.385Z;duration=P2D?project=devkit-prod&authuser=2)
Left the index from original PR. Reverts https://github.com/dailydotdev/daily-api/pull/2339

hotfix: revert reading streak to master

---

__tests__/search.ts
src/schema/search.ts

not a 100% sure what Meili has indexed for shared posts, but maybe it's the related post?
This should fix it on API side to not return those.

fix: should not return empty title posts

---

src/data-source.ts

Looks like #2351 lowered latency spikes significantly, there are some lower spikes still in 2-3 minutes period.
I can see that when those spikes happen its because pool needs to create new connections. Increasing idle timeout for connections in pool to see if retaining connections for a bit longer would lower amount of those smaller spikes since pool would be at maximum capacity for a bit longer.

feat: adjust idle timeout

---

src/common/queryDataSource.ts
src/graphorm/graphorm.ts

I noticed that in case of query failed `release` would not be throw. Don't think it had impact because we don't have failed queries on these but good to be safe in those cases.

fix: make sure release is called in case of error

---

src/data-source.ts

We want to test if spikes of the p99 latency of boot are due to pools catching up with traffic all the time after connections expiring due to being temporary unused.

feat: temp disable pool connection timeout

---

.infra/index.ts
.infra/package-lock.json
.infra/package.json

We already kill it every hour or so, so I think it can safely live on a spot node

feat: allow scheduling clickhouse sync onto spot nodes

---

.infra/package-lock.json
.infra/package.json

Enabled by default, so just updating pulumi-common

feat: run migration jobs on spot nodes

---

__tests__/__snapshots__/feeds.ts.snap
__tests__/feeds.ts
__tests__/integrations/feed.ts
__tests__/workers/__snapshots__/personalizedDigestEmail.ts.snap
bin/traces.ts
src/common/feedGenerator.ts

In an effort to reduce the load on the database, I merged together the different queries used to generate the feed filters object.
It also includes some minor optimizations.
If this will not reduce the load we can consider redis. Now with a single query it can be easier to cache it. I may also consider moving the javascript logic to the query itself but let's see.

refactor: use a single query for feed filters

---

package-lock.json
package.json

rolls back `@opentelemetry/instrumentation-http` because of issue with malformed forwarded headers that might occur
A [fix is proposed](https://github.com/open-telemetry/opentelemetry-js/pull/5099), so once that has been approved and released, we can upgrade this dependency

fix: rolls back `@opentelemetry/instrumentation-http` upgrade

---

__tests__/contentPreference.ts
__tests__/feeds.ts
__tests__/sources.ts
src/common/contentPreference.ts
src/entity/SourceMember.ts
src/entity/contentPreference/ContentPreferenceSource.ts
src/migration/1730390077794-ContentPreferenceSquad.ts
src/schema/contentPreference.ts
src/schema/feeds.ts
src/schema/sources.ts

AS-651
- add block mutations for all supported entities so far (with backward compatibility)
- squad entities (from other #2378)

feat: add block mutations

---

__tests__/users.ts
src/entity/user/UserStats.ts
src/graphorm/index.ts
src/migration/1730717128269-UserStatsTopReader.ts
src/schema/users.ts

feat: add total field to UserTopReader to get the users total amont of top reader badges

---

src/entity/user/UserStats.ts
src/migration/1730860362949-UserStatsIndex.ts

Query time goes from ~900ms to ~125ms.
Plan before index
```
Limit  (cost=0.15..88978.65 rows=3 width=96) (actual time=137.771..705.455 rows=5 loops=1)
->  Index Scan using ""IDX_user_top_reader_userId_issuedAt"" on user_top_reader user_top_reader_2ex  (cost=0.15..88978.65 rows=3 width=96) (actual time=137.769..705.452 rows=5 loops=1)"
Index Cond: ((""userId"")::text = 'XDCZD-PHG'::text)"
SubPlan 1
->  Seq Scan on user_stats us  (cost=0.00..29645.69 rows=1 width=8) (actual time=140.782..140.988 rows=1 loops=5)
Filter: ((id)::text = (user_top_reader_2ex.""userId"")::text)"
Rows Removed by Filter: 1244454
SubPlan 2
->  Subquery Scan on res  (cost=0.43..8.46 rows=1 width=32) (actual time=0.066..0.067 rows=1 loops=5)
->  Limit  (cost=0.43..8.45 rows=1 width=22) (actual time=0.049..0.049 …
```

fix: add missing index to `user_stats` table

---

src/entity/posts/FreeformPost.ts

Reduced `FREEFORM_POST_MINIMUM_CONTENT_LENGTH` to process most of the posts. Probably could set to 0 as well?
Did not change `FREEFORM_POST_MINIMUM_CHANGE_LENGTH`.

AS-615 reduce freeform post minimum content length

---

src/schema/sources.ts

- if you had a squad blocked the join would fail due to content_preference row existing
- added upsert + backward compatibility to avoid reseting referralToken
- test is already there but it was not showing due to catch inside joinSource mutation

fix: join squad even when already blocked

---

__tests__/sources.ts
src/schema/sources.ts

Introduces 2 new endpoints needed for source selection in onboarding.
- searchSources => Used for when you use the search box, needed slight different result from the suggestions one we have, so decided to do custom one.
- sourceRecommendationByTags => Initial page load, we pass the tags you selected on previous screen and find highest matching sources. (Needed to do 2 queries to avoid messy graphORM logic we couldn't deduplicate, and since it's once off this is fine)
AS-678

feat: add search source endpoints

---

src/index.ts

Uploaded a placeholder based on our library and color schema to cloudinary.
Which now resolves when `lettericon` endpoint hits.
Tested in both variations of the bar:

fix: add lettericon endpoint

---

src/index.ts

We need to support both the normal endpoint and the wildcard domain for `lettericon`

fix: also needed wildcard domain

---

queries/calculateTopReaders.sql
src/cron/calculateTopReaders.ts
src/notifications/builder.ts
src/notifications/generate.ts
src/workers/newNotificationV2Mail.ts

Minor adjustments to top reader:
- Moves the materialized view refresh out of transcation
- Excludes `dailydev` keyword from future runs
- Fallback to keyword value if `title` flag does not exist

fix: minor adjustments to top reader

---

__tests__/contentPreference.ts
__tests__/feeds.ts
src/common/contentPreference.ts
src/entity/contentPreference/ContentPreference.ts
src/entity/contentPreference/ContentPreferenceFeedKeyword.ts
src/entity/contentPreference/ContentPreferenceFeedSource.ts
src/entity/contentPreference/ContentPreferenceKeyword.ts
src/entity/contentPreference/types.ts
src/migration/1731044639557-ContentPreferencePKType.ts
src/schema/feeds.ts
src/schema/sources.ts

- PK for content_preference is now userId + referenceId + type
- solves deduplication of content_preference over [feed](https://dailydotdev.slack.com/archives/C07ATUPBPJ9/p1730894715539879)
- ContentPreferenceKeyword is used for my feed rows of feed_tag (feedId === userId)
- ContentPreferenceFeedKeyword is used for other rows like custom feeds
- same is done for ContentPreferenceSource with new ContentPreferenceFeedSource

feat: feed type content preference

---

src/entity/FeedTag.ts
src/migration/1731315131357-FeedTagDateColumns.ts

- add createdAt and updatedAt columns
- added updatedAt trigger so updatedAt is correctly set when updating filters (included only blocked column change since that is the only one that can really change)
- added index for filtering over updatedAt in migration script
Since migration is lot more heavy then I thought this will allow us to do a migration in more incremental way where we can set a date when we start it and then incrementally only update rows which changed after the set date.

feat: add date columns for feed_tag

---

src/workers/notifications/userTopReaderAdded.ts

Noticed after seed it goes into infinite loop due to scraper missing locally when generating badges, this is just a quick fix so it does not break dev locally.
cc: @omBratteng

feat: disable top reader worker locally due to crash after seed

---

__tests__/contentPreference.ts
src/common/contentPreference.ts

Just noticed in error logs some warns of PK violations due to existing records. Typeorm does not set correct type for sub entity.

fix: upsert when entry exists

---

__tests__/posts.ts
__tests__/workers/cdc/primary.ts
src/common/post.ts
src/schema/posts.ts

There are two things fixed here, separated by each commit:
- In our CDC pipeline, there can be a case where two of the same links were submitted. Is it not possible to process them at the same time when approved, in this case, the external link would have been created on the first instance, and on the second instance, it would produce an error due to having the same link.
- Second fix was on the submission of post for moderation. The values passed through the mutation would be present depending on the case. We have title, content, and commentary but the post entity only has a title and content.
- Freeform: must have a title and content. Empty `titleHtml` but `contentHtml` should be defined.
- Share (from internal id): must have `title` and `titleHtml`. Empty `content` and `contentHtml`.
- …

fix: external links submission

---

src/schema/posts.ts

Added sharedPost and post field in type, needed in moderation page list in order to show post preview

fix: add missing fields in type

---

__tests__/workers/newNotificationV2Mail.ts
src/workers/newNotificationV2Mail.ts

Currently, there is only 1 prop for us to send a name. We need to make it two so the names of the moderator and creator of the post be distinct from one another.

fix: post moderation submission email props

---

src/routes/webhooks/paddle.ts

We should only fire the event if subscription cycle actually changed, not any of the other changes.
I also decided to update our flags in this case so we have the right setting stored at all times.
AS-744 #done

fix: update subscription tracking

---

src/index.ts

Since we added lettericon proxy to API, we've been getting lots of extra logs, making it more difficult to go through production logs because of all the extra spam.
So this sets the log level for the proxy to `warn` instead of `info`

chore: reduce logging on lettericon proxy

---

__tests__/workers/__snapshots__/personalizedDigestEmail.ts.snap
__tests__/workers/personalizedDigestEmail.ts
src/common/personalizedDigest.ts
src/growthbook.ts

Add type for posts to allow flexible components and support ads.
The email template already supports it so it's safe to roll out. The existing one will drop the ad, and there's a new template that will present it which we gonna test

feat: ad placement in digest

---

src/common/users.ts
src/schema/users.ts

Expose the column that contains the timezone-adjusted column for last view at.

refactor: user streak to include last view with timezone

---

src/schema/search.ts

Noticed we actually only searched sources by name, added handle as well as some users prefer this.
The index we have actually already covers both name/handle as far as I can see.
Solves: https://github.com/dailydotdev/daily/issues/1604

fix: also search for source handles

---

__tests__/workers/personalizedDigestEmail.ts
src/common/markdown.ts
src/common/personalizedDigest.ts
src/common/post.ts

- no posts in email was due to outdated templates being scheduled on our email platform, it was a temporary issue and it should not happen now that everything scheduled before code change was deploy
- no title is because of shared posts, we can show shared post title
- no image, freeform post without image (we should technically load first image from content)
- also case for shared post, we would load image of a shared post
Closes https://github.com/dailydotdev/daily/issues/1600

fix: use shared and content title and image for post types

---

src/index.ts
src/remoteConfig.ts

- added origins support for remote config so I can test deployment easily without moving to *.daily.dev
- fallbacks to our original regex

feat: cors origins support for remote config

---

__tests__/notifications/index.ts
src/notifications/generate.ts

Rejection notification should now add the message.
Also, I noticed we don't require rejection reason, which should not be the case when rejecting a post. I will open a separate PR.

fix: rejection reason note

---

src/entity/contentPreference/ContentPreferenceSource.ts
src/entity/contentPreference/ContentPreferenceUser.ts
src/migration/1732464610853-ContentPreferenceIndexes.ts

These should be run first before merge, so that it doesn't hang on migration.
```sql
CREATE INDEX CONCURRENTLY IF NOT EXISTS "IDX_content_preference_source_id" ON "content_preference" ("sourceId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "IDX_content_preference_reference_user_id" ON "content_preference" ("referenceUserId");
```
This should fix the high query time when deleting user/ squad
<details>
<summary>Explain analyze results on user</summary>
```
"Delete on ""user""  (cost=0.43..8.45 rows=0 width=0) (actual time=0.062..0.063 rows=0 loops=1)"
->  Index Scan using ""PK_03b91d2b8321aa7ba32257dc321"" on ""user""  (cost=0.43..8.45 rows=1 width=6) (actual time=0.034..0.035 rows=1 loops=1)"
Index Cond: ((id)::text = 'LqpkFJyK0mXCplwKwBMen'::text)"
Filter: (((id)::text = '404'::text) IS NOT …
```

fix: add missing indexes for content preference

---

src/notifications/builder.ts
src/notifications/generate.ts

I just noticed, when a request is approved, the image used is not what we would want to display.
Member's POV (issue):
When approved, we should use the right image.

fix: approved post notification image

---

__tests__/users.ts
src/common/cloudinary.ts
src/common/users.ts
src/entity/user/User.ts
src/notifications/builder.ts
src/routes/devcards.ts
src/schema/users.ts

Rather than having a nullable prop that would signify that we should clear the image on certain mutations, we introduced a mutation to specifically do it. This makes maintaining how the clearance works much easier than remembering the meaning of the passed null values.

feat: clear image based on preset

---

__tests__/contentPreference.ts
src/common/contentPreference.ts

We should store blocked words lowercased.
(regardless feed implementation will do lowercasing both sides)

fix: we should store words lowercased

---

__tests__/common/post.ts
__tests__/notifications/notificationWorkerToWorker.ts
__tests__/posts.ts
src/common/post.ts
src/entity/posts/Post.ts
src/entity/posts/utils.ts
src/entity/user/UserAction.ts
src/paddle.ts
src/schema/posts.ts

Created new query to fetch the Smart Title or the original title of a post, based on the settings of the user.
If the user is a free user, we allow them to query one time before we return a forbidden error.
Also added a new post to seeds that has alt title added
TODO:
AS-803

feat: create query to fetch Smart Title / original title of post

---

src/common/feedGenerator.ts
src/common/personalizedDigest.ts
src/workers/notifications/articleAnalytics.ts
src/workers/notifications/articleReportApproved.ts
src/workers/notifications/collectionUpdated.ts
src/workers/notifications/postBookmarkReminder.ts
src/workers/notifications/postMention.ts
src/workers/notifications/sourceMemberRoleChanged.ts
src/workers/notifications/sourcePostModerationApprovedNotification.ts
src/workers/notifications/sourcePostModerationRejectedNotification.ts
src/workers/notifications/sourcePostModerationSubmittedNotification.ts
src/workers/notifications/sourceRequest.ts
src/workers/notifications/squadFeaturedUpdated.ts
src/workers/notifications/squadPublicRequestNotification.ts
src/workers/notifications/userStreakResetNotification.ts
src/workers/notifications/utils.ts
src/workers/userCompanyApprovedCio.ts
src/workers/userUpdatedPlusSubscription.ts

Moved workers:
- digest generation
- all workers not needing real time data (upvotes, rep, notification with counts)
Did not move any worker that needs to write or live data as well. Some of them I implemented but in testing realized they would return stale data since RR would be out of date. 
We could move rest of the real time workers if we moved CDC to RR, see [here](https://dailydotdev.slack.com/archives/C03C3JZPRU4/p1733484456135089), but something to be evaluated separate.

feat: move workers queries to read replica 1

---

src/dataLoaderService.ts
src/graphorm/index.ts
src/schema/posts.ts

Should reduce the need for querying user settings too many times in post queries
AS-813

refactor: use dataloader for storing user settings per request

---

__tests__/bookmarks.ts
src/entity/Bookmark.ts
src/schema/bookmarks.ts
src/schema/feeds.ts
src/types.ts

- On bookmark creation: 
- auto set last folder used from before (if any); 
- now returns the just-created item;
- Rename `addBookmarkToList` endpoint to `moveBookmark`

feat: Bookmark add and move methods

---

__tests__/bookmarks.ts
src/common/utils.ts
src/schema/bookmarks.ts

Looks like the regex didn't work for some icons. 
Since we are allowing only a strict amount of emojis changes the check for this subset.

fix: some icons don't pass folder validation

---

__tests__/boot.ts
src/routes/boot.ts

Fixes edge cases where user has upgrade to plus, but can not use the `fetchSmartTitle` on posts because JWT is outdated.

fix: re-issue JWT when user is upgraded to plus

---

__tests__/workers/notifications.ts
__tests__/workers/notifications/commentMention.ts
src/workers/notifications/commentMention.ts
src/workers/notifications/commentReply.ts

Send notifications to mentioned users even if they are part of the thread since we send a reply notification only to the parent commenter. We also respect mute settings now
MI-604 #done

fix: thread notifications

---

__tests__/bookmarks.ts
__tests__/posts.ts
src/entity/Bookmark.ts
src/migration/1733932616522-BookmarkUpdatedAt.ts
src/schema/bookmarks.ts

I found an edge case when you move a bookmark that isn't the last one saved. 
Adding a `updatedAt` column allows us to keep track of list changes and retrieve the very last used folder.

fix: add updatedAt for enabling query last assigned list effectively

---

__tests__/feeds.ts
src/entity/Feed.ts
src/migration/1734071060646-FeedTypeColumn.ts

Creates a new generated column `type` on `Feed` entity which is `main` when feed.id equals feed.userId, otherwise it is `custom`.
AS-837

feat: add new type column to Feed entity

---

.infra/index.ts
.infra/package-lock.json
.infra/package.json

This aligns us up with Debezium in Mimir.
Also now pulls debezium image from quay.io

chore: upgrade debezium to v2.4.2.Final

---

__tests__/bookmarks.ts
src/schema/bookmarks.ts

Currently is not filtering by userId, so the toast will show the first bookmark result (maybe not from this user). 
This is only for the return query, not the update/logic applied before.

fix: not filtering by userId on bookmark save

---

__tests__/notifications/index.ts
src/notifications/generate.ts
src/notifications/types.ts
src/workers/notifications/sourcePostModerationApprovedNotification.ts

When generating the approved notification, the reference is always the post, which means, the notification has already existed since it was approved the first time.
To set the uniqueness, we should set the key based on the moderation request id.

fix: approved edit notification not being sent

---

__tests__/feeds.ts
__tests__/integrations/feed.ts
src/common/feed.ts
src/common/feedGenerator.ts
src/entity/Feed.ts
src/integrations/feed/configs.ts
src/integrations/feed/types.ts
src/schema/feeds.ts

- apply new flags to filters
- send new filters in config generator
- move customFeed query to feed endpoint and custom feed config name (confirmed name with Vas)
- currently not moving to RR because I don't have time to test if any edge cases, will log

feat: add flags filters for feed config

---

__tests__/comments.ts
__tests__/posts.ts
__tests__/setup.ts
src/common/rateLimit.ts
src/directive/rateLimit.ts
src/remoteConfig.ts
src/schema/comments.ts
src/schema/posts.ts

Rate limit also affects our power users and I'd like to avoid that. Hence, introducing reputation based rate limiting. It will allow us to set stricter limits to new accounts with low reputation to deal with the spam

feat: rate limiting based on reputation

---

.infra/Pulumi.adhoc.yaml
__tests__/boot.ts
__tests__/feeds.ts
src/common/constants.ts
src/routes/boot.ts
src/schema/feeds.ts

AS-874
also not removing default custom feed if not plus

feat: limit custom feed view from date

---

src/entity/Prompt.ts
src/migration/1735645895838-Prompt.ts

Add the prompt table and seed it directly.
(added order as I missed this in RFC, but seems important)
Also as requested by platform we should start having created/updated on all tables for future proofing.
#AS-901 #done

feat: add prompt table and seed it

---

__tests__/workers/__snapshots__/postUpdated.ts.snap
src/entity/posts/Post.ts
src/migration/1736519518183-PostTranslations.ts

Adds new `translation` column to `Post`.
```js
{
// First implementation only has title
"title": {
"es": "Titulo",
"no": "Tittel",
},
// Future expansion to other fields:
"summary": {
"es": "Sumario",
"no": "Sammendrag",
}
}
```
AS-921

feat: add new `translation` column to `Post`

---

__tests__/workers/cdc/primary.ts
src/entity/posts/FreeformPost.ts

Removing the limits had the effect of unusually high number of posts sent to Yggdrasil. But it did not result in corresponding number of new posts created in database. So I suspect most of updates were sent when freeform post was changed in any way (not just content). 
Now I am trying to leave minimal threshold. I could alternatively check if `len(change) > 0` but decided to keep constants as easy way to change threshold in the future.

feat: reduce freeform content change trigger threshold

---

src/schema/users.ts

fixes calendar heatmap [thread](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1737040404925759)
- for reading streaks we needed exact times with time portion of date so that we can accurately know when did user read occur, which conflicted with a way we return read history currently
- this adds a `grouped` param which for now allows us to retain that functionality for calendar heatmap
- heatmap will again return dates in user's timezone to preserve heatmap logic, we can look into adjusting that in the future but for now its ok
Frontend PR https://github.com/dailydotdev/apps/pull/4073

feat: add grouped argument so we can extract grouped dates

---

.infra/common.ts
__tests__/workers/postDeletedSharedPostCleanup.ts
src/workers/index.ts
src/workers/postDeletedSharedPostCleanup.ts

We decided not to show shared post that have deleted reference on feed anymore.
Luckily `showOnFeed` handles all feed types for us.
To retro fix I suggest we simply run a manual query. (Probably very few hits anyway)

fix: don't show shared post deleted on feed

---

__tests__/posts.ts
src/entity/posts/Post.ts
src/graphorm/index.ts
src/schema/posts.ts

Expose `translation` field on `Post`. It returns an object containing keys of what translations are available. Currently we only return `title`, but it can be extended in the future.

feat: expose translation field on Post

---

__tests__/posts.ts
src/entity/posts/Post.ts
src/entity/posts/utils.ts
src/workers/cdc/primary.ts

When a post title is changed, we want to clear out the translation, so that we can fetch translation for the new title.

feat: clear title translation when post title is changed

---

__tests__/workers/postTranslated.ts
src/workers/postTranslated.ts

During the demo, I noticed that it didn't store translations where the translated title contained `'`, because it wasn't getting escaped properly 🙈

fix: escape post translated JSON

---

__tests__/posts.ts
src/entity/posts/Post.ts
src/entity/posts/utils.ts
src/workers/cdc/primary.ts

Trying this again... now handles when `translation` is `{}` and when it contains non-object values like `{"key": "value"}`

feat: clear title translation when post title is changed (2nd try)

---

package-lock.json
package.json
src/index.ts

It has been commented out for almost 3 years https://github.com/dailydotdev/daily-api/pull/855, so I think we can safely remove it

chore: cleanup commented out @fastify/websocket

---

__tests__/posts.ts
src/schema/posts.ts

Required to do some real time translation on webapp side

fix: expose `post` `language`

---

__tests__/posts.ts
src/entity/posts/utils.ts
src/schema/posts.ts

New flow that will always share 1 up only.
If 1 up is a shared post with commentary we re-share that.
If 1 up is a shared post with no commentary we share it's parent.
if 1 up is some other post we just share that.

fix: new feature for shared post

---

.infra/Pulumi.adhoc.yaml
.infra/Pulumi.prod.yaml
__tests__/setup.ts
src/Context.ts
src/entity/user/utils.ts
src/remoteConfig.ts
src/types.ts
src/workers/postTranslated.ts

Matches Kvasir so they validate the same languages.

refactor: read valid languages from remote config

---

__tests__/workers/postTranslated.ts
src/workers/postTranslated.ts

Updates the query to not override already existing translations for that language.
AS-968

feat: add smartTitle as a translatable field

---

src/workers/notifications/userGiftedPlusNotification.ts

Split condition because `warn` was firing for each user subscription purchase thus spamming a bit too much
We now:
- early return when user is not gifted, basic case where user bought subscription for themself
- warn if user was gifter but was already gifter id is missing

chore: adjust when we log warn for gift notification

---

src/schema/users.ts

Investigated the issue with regards to streak being unable to restore, unfortunately were not able to find fault - even simulated the user's case through tests. We are adding temporary logging until we find the root cause once it occurs again.

chore: logging when user is unable to restore

---

__tests__/notifications/index.ts
__tests__/posts.ts
src/common/post.ts
src/notifications/builder.ts
src/notifications/generate.ts
src/schema/posts.ts
src/schema/sources.ts

Enables a moderator to view moderation items from multiple squads at once, as well as bulk approve for multiple squads at once.

feat: multi squad moderation

---

src/common/post.ts

Added vordr check to the common moderation fetch logic, so that it's the same as for just a single squad

fix: add vordr check to common moderation query

---

__tests__/feeds.ts
__tests__/integrations/feed.ts
src/common/feedGenerator.ts
src/integrations/feed/types.ts

Somehow it ended up being sent under `thesholds`, but `min_thresholds` should be top level.
https://github.com/dailydotdev/daily/issues/1743

fix: feed thresholds under wrong name in config

---

__tests__/posts.ts
src/common/post.ts
src/graphorm/index.ts
src/schema/posts.ts

- when smart title is fetched we want to know if it was translated as well
- exposed the same `translation` field

feat: expose translation field on fetch smart title

---

src/schema/search.ts

I saw the suggestion one didn't filter out deleted/private posts.
It should as they not accesible for the masses.
Then it's also inline with the actual post page.

fix: suggestions should keep same logic as posts

---

.infra/.npmrc
.infra/package.json
.infra/pnpm-lock.yaml

Because of how `pnpm` isolates modules, it's easiest to add `knex` as a direct dependency

fix: hoist packages in infra

---

Dockerfile.dev

missed updating dev image version

chore: docker dev image

---

src/workers/newView.ts

We seemed to always trigger this message regardless of the fail reason.
(might have been added after logs tbh)
So now we only log the user missing when that's the error.
Other cases likely mean user just not eligible for streak.

fix: add better log tracking

---

__tests__/boot.ts
src/routes/boot.ts

Exposes the plus provider in boot. Need to use it in webapp to determine what plus to show in app

feat: add `plusProvider` to boot

---

src/common/personalizedDigest.ts
src/integrations/garmr.ts

- expose events for garmr so that different instances can have its own subscriptions
- refactor digest to use the new implementation

feat: add garmr events support

---

src/common/njord.ts
src/routes/boot.ts

- skip caching garm response (when breaker is open since it already locally returns), this will allow for service to return instantly and fill cache with real response after error
- handle balance account missing to avoid triggering garm, this error is expected for all new users and handled as zero balance

fix: skip caching garm response

---

src/entity/user/User.ts
src/migration/1741863600700-UserUniqueAppAccountToken.ts

It has a very low chance of happening as it is an UUIDv4, but better be safe

fix: ensure `appAccountToken` is unqiue

---

Dockerfile

Forgot that we run as user `node` and default permissions are `600`, so the user wasn't allowed to read the certs.

fix: add correct permissions on apple root certs

---

src/routes/webhooks/apple.ts
src/types.ts

:fml:
Error didn't occur in sandbox, because there it doesn't care about the `appAppleId` :triggered:

fix: parse `appAppleId` as int

---

src/routes/webhooks/apple.ts

Apple sends [`renewalPrice`](https://developer.apple.com/documentation/appstoreservernotifications/renewalprice) as "milliunits" just because... :fml: :triggered:

fix: correct price when converting currency

---

src/routes/webhooks/apple.ts

- Add the `notification` payload to the error log when user does not have access to sandbox
- Add the `environment` to all logs too

fix: log `notification` in sandbox endpoint

---

.infra/index.ts

Adds the liveness probe to the API pod in adhoc environment, so that it'll restart it when the API has crashed for some reason.
Because we're using nodemon in adhoc environment, the pod doesn't really crash when API crashes, because nodemon is still running.

fix: improve DX by adding liveness probe to API pod

---

.env
.infra/Pulumi.adhoc.yaml
.infra/Pulumi.prod.yaml
__tests__/boot.ts
src/cookies.ts
src/integrations/freyja/clients.ts
src/integrations/freyja/index.ts
src/integrations/freyja/types.ts
src/routes/boot.ts

Introduce a new boot endpoint for web funnels. It's a lean version to optimize for speed.
It calls Freyja to fetch the funnel and has simple logic for the experimentation.

feat: funnel boot

---

src/common/paddle.ts
src/cron/calculateTopReaders.ts
src/entity/user/utils.ts
src/routes/webhooks/customerio.ts
src/routes/webhooks/paddle.ts
src/workers/notifications/index.ts

Log the entire error, and not just the error message, for better debugging.
Also fixed a few other `logger.error` where it logs to `error` instead

fix: log entire error for paddle generic error

---

.infra/index.ts

Decrease the ws memory limit to 1.25 GiB, and request 800 MiB memory

chore: adjust ws memory limit and split into r/l

---

.infra/index.ts

- set HPA to trigger at 130% of requested memory (~80% of limit)
- and don't request 300 cores (instead of 0.3 core)
Expect pulumi to fail, as I force applied fix

fix: set correct memory limit for ws hpa

---

src/routes/webhooks/paddle.ts

The value returned by Paddle event is `year`. We've been using `yearly` since then. To make them consistent from the past, we are going to keep using `yearly`.
I will run a manual update to around 15 records once this is merged.

fix: uniform value for the subscription cycle

---

__tests__/helpers.ts
__tests__/private.ts
__tests__/users.ts
src/entity/user/UserAction.ts
src/entity/user/utils.ts
src/schema/actions.ts
src/schema/users.ts

Query will be called from frontend to check user's region and set correct `coresRole` based on it. It is a once off based on user action. 
Frontend call https://github.com/dailydotdev/apps/pull/4353

feat: check cores role

---

src/common/paddle/index.ts
src/routes/webhooks/paddle.ts

With one-step checkout `transaction.ready` happens immediately so most transaction would end up in processing/pending state even though user maybe did not even interact with checkout. This keeps transaction in `created` state until user actually tries to pay and then we start processing.

feat: adjust transaction processing

---

__tests__/devcard.ts
src/common/devcard.ts
src/schema/users.ts

In production, the `UserShortInfo` includes `coresRole` on `User`. It was missing in the user query, so it was throwing a `Cannot return null for non-nullable field User.coresRole.` error.
Noticed this because my DevCard GH workflow was throwing errors.

fix: make `coresRole` optional

---

.infra/.gitignore
.infra/package.json
.infra/pnpm-lock.yaml
Tiltfile

Temporarily from git because unable to publish new version at the moment :fml:
New in this version, is that it can now read secrets from a local `.env` file inside `.infra` directory. That way you can manipulate env variables without adding them to pulumi config and accidentally committing it.
Also new, if it detects a change in the `.env` or pulumi config, it will re-deploy the pods so that it has the new env variables loaded. Unfortunately, only the `.env` changes will automagically trigger pulumi update, as detecting change in the pulumi config will just cause infinite loops (because of image tag).
But for that, I added a new button to Tilt, that triggers pulumi up from Tilt :)

chore: update pulumi-common

---

.infra/package.json
.infra/pnpm-lock.yaml

This pull request updates the dependency versions for `@dailydotdev/pulumi-common` in the `.infra` package files. The most important changes are:
Dependency updates:
* [`.infra/package.json`](diffhunk://#diff-37e1ff10ed9cd0f932c497ce8c56ac4d56c676c48934656bae2fe84582684c10L10-R10): Updated the `@dailydotdev/pulumi-common` dependency from a specific GitHub commit to version `^2.7.0`.
* [`.infra/pnpm-lock.yaml`](diffhunk://#diff-5c2618ceb30b389b2fafabaf477a1adf2abcbd2a211d4a7efb01f62336288db6L12-R13): Updated the `@dailydotdev/pulumi-common` dependency specifier from a specific GitHub commit to version `^2.7.0`.
* [`.infra/pnpm-lock.yaml`](diffhunk://#diff-5c2618ceb30b389b2fafabaf477a1adf2abcbd2a211d4a7efb01f62336288db6L30-R31): Updated the `@dailydotdev/pulumi-common` package resolution …

chore: install pulumi-common from npm

---

__tests__/routes/private/kvasir.ts
src/routes/private.ts
src/routes/private/kvasir.ts

Creates a new endpoint that Kvasir will call to fetch posts, and it will only return the posts that the user has access to.
Kvasir calls the endpoint by emulating being the user, where it forwards the users auth token as the da3 cookie in the request.
https://github.com/dailydotdev/kvasir/pull/15
AS-1002

feat: new private endpoint for Kvasir

---

Dockerfile.dev

Minor DX improvement where we install utils like `ping` and `curl` in the dev image, so it's available in the container when running in adhoc. So we don't have to manually install it.

fix(dx): install ping and curl in dev image

---

src/common/njord.ts
src/workers/transactions/userReceivedAward.ts

- got little carried away with read replica, which can be outdated during multiple mutations, so moving everything to master
- also moved worker since cdc also listens for master changes

fix: use master for award mutation queries

---

src/routes/boot.ts

Add optional chaining to userId and session checks in funnel data retrieval
| Cloud | Vercel |
|--------|--------|
| <img width="1211" alt="image" src="https://github.com/user-attachments/assets/b4138808-2b09-4f02-a069-93ba6f40924b" /> | <img width="1211" alt="image" src="https://github.com/user-attachments/assets/531f229a-97dc-4c7b-8f91-aefbb48d91a1" /> |

fix: funnel return 500 when userId is read

---

src/entity/PostReport.ts
src/entity/common.ts
src/migration/1745812404446-PostReportLength.ts

Updated post report reason. Also updated the maximum length of reason, since "MISINFORMATON" and some other currently unused words were too long

feat: update post reasons

---

__tests__/paddle.ts
src/schema/paddle.ts

Add a `locale` param for requesting the pricing preview.

refactor: pricing preview to add locale option

---

__tests__/common/paddle/pricing.ts

As Ido asked, since we moved the formatter logic from the apps repo to API repo, we should cover the tests that were from the original code. Basically the ones that are currency-specific.
Even though we already covered a wide coverage of the cases, it shouldn't hurt to add more so I've committed more 🚀 
Referenced original tests: https://github.com/dailydotdev/apps/blob/df596ba2d619272f6b386cc25ad5b765ee9636d1/packages/shared/src/features/payment/hooks/usePricingCycleConverter.spec.ts

test: price formatter with the original test cases

---

__tests__/common/njord.ts
__tests__/routes/webhooks/apple.ts
__tests__/routes/webhooks/paddle.ts
src/common/apple/purchase.ts
src/common/apple/subscription.ts
src/common/apple/types.ts
src/common/apple/utils.ts
src/integrations/analytics.ts
src/routes/webhooks/apple.ts
src/routes/webhooks/paddle.ts

- support for IAP and one time purchases
- refactor apple webhooks file to common to split and reuse common logic
- will work on adding mores tests for IAP flow in next PR after some sandbox testing e2e if needed

feat: cores iap

---

__tests__/users.ts
src/common/user.ts

From Paddle's side of things, there is no subscription ID for gifted Plus membership. Hence we get an error that the subscription is not found and the process causes to throw an error.

fix: deleting an account with gifted subscription

---

__tests__/boot.ts

Noticed test is flaky sometimes due to other tests modifying subscription flags on same user.

fix: flaky boot test

---

__tests__/common/personalizedDigest.ts
src/common/personalizedDigest.ts
src/integrations/skadi/types.ts

Skadi response can be `{}` when no ad is available.

fix: skadi response can be empty

---

__tests__/comments.ts
__tests__/posts.ts
src/entity/user/UserTransaction.ts
src/graphorm/index.ts
src/migration/1747309505414-UserTransactionValueDesc.ts
src/schema/comments.ts
src/schema/njord.ts
src/schema/posts.ts

Previously the awards listings would use product current value when showing awards, now I added transaction value so that even when product prices change we still show product price at the time of award.

feat: transaction value for awards

---

src/migration/1746779086984-DropRoleContentPreference.ts

[Omitted from the migration](https://github.com/dailydotdev/daily-api/pull/2377/files#r1829110354) from #2377, but should be safe to drop now

chore: drop deprecated column `role` from `content_preference` table

---

src/schema/common.ts
src/schema/search.ts

Since we don't know total, we need to evaluate page to page.
But since we reuse the meiei one for now I adjusted it a bit hacky to start with.

fix: mimir pagination works differently

---

__tests__/paddle.ts
__tests__/routes/webhooks/apple.ts
src/common/paddle/pricing.ts
src/entity/ExperimentVariant.ts
src/migration/1748371994832-ExperimentVariationType.ts
src/schema/paddle.ts

Need to be able to get the metadata we have for prices too, and can't rely on `PricingPreview` if it returns an experiment variation with a price ID that doesn't match what the organization is subscribed with

feat: fetch our price metadata when getting price previews

---

__tests__/users.ts
src/common/paddle/index.ts
src/entity/user/utils.ts
src/integrations/analytics.ts

When claiming a subscription, we now add the userId to the subscriptions customdata, so that it gets properly updated on change events, i.e cancelling the sub.
Also added a log event to claiming a sub
[REF](https://dailydotdev.slack.com/archives/C02E2C3C13R/p1748340567666399?thread_ts=1748324078.181229&cid=C02E2C3C13R)

feat: add userId to subscription custom data on creation

---

__tests__/workers/organization/organizationUserLeft.ts
__tests__/workers/organization/organizationUserRemoved.ts
src/workers/organization/organizationUserLeft.ts
src/workers/organization/organizationUserRemoved.ts

It's not possible to query for the member in ContentPreferenceOrganization, because they have already been removed from the org 🙈

fix: query user and organization directly in organization notification worker

---

__tests__/boot.ts
src/routes/boot.ts

Onboarding funnels weren't keeping the sessionId. Just added a way to set the right one.

fix: onboarding funnel session cookies

---

src/common/paddle/slack.ts

For anon subs cycle can be undefined if events come in out of place, also added `anonymous` fallback for those orders to avoid undefined.
AS-1128

fix: slack message anon cycle

---

src/common/paddle/index.ts

Sub cancelation during user deletion sometimes fails due to sub being in locked/canceled state. While I did not find how to detect that locked state I did add a check for canceled state so we avoid canceling if already canceled by user. Added logging so we can monitor.
AS-1034

fix: check sub state before cancel

---

__tests__/posts.ts

Just solves some typing errors in the posts test. Leftovers from when I tried to get Claude to fix the test but explicitly told it to ignore TS errors, and it fixed TS errors instead and ignored test errors.

fix: types in posts test

---

__tests__/posts.ts
src/common/post/boost.ts
src/entity/posts/Post.ts
src/schema/posts.ts
src/workers/notifications/postBoostCompleted.ts

Previously, the integration to fetch a specific campaign only required a post ID and a user ID, but the endpoint has changed and now just requires the campaign ID instead. We will now need to store the campaign ID on our end if we want to fetch the details while the campaign is running.
I modified the `boosted` boolean property to be just `campaignId` that if it is not `null`, then there is a campaign running.
MI-888

refactor: boosted property to campaign id

---

__tests__/routes/webhooks/apple.ts
src/common/apple/subscription.ts

Consumption request event when refund is requested but still not processed by Apple.

fix: apple consumption request ignore

---

.env
.infra/Pulumi.adhoc.yaml
.infra/Pulumi.prod.yaml
__tests__/schema/posts/boost.ts
src/integrations/skadi/api/clients.ts
src/integrations/skadi/api/index.ts
src/integrations/skadi/api/types.ts
src/integrations/skadi/clients.ts
src/integrations/skadi/index.ts
src/integrations/skadi/types.ts
src/schema/posts.ts
src/types.ts

After setting up all the integrations, it was mentioned that the URL for the Post Boost feature is going to be different from our current Skadi integration client.
The changes here basically just copy-paste the existing functions and remove the newly unused ones from `SkadiClient` to `SkadiApiClient`.
MI-888

refactor: skadi boost client

---

src/schema/sources.ts

Filter out the user source from publicSourceMemberships query 
<table>
<tr>
<td>Before
<td>After
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/b372b52d-bd6f-4460-aeb5-92043a2cb6b2">
<td><img src="https://github.com/user-attachments/assets/20127656-5624-4175-917a-a3b303d8ac50">
</tr>
</table>

fix: hide user source from publicSourceMemberships

---

src/integrations/skadi/api/clients.ts

When there are no promoted posts, the value can be null.
MI-888

fix: empty promoted_posts property

---

.infra/common.ts
__tests__/workers/personalizedDigestEmail.ts
__tests__/workers/postAddedSlackChannelSend.ts
__tests__/workers/postAddedSlackChannelSendBrief.ts
src/common/personalizedDigest.ts
src/common/userIntegration.ts
src/workers/index.ts
src/workers/personalizedDigestEmail.ts
src/workers/postAddedSlackChannelSendBrief.ts

- added separate subscription to not mix up logic for other slack posts
- brief worker sends only the posts that user is author of, eg. their own briefs
- added exclusion for brief on other worker
- updated tests to reflect new guards

feat: send brief to slack

---

__tests__/schema/posts/boost.ts
src/common/njord.ts
src/common/post/boost.ts
src/schema/njord.ts
src/schema/posts.ts

Two things:
- Returning `referenceId`: to run some optimistic updates on applicable cases.
- Discussion link: We want to utilize the post's discussion link in certain cases, so it must be returned.
MI-888

feat: reference id on newly created transaction and comments permalink

---

__tests__/posts.ts
src/errors.ts
src/schema/posts.ts

So we can restart process and show loader again in case of an issue on client.

feat: return existing post id when brief is generating

---

__tests__/schema/posts/boost.ts
src/integrations/skadi/api/clients.ts
src/integrations/skadi/api/types.ts
src/schema/posts.ts

This was the source of the issue. However, we want to know more about it by wrapping it in a try-catch instead.
Only thing I can think of where this can break was if the `impressions` is actually a string. We'll find out.

fix: estimated boost reach - reduced params and returning pure int

---

src/migration/1754321021915-SourceMemberHasUnreadPostsIndexFix.ts
src/migration/1754397036839-SourceMemberHasUnreadPostsIndex.ts

Previous index did not actually do anything, so new migration to make it actually work.
AS-1172

fix: re-create index so that it actually works

---

__tests__/posts.ts
src/schema/posts.ts

Missed doing the "polyfill" in the `sharePost` mutation.
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1754424084071199

fix: ensure user source is created in the sharePost mutation

---

__tests__/workers/brief/userGenerateBrief.ts
src/workers/brief/userGenerateBrief.ts

To make brief shareable we decided to make them public since there's no private/personal info there

feat: make brief public

---

__tests__/workers/notifications.ts
src/workers/notifications/postAddedUserNotification.ts

I am still getting notifications for briefs of other users even after https://github.com/dailydotdev/daily-api/pull/2967

fix: do not send brief notifications from followed users

---

__tests__/users.ts
src/common/googleCloud.ts
src/schema/users.ts

I assumed that GCS automagically detected the content type on uploaded blobs, but it does not. so added the content type to blob metadata during upload.
AS-1177

fix: add content type metadata to blob

---

__tests__/sources.ts
src/schema/sources.ts

When querying for moderators we should also include admins.
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1755589022101189

fix: return both moderators and admin on moderator query

---

__tests__/boot.ts
__tests__/users.ts
src/common/geo.ts
src/entity/user/User.ts
src/routes/boot.ts
src/schema/users.ts
src/types.ts
src/workers/userUpdatedCio.ts

Adds location flags from our geo IP db, when user doesn't have them set in flags.
It's a one time call from the frontend so not too heavy load.
Preparation for the matching service to use, we'd like to start collecting it asap.
Ante noted we probably need to up memory on API pod.

feat: set location when it's not known in flags

---

__tests__/njord.ts
src/common/njord.ts
src/entity/user/UserTransaction.ts

So that cores can be more easily attributed back to entity from transaction.

feat: save entity reference on award

---

__tests__/notifications/index.ts
src/notifications/generate.ts
src/workers/newNotificationV2Mail.ts

Changing to use `referenceSource` instead of `referencePost` on `squad_member_joined` so that the `referenceId` is the source id. This is so we can mute this notification preference per squad on the notifications page on the frontend.
I address what happens to old notifications that still have the post id as reference in the frontend [PR](https://github.com/dailydotdev/apps/pull/4809)
MI-1003

feat: squad_member_joined should now have source.id as reference

---

src/integrations/skadi/api/v1/clients.ts

Being a preview tester, you will be able to test both flows (v1 and v2) through preview deployment and the current production env. To avoid breaking your dashboard until rollout, we will filter posts only on the legacy API. Note, the concern here (creating campaigns on both flows) will not break the regular user's flow, just for everyone within the team to have a better experience.

fix: preview testers backwards support for campaigns dashboard list

---

.infra/index.ts
bin/createClickhouseMigration.ts
bin/runClickhouseMigrations.ts
clickhouse/migrations/1756316678212_post_analytics.down.sql
clickhouse/migrations/1756316678212_post_analytics.up.sql
src/entity/ChMigration.ts
src/migration/1756375302904-ChMigration.ts
src/types.ts

Added a small script to run clickhouse migrations. Based it on lib I found, but opted to just copy small portion of functionality vs using the whole lib. Copied naming/structure of migrations from go projects.
Logic is:
- Discovers migrations named: {id}_{snake_case_name}.{up|down}.sql
- Records migration as dirty in the migrations_ch table on API
- Executes pending *.up.sql in ascending id order
- If any up fails blocks further execution
- Records each applied up into migrations_ch table (id, name, timestamp, dirty = true)

feat: clickhouse migrations support

---

__tests__/campaigns.ts
src/graphorm/index.ts
src/schema/campaigns.ts

We use the `campaignById` query to fetch the information about who boosted the Squad and more details, such as when it is going to end. Also removed the `@auth` directive as anonymous users are able to view Squads directory that has this feature.
For other Squad mods/admins:
For anonymous user:

refactor: campaign by id fetched by regular users

---

__tests__/campaigns.ts
src/common/campaign/common.ts
src/schema/campaigns.ts

We've separated the stats call from the list to avoid coupling things together.

feat: query campaign stats as a separate query

---

__tests__/workers/campaignUpdatedAction.ts
__tests__/workers/campaignUpdatedSlack.ts
__tests__/workers/notifications.ts
src/workers/campaignUpdatedAction.ts
src/workers/campaignUpdatedSlack.ts
src/workers/notifications/campaignUpdatedAction.ts
src/workers/notifications/postBoostAction.ts

Campaign v2 workers: if campaign does not exist, ignore it as [Viktor have said](https://dailydotdev.slack.com/archives/C07LHS7RXA4/p1756719562719959?thread_ts=1756718292.452039&cid=C07LHS7RXA4).
Campaign v1 workers: when a user is not found, log an error instead of throwing it.

fix: missing data from workers

---

__tests__/workers/campaignUpdatedAction.ts
src/workers/campaignUpdatedAction.ts

Skadi will send a `completed` event regardless of whether it was due to budget consumption or cancellation. As long as the state in Skadi turns from active to inactive, an event is sent.
When we cancel a campaign, on our side, we immediately set its state to Cancelled, so when Skadi triggers completed event, we don't have to overwrite it.

fix: workers receiving completed event

---

__tests__/workers/campaignUpdatedSlack.ts
src/common/slack.ts
src/workers/campaignUpdatedSlack.ts
src/workers/postBoostActionSlack.ts

Small addition to show team members on boosts.
Contemplated doing it inside the slack worker, but seemed more streamlined like this, with query client outside.

feat: show team members on boosts

---

__tests__/campaigns.ts
src/schema/campaigns.ts

I need to query campaigns for post Id to show them on analytics graph, so I exposed `entityId` so we can fetch it in the future for squads and so on.

feat: get campaigns per entity

---

__tests__/schema/opportunity.ts
src/graphorm/index.ts
src/schema/common.ts
src/schema/opportunity.ts
src/schema/organizations.ts

Remove GQL enums from Protobuf enums, use Int instead via custom scalar ProtoEnumValue, that way we can differentiate between actual Int and when we intend for proto enums.
The scalar ProtoEnumValue just accepts whole ints above and 0

refactor: remove gql enums of protobf enums

---

__tests__/schema/posts/boost.ts
src/schema/posts.ts

- we want to show estimate reach on analytics page while boost is active

feat: allow estimating reach for boosted posts

---

__tests__/campaigns.ts
src/schema/campaigns.ts

- reverted https://github.com/dailydotdev/daily-api/pull/3080 since code I modified was for v1
- now updated code for skadi v2 which frontend actually uses

feat: allow estimating reach for boosted posts v2

---

__tests__/fixture/opportunity.ts
__tests__/schema/opportunity.ts
src/graphorm/index.ts
src/schema/opportunity.ts

We don't want GraphORM to join the opportunity keyword to keyword table, so we need custom type for it, since we want to display any keyword they have

fix: return all opportunity keywords

---

src/entity/Organization.ts
src/migration/1757494437588-OrganizationFoundedType.ts

TIL `numeric` returns value as string

fix: organization founded column type

---

__tests__/keywords.ts
src/index.ts
src/schema/keywords.ts

Replace auth in favour of 1 hour long TTL. Keywords has a low chance of actually changing that often, so we can safely add a 1 hour long TTL of the query.
AS-1210

fix: replace auth with long ttl of autocompleteKeywords query

---

src/workers/worker.ts

To avoid forgetting it by mistake until we move

chore: require parseMessage on typed notification workers

---

__tests__/posts.ts
src/common/post.ts
src/graphorm/index.ts
src/schema/posts.ts

Poll options weren't added to the post moderation when we [updated](https://github.com/dailydotdev/daily-api/pull/3156) it.

feat: fetch poll options for moderation

---

src/schema/posts.ts

Missing resolver made the history page explode
MI-1047

fix: add resolver for endsAt

---

.infra/index.ts

This simplifies service account management, by just using one service account across adhoc projects, instead of one service account per adhoc project.
The secret is defined in adhoc-infra, so you need to update adhoc-infra to get it.
https://github.com/dailydotdev/adhoc-infra/blob/356217040d7e3cb6f5d95c27a5efab5bc3de35c2/index.ts#L36-L50

refactor: use common adhoc secret for gcloud credentials

---

__tests__/schema/opportunity.ts
src/schema/opportunity.ts

For example if in content there is a column name like `state`, typeorm will add quotes around `"state"` which then breaks insert. With params it does not add it so update goes through.

fix: insert formatting for opportunity json fields

---

__tests__/posts.ts
src/graphorm/index.ts
src/schema/posts.ts

We will show them instead of views

feat: expose impressions analytics under post query

---

__tests__/posts.ts
src/common/post.ts
src/entity/posts/FreeformPost.ts

Allows to create freeform posts without content
```json
{
"data": null,
"errors": [
{
"message": "Validation error",
"locations": [
{
"line": 14,
"column": 5
}
],
"path": [
"createPostInMultipleSources"
],
"extensions": {
"code": "ZOD_VALIDATION_ERROR",
"issues": [
{
"expected": "string",
"code": "invalid_type",
"path": [
"content"
],
"message": "Invalid input: expected string, received null"
}
]
}
}
]
}
```

fix: allow empty freeform content

---

__tests__/workers/extractCVMarkdown.ts
src/workers/extractCVMarkdown.ts

A temporary fix until I've backfilled all CVs and found all edge-cases

fix: don't throw error when gRPC error
